// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package calculatordb

import (
	"context"

	"github.com/google/uuid"
)

const currentMacroPlan = `-- name: CurrentMacroPlan :one
SELECT id, user_id, weight_kg, height_cm, age, sex, activity_level, goal, macro_split, bmr, tdee, calorie_goal, protein_g, fat_g, carb_g, is_current, created_at FROM user_macro_plans WHERE user_id = $1 AND is_current
`

func (q *Queries) CurrentMacroPlan(ctx context.Context, userID uuid.UUID) (UserMacroPlan, error) {
	row := q.db.QueryRow(ctx, currentMacroPlan, userID)
	var i UserMacroPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.HeightCm,
		&i.Age,
		&i.Sex,
		&i.ActivityLevel,
		&i.Goal,
		&i.MacroSplit,
		&i.Bmr,
		&i.Tdee,
		&i.CalorieGoal,
		&i.ProteinG,
		&i.FatG,
		&i.CarbG,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const insertMacroPlan = `-- name: InsertMacroPlan :one
INSERT INTO user_macro_plans (
    user_id, weight_kg, height_cm, age, sex,
    activity_level, goal, macro_split,
    bmr, tdee, calorie_goal, protein_g, fat_g, carb_g,
    is_current
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, true)
RETURNING id, user_id, weight_kg, height_cm, age, sex, activity_level, goal, macro_split, bmr, tdee, calorie_goal, protein_g, fat_g, carb_g, is_current, created_at
`

type InsertMacroPlanParams struct {
	UserID        uuid.UUID
	WeightKg      float64
	HeightCm      float64
	Age           int16
	Sex           string
	ActivityLevel string
	Goal          string
	MacroSplit    string
	Bmr           float64
	Tdee          float64
	CalorieGoal   float64
	ProteinG      float64
	FatG          float64
	CarbG         float64
}

func (q *Queries) InsertMacroPlan(ctx context.Context, arg InsertMacroPlanParams) (UserMacroPlan, error) {
	row := q.db.QueryRow(ctx, insertMacroPlan,
		arg.UserID,
		arg.WeightKg,
		arg.HeightCm,
		arg.Age,
		arg.Sex,
		arg.ActivityLevel,
		arg.Goal,
		arg.MacroSplit,
		arg.Bmr,
		arg.Tdee,
		arg.CalorieGoal,
		arg.ProteinG,
		arg.FatG,
		arg.CarbG,
	)
	var i UserMacroPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.HeightCm,
		&i.Age,
		&i.Sex,
		&i.ActivityLevel,
		&i.Goal,
		&i.MacroSplit,
		&i.Bmr,
		&i.Tdee,
		&i.CalorieGoal,
		&i.ProteinG,
		&i.FatG,
		&i.CarbG,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const listMacroPlans = `-- name: ListMacroPlans :many
SELECT id, user_id, weight_kg, height_cm, age, sex, activity_level, goal, macro_split, bmr, tdee, calorie_goal, protein_g, fat_g, carb_g, is_current, created_at FROM user_macro_plans
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListMacroPlansParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListMacroPlans(ctx context.Context, arg ListMacroPlansParams) ([]UserMacroPlan, error) {
	rows, err := q.db.Query(ctx, listMacroPlans, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserMacroPlan{}
	for rows.Next() {
		var i UserMacroPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeightKg,
			&i.HeightCm,
			&i.Age,
			&i.Sex,
			&i.ActivityLevel,
			&i.Goal,
			&i.MacroSplit,
			&i.Bmr,
			&i.Tdee,
			&i.CalorieGoal,
			&i.ProteinG,
			&i.FatG,
			&i.CarbG,
			&i.IsCurrent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetCurrentMacroPlans = `-- name: UnsetCurrentMacroPlans :exec
UPDATE user_macro_plans SET is_current = false WHERE user_id = $1 AND is_current
`

func (q *Queries) UnsetCurrentMacroPlans(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsetCurrentMacroPlans, userID)
	return err
}
