// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package medicationsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMedication = `-- name: CreateMedication :one
INSERT INTO medications (user_id, name, dose, times_of_day, days_of_week, remind, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, dose, times_of_day, days_of_week, remind, notes, stopped_at, created_at, updated_at
`

type CreateMedicationParams struct {
	UserID     uuid.UUID
	Name       string
	Dose       string
	TimesOfDay []string
	DaysOfWeek []int16
	Remind     bool
	Notes      string
}

func (q *Queries) CreateMedication(ctx context.Context, arg CreateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, createMedication,
		arg.UserID,
		arg.Name,
		arg.Dose,
		arg.TimesOfDay,
		arg.DaysOfWeek,
		arg.Remind,
		arg.Notes,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Dose,
		&i.TimesOfDay,
		&i.DaysOfWeek,
		&i.Remind,
		&i.Notes,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMedicationLog = `-- name: DeleteMedicationLog :execrows
DELETE FROM medication_logs WHERE id = $1 AND user_id = $2
`

type DeleteMedicationLogParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMedicationLog(ctx context.Context, arg DeleteMedicationLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMedicationLog, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMedication = `-- name: GetMedication :one
SELECT id, user_id, name, dose, times_of_day, days_of_week, remind, notes, stopped_at, created_at, updated_at FROM medications WHERE id = $1 AND user_id = $2
`

type GetMedicationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMedication(ctx context.Context, arg GetMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, getMedication, arg.ID, arg.UserID)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Dose,
		&i.TimesOfDay,
		&i.DaysOfWeek,
		&i.Remind,
		&i.Notes,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMedications = `-- name: ListActiveMedications :many
SELECT id, user_id, name, dose, times_of_day, days_of_week, remind, notes, stopped_at, created_at, updated_at FROM medications
WHERE user_id = $1 AND stopped_at IS NULL
ORDER BY lower(name)
`

func (q *Queries) ListActiveMedications(ctx context.Context, userID uuid.UUID) ([]Medication, error) {
	rows, err := q.db.Query(ctx, listActiveMedications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medication{}
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Dose,
			&i.TimesOfDay,
			&i.DaysOfWeek,
			&i.Remind,
			&i.Notes,
			&i.StoppedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMedicationLogs = `-- name: ListAllMedicationLogs :many
SELECT l.id, l.user_id, l.medication_id, l.log_date, l.slot, l.status, l.logged_at, m.name AS medication_name, m.dose AS medication_dose
FROM medication_logs l
JOIN medications m ON m.id = l.medication_id
WHERE l.user_id = $1
ORDER BY l.log_date DESC, l.logged_at DESC
`

type ListAllMedicationLogsRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	MedicationID   uuid.UUID
	LogDate        pgtype.Date
	Slot           *string
	Status         string
	LoggedAt       time.Time
	MedicationName string
	MedicationDose string
}

func (q *Queries) ListAllMedicationLogs(ctx context.Context, userID uuid.UUID) ([]ListAllMedicationLogsRow, error) {
	rows, err := q.db.Query(ctx, listAllMedicationLogs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllMedicationLogsRow{}
	for rows.Next() {
		var i ListAllMedicationLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MedicationID,
			&i.LogDate,
			&i.Slot,
			&i.Status,
			&i.LoggedAt,
			&i.MedicationName,
			&i.MedicationDose,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMedications = `-- name: ListAllMedications :many
SELECT id, user_id, name, dose, times_of_day, days_of_week, remind, notes, stopped_at, created_at, updated_at FROM medications
WHERE user_id = $1
ORDER BY stopped_at IS NOT NULL, lower(name), created_at
`

func (q *Queries) ListAllMedications(ctx context.Context, userID uuid.UUID) ([]Medication, error) {
	rows, err := q.db.Query(ctx, listAllMedications, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medication{}
	for rows.Next() {
		var i Medication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Dose,
			&i.TimesOfDay,
			&i.DaysOfWeek,
			&i.Remind,
			&i.Notes,
			&i.StoppedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationLogsOn = `-- name: ListMedicationLogsOn :many
SELECT l.id, l.user_id, l.medication_id, l.log_date, l.slot, l.status, l.logged_at, m.name AS medication_name, m.dose AS medication_dose
FROM medication_logs l
JOIN medications m ON m.id = l.medication_id
WHERE l.user_id = $1 AND l.log_date = $2
ORDER BY l.logged_at DESC
`

type ListMedicationLogsOnParams struct {
	UserID  uuid.UUID
	LogDate pgtype.Date
}

type ListMedicationLogsOnRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	MedicationID   uuid.UUID
	LogDate        pgtype.Date
	Slot           *string
	Status         string
	LoggedAt       time.Time
	MedicationName string
	MedicationDose string
}

func (q *Queries) ListMedicationLogsOn(ctx context.Context, arg ListMedicationLogsOnParams) ([]ListMedicationLogsOnRow, error) {
	rows, err := q.db.Query(ctx, listMedicationLogsOn, arg.UserID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMedicationLogsOnRow{}
	for rows.Next() {
		var i ListMedicationLogsOnRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MedicationID,
			&i.LogDate,
			&i.Slot,
			&i.Status,
			&i.LoggedAt,
			&i.MedicationName,
			&i.MedicationDose,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stopMedication = `-- name: StopMedication :one
UPDATE medications
SET stopped_at = $3, updated_at = now()
WHERE id = $1 AND user_id = $2 AND stopped_at IS NULL
RETURNING id, user_id, name, dose, times_of_day, days_of_week, remind, notes, stopped_at, created_at, updated_at
`

type StopMedicationParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	StoppedAt *time.Time
}

func (q *Queries) StopMedication(ctx context.Context, arg StopMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, stopMedication, arg.ID, arg.UserID, arg.StoppedAt)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Dose,
		&i.TimesOfDay,
		&i.DaysOfWeek,
		&i.Remind,
		&i.Notes,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMedication = `-- name: UpdateMedication :one
UPDATE medications
SET name = $3, dose = $4, times_of_day = $5, days_of_week = $6, remind = $7, notes = $8, updated_at = now()
WHERE id = $1 AND user_id = $2 AND stopped_at IS NULL
RETURNING id, user_id, name, dose, times_of_day, days_of_week, remind, notes, stopped_at, created_at, updated_at
`

type UpdateMedicationParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Dose       string
	TimesOfDay []string
	DaysOfWeek []int16
	Remind     bool
	Notes      string
}

func (q *Queries) UpdateMedication(ctx context.Context, arg UpdateMedicationParams) (Medication, error) {
	row := q.db.QueryRow(ctx, updateMedication,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Dose,
		arg.TimesOfDay,
		arg.DaysOfWeek,
		arg.Remind,
		arg.Notes,
	)
	var i Medication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Dose,
		&i.TimesOfDay,
		&i.DaysOfWeek,
		&i.Remind,
		&i.Notes,
		&i.StoppedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMedicationLog = `-- name: UpsertMedicationLog :one
INSERT INTO medication_logs (user_id, medication_id, log_date, slot, status, logged_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (medication_id, log_date, slot)
DO UPDATE SET status = EXCLUDED.status, logged_at = EXCLUDED.logged_at
RETURNING id, user_id, medication_id, log_date, slot, status, logged_at
`

type UpsertMedicationLogParams struct {
	UserID       uuid.UUID
	MedicationID uuid.UUID
	LogDate      pgtype.Date
	Slot         *string
	Status       string
	LoggedAt     time.Time
}

// A scheduled slot answered twice keeps the second answer. A NULL slot never
// conflicts, so as-needed doses always insert.
func (q *Queries) UpsertMedicationLog(ctx context.Context, arg UpsertMedicationLogParams) (MedicationLog, error) {
	row := q.db.QueryRow(ctx, upsertMedicationLog,
		arg.UserID,
		arg.MedicationID,
		arg.LogDate,
		arg.Slot,
		arg.Status,
		arg.LoggedAt,
	)
	var i MedicationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MedicationID,
		&i.LogDate,
		&i.Slot,
		&i.Status,
		&i.LoggedAt,
	)
	return i, err
}
