// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package toolauditdb

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ActivitySession struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	ActivityCode       string
	Source             string
	Status             string
	WeightKgSnapshot   float64
	StartedAt          time.Time
	PausedAt           *time.Time
	TotalPausedSeconds int32
	EndedAt            *time.Time
	CaloriesBurned     *float64
	ExternalID         *string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type AgentConnection struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	ClientKind  string
	TokenHash   []byte
	TokenPrefix string
	CreatedAt   time.Time
	LastUsedAt  *time.Time
	RevokedAt   *time.Time
}

type AuthIdentity struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	Provider        string
	ProviderSubject string
	Email           *string
	CreatedAt       time.Time
}

type CheckIn struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	LocalDate     pgtype.Date
	Mood          int16
	Energy        int16
	Wins          string
	Challenges    string
	Notes         string
	RelatedGoalID *uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ChunkEmbedding struct {
	ChunkID   string
	UserID    uuid.UUID
	Provider  string
	Model     string
	Embedding *pgvector.Vector
	CreatedAt time.Time
}

type Conversation struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Title               *string
	CreatedAt           time.Time
	UpdatedAt           time.Time
	MemoriesExtractedAt *time.Time
	Kind                string
	Summary             string
}

type Decision struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Options   string
	Rationale string
	Outcome   string
	DecidedAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Diet struct {
	ID          uuid.UUID
	Code        string
	Name        string
	Description string
}

type Document struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Title              string
	SourceKind         string
	StorageKey         *string
	Body               *string
	Mime               string
	ByteSize           int64
	ContentSha256      string
	LineCount          int32
	Status             string
	ParseError         string
	IndexedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	ChunkerFingerprint string
	ExternalPath       *string
	ExternalMtime      *time.Time
}

type DocumentChunk struct {
	ChunkID       string
	DocumentID    uuid.UUID
	UserID        uuid.UUID
	Ordinal       int32
	HeadingPath   []byte
	StartLine     int32
	EndLine       int32
	Content       string
	ContentSha256 string
	CreatedAt     time.Time
}

type Exercise struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Category         string
	Equipment        string
	Difficulty       string
	Instructions     string
	VideoUrl         string
	PrimaryMuscles   []string
	SecondaryMuscles []string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type FoodLog struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	LogDate       pgtype.Date
	MealID        *uuid.UUID
	IngredientID  *uuid.UUID
	QuantityGrams *float64
	Label         string
	Calories      float64
	ProteinG      float64
	FatG          float64
	CarbsG        float64
	LoggedAt      time.Time
}

type FormAnalysis struct {
	ID        uuid.UUID
	MediaID   uuid.UUID
	UserID    uuid.UUID
	Status    string
	Analysis  []byte
	Error     string
	Model     string
	Provider  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Goal struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Title      string
	Motivation string
	Success    string
	Category   string
	Status     string
	TargetDate pgtype.Date
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ClosedAt   *time.Time
}

type GoalMilestone struct {
	ID          uuid.UUID
	GoalID      uuid.UUID
	UserID      uuid.UUID
	Title       string
	Status      string
	Position    int32
	TargetDate  pgtype.Date
	CompletedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GoalUpdate struct {
	ID        uuid.UUID
	GoalID    uuid.UUID
	UserID    uuid.UUID
	Note      string
	Progress  *int16
	CreatedAt time.Time
}

type Habit struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Domain     string
	DaysOfWeek []int16
	Active     bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type HabitCompletion struct {
	ID          uuid.UUID
	HabitID     uuid.UUID
	UserID      uuid.UUID
	LocalDate   pgtype.Date
	CompletedAt time.Time
}

type HealthMetric struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Source    string
	Metric    string
	Value     float64
	Unit      string
	StartedAt time.Time
	EndedAt   *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type HydrationLog struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	LogDate  pgtype.Date
	AmountMl int32
	LoggedAt time.Time
}

type IndexRun struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Kind               string
	StartedAt          time.Time
	CompletedAt        *time.Time
	DocumentsSeen      int32
	DocumentsAdded     int32
	DocumentsUpdated   int32
	DocumentsUnchanged int32
	DocumentsFailed    int32
	ChunksWritten      int32
	ChunksRemoved      int32
	Warnings           []byte
	Success            bool
	ErrorSummary       string
}

type Ingredient struct {
	ID                   uuid.UUID
	UserID               *uuid.UUID
	Name                 string
	Brand                string
	Category             string
	ServingSizeGrams     float64
	CaloriesPer100g      float64
	ProteinGPer100g      float64
	FatGPer100g          float64
	CarbsGPer100g        float64
	FiberGPer100g        float64
	SugarGPer100g        float64
	SodiumMgPer100g      float64
	PotassiumMgPer100g   float64
	CholesterolMgPer100g float64
	CreatedAt            time.Time
	UpdatedAt            time.Time
	SaturatedFatGPer100g float64
}

type Job struct {
	ID          uuid.UUID
	Kind        string
	Payload     []byte
	Status      string
	Attempts    int16
	MaxAttempts int16
	RunAfter    time.Time
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type JournalEntry struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Content   string
	Mood      *int16
	CreatedAt time.Time
}

type Meal struct {
	ID          uuid.UUID
	MealPlanID  uuid.UUID
	MealNumber  int16
	Name        string
	TotalMacros []byte
	CreatedAt   time.Time
}

type MealIngredient struct {
	ID            uuid.UUID
	MealID        uuid.UUID
	IngredientID  uuid.UUID
	QuantityGrams float64
	Calories      float64
	ProteinG      float64
	FatG          float64
	CarbsG        float64
	CreatedAt     time.Time
}

type MealPlan struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Name          string
	Description   string
	Objective     string
	ActivityLevel string
	Gender        string
	TotalMacros   []byte
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type MealReminder struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Label              string
	TimeOfDay          string
	DaysOfWeek         []int16
	Enabled            bool
	LastFiredLocalDate pgtype.Date
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type Medium struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Kind         string
	MimeType     string
	SizeBytes    int64
	StorageKey   string
	OriginalName string
	CreatedAt    time.Time
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        string
	Parts          []byte
	Usage          []byte
	Model          *string
	Provider       *string
	CreatedAt      time.Time
	EvidenceRefs   []string
	ToolCalls      []byte
	ToolResults    []byte
}

type MessagingLink struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Platform     string
	ExternalID   string
	LastUpdateID int64
	CreatedAt    time.Time
	LastSeenAt   *time.Time
}

type MessagingLinkCode struct {
	CodeHash   []byte
	UserID     uuid.UUID
	Platform   string
	ExpiresAt  time.Time
	RedeemedAt *time.Time
	CreatedAt  time.Time
}

type PasswordResetToken struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
	UsedAt    *time.Time
}

type QuotaCounter struct {
	UserID      uuid.UUID
	Action      string
	WindowStart time.Time
	Used        int32
}

type Report struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Kind        string
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Title       string
	Body        string
	Status      string
	LastError   string
	GeneratedAt *time.Time
	ArchivedAt  *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	CreatedAt  time.Time
	LastSeenAt time.Time
	UserAgent  *string
	Ip         *netip.Addr
}

type SleepLog struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	LocalDate       pgtype.Date
	DurationMinutes int32
	Quality         *int16
	Bedtime         *string
	WakeTime        *string
	Notes           string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type StravaActivity struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	StravaID            int64
	Name                string
	SportType           string
	StartDate           time.Time
	DistanceM           float64
	MovingTimeS         int32
	ElapsedTimeS        int32
	TotalElevationGainM float64
	AverageSpeedMs      float64
	SummaryPolyline     string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type StravaConnection struct {
	UserID             uuid.UUID
	AthleteID          int64
	AccessToken        string
	RefreshToken       string
	ExpiresAt          time.Time
	Scopes             string
	LastSyncedAt       *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AccessTokenSealed  []byte
	RefreshTokenSealed []byte
}

type ToolExecution struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Tool      string
	Arguments []byte
	Surface   string
	Outcome   string
	Detail    *string
	CreatedAt time.Time
}

type User struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  *string
	DisplayName   string
	Timezone      string
	CoachingStyle *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Tier          string
	OnboardedAt   *time.Time
	CoachingTone  string
}

type UserAiCredential struct {
	UserID      uuid.UUID
	Provider    string
	ApiKey      []byte
	KeyHint     string
	Model       string
	LastError   string
	LastErrorAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BaseUrl     string
}

type UserBiometric struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WeightKg    float64
	HeightCm    float64
	DateOfBirth pgtype.Date
	Sex         string
	IsCurrent   bool
	CreatedAt   time.Time
}

type UserDietPreference struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	DietID    uuid.UUID
	CreatedAt time.Time
}

type UserMacroPlan struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	WeightKg      float64
	HeightCm      float64
	Age           int16
	Sex           string
	ActivityLevel string
	Goal          string
	MacroSplit    string
	Bmr           float64
	Tdee          float64
	CalorieGoal   float64
	ProteinG      float64
	FatG          float64
	CarbG         float64
	IsCurrent     bool
	CreatedAt     time.Time
}

type UserMemory struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	Category             string
	Content              string
	Status               string
	Pinned               bool
	Source               string
	SourceConversationID *uuid.UUID
	Confidence           *float32
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            *time.Time
	Excluded             bool
}

type UserNotificationPref struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	NudgeMissedCheckin bool
	NudgeGoalDeadline  bool
	WeeklyReportAuto   bool
	QuietHoursEnabled  bool
	QuietStart         string
	QuietEnd           string
	UpdatedAt          time.Time
}

type UserNudge struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Kind        string
	DedupeKey   string
	Title       string
	Body        string
	Href        string
	ReadAt      *time.Time
	DismissedAt *time.Time
	CreatedAt   time.Time
}

type UserPreference struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	UnitsSystem       string
	DefaultGoal       string
	DefaultMacroSplit string
	UpdatedAt         time.Time
}

type VaultConnection struct {
	UserID     uuid.UUID
	RootPath   string
	LastSyncAt *time.Time
	LastError  string
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type WebauthnChallenge struct {
	ID        uuid.UUID
	Data      []byte
	ExpiresAt time.Time
	CreatedAt time.Time
}

type WebauthnCredential struct {
	CredentialID    []byte
	UserID          uuid.UUID
	PublicKey       []byte
	AttestationType string
	Transport       []string
	SignCount       int64
	Name            string
	Aaguid          []byte
	BackupEligible  bool
	BackupState     bool
	CreatedAt       time.Time
	LastUsedAt      *time.Time
}

type WorkoutIntake struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Goal           string
	Experience     string
	DaysPerWeek    int16
	SessionMinutes int16
	Equipment      []string
	Limitations    string
	CreatedAt      time.Time
}

type WorkoutPlan struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	IntakeID  uuid.UUID
	Name      string
	Plan      []byte
	Model     string
	Provider  string
	CreatedAt time.Time
}
