// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package toolauditdb

import (
	"context"

	"github.com/google/uuid"
)

const listToolExecutions = `-- name: ListToolExecutions :many
SELECT id, user_id, tool, arguments, surface, outcome, detail, created_at FROM tool_executions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListToolExecutionsParams struct {
	UserID   uuid.UUID
	RowLimit int32
}

// One person's executions, newest first. The only read this table has.
func (q *Queries) ListToolExecutions(ctx context.Context, arg ListToolExecutionsParams) ([]ToolExecution, error) {
	rows, err := q.db.Query(ctx, listToolExecutions, arg.UserID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolExecution{}
	for rows.Next() {
		var i ToolExecution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Tool,
			&i.Arguments,
			&i.Surface,
			&i.Outcome,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordToolExecution = `-- name: RecordToolExecution :one
INSERT INTO tool_executions (user_id, tool, arguments, surface, outcome, detail)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, tool, arguments, surface, outcome, detail, created_at
`

type RecordToolExecutionParams struct {
	UserID    uuid.UUID
	Tool      string
	Arguments []byte
	Surface   string
	Outcome   string
	Detail    *string
}

func (q *Queries) RecordToolExecution(ctx context.Context, arg RecordToolExecutionParams) (ToolExecution, error) {
	row := q.db.QueryRow(ctx, recordToolExecution,
		arg.UserID,
		arg.Tool,
		arg.Arguments,
		arg.Surface,
		arg.Outcome,
		arg.Detail,
	)
	var i ToolExecution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Tool,
		&i.Arguments,
		&i.Surface,
		&i.Outcome,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}
