// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package screentimedb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ScreenTimeLog struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	LocalDate pgtype.Date
	Minutes   int32
	Source    string
	UpdatedAt time.Time
}
