// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package screentimedb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listScreenTimeBetween = `-- name: ListScreenTimeBetween :many
SELECT id, user_id, local_date, minutes, source, updated_at FROM screen_time_logs
WHERE user_id = $1 AND local_date >= $2 AND local_date < $3
ORDER BY local_date DESC
`

type ListScreenTimeBetweenParams struct {
	UserID      uuid.UUID
	LocalDate   pgtype.Date
	LocalDate_2 pgtype.Date
}

func (q *Queries) ListScreenTimeBetween(ctx context.Context, arg ListScreenTimeBetweenParams) ([]ScreenTimeLog, error) {
	rows, err := q.db.Query(ctx, listScreenTimeBetween, arg.UserID, arg.LocalDate, arg.LocalDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScreenTimeLog{}
	for rows.Next() {
		var i ScreenTimeLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocalDate,
			&i.Minutes,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const screenTimeForDate = `-- name: ScreenTimeForDate :one
SELECT id, user_id, local_date, minutes, source, updated_at FROM screen_time_logs WHERE user_id = $1 AND local_date = $2
`

type ScreenTimeForDateParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
}

func (q *Queries) ScreenTimeForDate(ctx context.Context, arg ScreenTimeForDateParams) (ScreenTimeLog, error) {
	row := q.db.QueryRow(ctx, screenTimeForDate, arg.UserID, arg.LocalDate)
	var i ScreenTimeLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocalDate,
		&i.Minutes,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScreenTime = `-- name: UpsertScreenTime :one
INSERT INTO screen_time_logs (user_id, local_date, minutes, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, local_date) DO UPDATE
SET minutes = EXCLUDED.minutes, source = EXCLUDED.source, updated_at = now()
RETURNING id, user_id, local_date, minutes, source, updated_at
`

type UpsertScreenTimeParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
	Minutes   int32
	Source    string
}

func (q *Queries) UpsertScreenTime(ctx context.Context, arg UpsertScreenTimeParams) (ScreenTimeLog, error) {
	row := q.db.QueryRow(ctx, upsertScreenTime,
		arg.UserID,
		arg.LocalDate,
		arg.Minutes,
		arg.Source,
	)
	var i ScreenTimeLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocalDate,
		&i.Minutes,
		&i.Source,
		&i.UpdatedAt,
	)
	return i, err
}
