// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package crewsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :execrows
INSERT INTO crew_members (crew_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddMemberParams struct {
	CrewID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, addMember, arg.CrewID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearChallenge = `-- name: ClearChallenge :exec
DELETE FROM crew_challenges WHERE crew_id = $1
`

func (q *Queries) ClearChallenge(ctx context.Context, crewID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearChallenge, crewID)
	return err
}

const countMembers = `-- name: CountMembers :one
SELECT count(*) FROM crew_members WHERE crew_id = $1
`

func (q *Queries) CountMembers(ctx context.Context, crewID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMembers, crewID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCrew = `-- name: CreateCrew :one
INSERT INTO crews (name, owner_id, code) VALUES ($1, $2, $3) RETURNING id, name, owner_id, code, created_at
`

type CreateCrewParams struct {
	Name    string
	OwnerID uuid.UUID
	Code    string
}

func (q *Queries) CreateCrew(ctx context.Context, arg CreateCrewParams) (Crew, error) {
	row := q.db.QueryRow(ctx, createCrew, arg.Name, arg.OwnerID, arg.Code)
	var i Crew
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const crewByCode = `-- name: CrewByCode :one
SELECT id, name, owner_id, code, created_at FROM crews WHERE code = $1
`

func (q *Queries) CrewByCode(ctx context.Context, code string) (Crew, error) {
	row := q.db.QueryRow(ctx, crewByCode, code)
	var i Crew
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const crewmatesOf = `-- name: CrewmatesOf :many
SELECT DISTINCT u.id, u.display_name, u.timezone
FROM crew_members mine
JOIN crew_members other ON other.crew_id = mine.crew_id AND other.user_id <> mine.user_id
JOIN users u ON u.id = other.user_id
WHERE mine.user_id = $1
`

type CrewmatesOfRow struct {
	ID          uuid.UUID
	DisplayName string
	Timezone    string
}

// Everybody who shares at least one crew with the user, once each.
func (q *Queries) CrewmatesOf(ctx context.Context, userID uuid.UUID) ([]CrewmatesOfRow, error) {
	rows, err := q.db.Query(ctx, crewmatesOf, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrewmatesOfRow{}
	for rows.Next() {
		var i CrewmatesOfRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCrew = `-- name: DeleteCrew :exec
DELETE FROM crews WHERE id = $1
`

func (q *Queries) DeleteCrew(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCrew, id)
	return err
}

const getChallenge = `-- name: GetChallenge :one
SELECT crew_id, kind, target, created_at FROM crew_challenges WHERE crew_id = $1
`

func (q *Queries) GetChallenge(ctx context.Context, crewID uuid.UUID) (CrewChallenge, error) {
	row := q.db.QueryRow(ctx, getChallenge, crewID)
	var i CrewChallenge
	err := row.Scan(
		&i.CrewID,
		&i.Kind,
		&i.Target,
		&i.CreatedAt,
	)
	return i, err
}

const getCrew = `-- name: GetCrew :one
SELECT id, name, owner_id, code, created_at FROM crews WHERE id = $1
`

func (q *Queries) GetCrew(ctx context.Context, id uuid.UUID) (Crew, error) {
	row := q.db.QueryRow(ctx, getCrew, id)
	var i Crew
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (SELECT 1 FROM crew_members WHERE crew_id = $1 AND user_id = $2)
`

type IsMemberParams struct {
	CrewID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.CrewID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMine = `-- name: ListMine :many
SELECT c.id, c.name, c.owner_id, c.code, c.created_at, (SELECT count(*) FROM crew_members m2 WHERE m2.crew_id = c.id) AS members
FROM crews c JOIN crew_members m ON m.crew_id = c.id
WHERE m.user_id = $1
ORDER BY c.created_at
`

type ListMineRow struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	Code      string
	CreatedAt time.Time
	Members   int64
}

func (q *Queries) ListMine(ctx context.Context, userID uuid.UUID) ([]ListMineRow, error) {
	rows, err := q.db.Query(ctx, listMine, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMineRow{}
	for rows.Next() {
		var i ListMineRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.Code,
			&i.CreatedAt,
			&i.Members,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const members = `-- name: Members :many
SELECT u.id, u.display_name, u.handle, u.timezone, u.tier, m.joined_at
FROM crew_members m JOIN users u ON u.id = m.user_id
WHERE m.crew_id = $1
ORDER BY m.joined_at
`

type MembersRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
	Timezone    string
	Tier        string
	JoinedAt    time.Time
}

func (q *Queries) Members(ctx context.Context, crewID uuid.UUID) ([]MembersRow, error) {
	rows, err := q.db.Query(ctx, members, crewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MembersRow{}
	for rows.Next() {
		var i MembersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Handle,
			&i.Timezone,
			&i.Tier,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestOtherMember = `-- name: OldestOtherMember :one
SELECT user_id FROM crew_members
WHERE crew_id = $1 AND user_id <> $2
ORDER BY joined_at LIMIT 1
`

type OldestOtherMemberParams struct {
	CrewID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) OldestOtherMember(ctx context.Context, arg OldestOtherMemberParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, oldestOtherMember, arg.CrewID, arg.UserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM crew_members WHERE crew_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	CrewID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.CrewID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rename = `-- name: Rename :exec
UPDATE crews SET name = $2 WHERE id = $1
`

type RenameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) Rename(ctx context.Context, arg RenameParams) error {
	_, err := q.db.Exec(ctx, rename, arg.ID, arg.Name)
	return err
}

const setChallenge = `-- name: SetChallenge :exec
INSERT INTO crew_challenges (crew_id, kind, target) VALUES ($1, $2, $3)
ON CONFLICT (crew_id) DO UPDATE SET kind = EXCLUDED.kind, target = EXCLUDED.target, created_at = now()
`

type SetChallengeParams struct {
	CrewID uuid.UUID
	Kind   string
	Target int16
}

func (q *Queries) SetChallenge(ctx context.Context, arg SetChallengeParams) error {
	_, err := q.db.Exec(ctx, setChallenge, arg.CrewID, arg.Kind, arg.Target)
	return err
}

const setOwner = `-- name: SetOwner :exec
UPDATE crews SET owner_id = $2 WHERE id = $1
`

type SetOwnerParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) SetOwner(ctx context.Context, arg SetOwnerParams) error {
	_, err := q.db.Exec(ctx, setOwner, arg.ID, arg.OwnerID)
	return err
}
