// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package liftsdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SetLog struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	ActivitySessionID *uuid.UUID
	LogDate           pgtype.Date
	ExerciseSlug      string
	ExerciseName      string
	SetNumber         int32
	WeightKg          float64
	Reps              int32
	PerformedAt       time.Time
	Kind              string
	Rir               *int16
	ClientID          *uuid.UUID
}
