// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package liftsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSetLog = `-- name: CreateSetLog :one
INSERT INTO set_logs (user_id, activity_session_id, log_date, exercise_slug, exercise_name, set_number, weight_kg, reps, performed_at, kind, rir)
VALUES (
    $1,
    (SELECT a.id FROM activity_sessions a WHERE a.id = $2 AND a.user_id = $1),
    $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, user_id, activity_session_id, log_date, exercise_slug, exercise_name, set_number, weight_kg, reps, performed_at, kind, rir
`

type CreateSetLogParams struct {
	UserID            uuid.UUID
	ActivitySessionID *uuid.UUID
	LogDate           pgtype.Date
	ExerciseSlug      string
	ExerciseName      string
	SetNumber         int32
	WeightKg          float64
	Reps              int32
	PerformedAt       time.Time
	Kind              string
	Rir               *int16
}

// An activity session that is not the person's own is dropped rather than
// linked, so a set can never attach to somebody else's workout.
func (q *Queries) CreateSetLog(ctx context.Context, arg CreateSetLogParams) (SetLog, error) {
	row := q.db.QueryRow(ctx, createSetLog,
		arg.UserID,
		arg.ActivitySessionID,
		arg.LogDate,
		arg.ExerciseSlug,
		arg.ExerciseName,
		arg.SetNumber,
		arg.WeightKg,
		arg.Reps,
		arg.PerformedAt,
		arg.Kind,
		arg.Rir,
	)
	var i SetLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivitySessionID,
		&i.LogDate,
		&i.ExerciseSlug,
		&i.ExerciseName,
		&i.SetNumber,
		&i.WeightKg,
		&i.Reps,
		&i.PerformedAt,
		&i.Kind,
		&i.Rir,
	)
	return i, err
}

const deleteSetLog = `-- name: DeleteSetLog :execrows
DELETE FROM set_logs WHERE id = $1 AND user_id = $2
`

type DeleteSetLogParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSetLog(ctx context.Context, arg DeleteSetLogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSetLog, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSetsBetween = `-- name: ListSetsBetween :many
SELECT id, user_id, activity_session_id, log_date, exercise_slug, exercise_name, set_number, weight_kg, reps, performed_at, kind, rir FROM set_logs
WHERE user_id = $1 AND performed_at >= $2 AND performed_at < $3
ORDER BY performed_at DESC
`

type ListSetsBetweenParams struct {
	UserID        uuid.UUID
	PerformedAt   time.Time
	PerformedAt_2 time.Time
}

// Half-open [since, until) on when the set was done, newest first.
func (q *Queries) ListSetsBetween(ctx context.Context, arg ListSetsBetweenParams) ([]SetLog, error) {
	rows, err := q.db.Query(ctx, listSetsBetween, arg.UserID, arg.PerformedAt, arg.PerformedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetLog{}
	for rows.Next() {
		var i SetLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivitySessionID,
			&i.LogDate,
			&i.ExerciseSlug,
			&i.ExerciseName,
			&i.SetNumber,
			&i.WeightKg,
			&i.Reps,
			&i.PerformedAt,
			&i.Kind,
			&i.Rir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsForExercises = `-- name: ListSetsForExercises :many
SELECT id, user_id, activity_session_id, log_date, exercise_slug, exercise_name, set_number, weight_kg, reps, performed_at, kind, rir FROM set_logs
WHERE user_id = $1
  AND performed_at >= $2
  AND (CASE WHEN exercise_slug <> '' THEN exercise_slug ELSE lower(btrim(exercise_name)) END) = ANY($3::text[])
ORDER BY performed_at DESC
LIMIT 500
`

type ListSetsForExercisesParams struct {
	UserID uuid.UUID
	Since  time.Time
	Keys   []string
}

// Sets of the given exercises since a point, newest first. The key matches
// lift.KeyFor: the slug, or the trimmed lower-cased name when there is none.
func (q *Queries) ListSetsForExercises(ctx context.Context, arg ListSetsForExercisesParams) ([]SetLog, error) {
	rows, err := q.db.Query(ctx, listSetsForExercises, arg.UserID, arg.Since, arg.Keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetLog{}
	for rows.Next() {
		var i SetLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivitySessionID,
			&i.LogDate,
			&i.ExerciseSlug,
			&i.ExerciseName,
			&i.SetNumber,
			&i.WeightKg,
			&i.Reps,
			&i.PerformedAt,
			&i.Kind,
			&i.Rir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsForExercisesBefore = `-- name: ListSetsForExercisesBefore :many
SELECT id, user_id, activity_session_id, log_date, exercise_slug, exercise_name, set_number, weight_kg, reps, performed_at, kind, rir FROM set_logs
WHERE user_id = $1
  AND performed_at >= $2
  AND performed_at < $3
  AND (CASE WHEN exercise_slug <> '' THEN exercise_slug ELSE lower(btrim(exercise_name)) END) = ANY($4::text[])
ORDER BY performed_at DESC
LIMIT 500
`

type ListSetsForExercisesBeforeParams struct {
	UserID uuid.UUID
	Since  time.Time
	Before time.Time
	Keys   []string
}

// Sets of the given exercises in [since, before), newest first: the history
// a finished workout is compared against. Keys match lift.KeyFor.
func (q *Queries) ListSetsForExercisesBefore(ctx context.Context, arg ListSetsForExercisesBeforeParams) ([]SetLog, error) {
	rows, err := q.db.Query(ctx, listSetsForExercisesBefore,
		arg.UserID,
		arg.Since,
		arg.Before,
		arg.Keys,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetLog{}
	for rows.Next() {
		var i SetLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivitySessionID,
			&i.LogDate,
			&i.ExerciseSlug,
			&i.ExerciseName,
			&i.SetNumber,
			&i.WeightKg,
			&i.Reps,
			&i.PerformedAt,
			&i.Kind,
			&i.Rir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSetsForSession = `-- name: ListSetsForSession :many
SELECT id, user_id, activity_session_id, log_date, exercise_slug, exercise_name, set_number, weight_kg, reps, performed_at, kind, rir FROM set_logs
WHERE user_id = $1 AND activity_session_id = $2
ORDER BY performed_at, set_number
`

type ListSetsForSessionParams struct {
	UserID            uuid.UUID
	ActivitySessionID *uuid.UUID
}

// The sets logged during one timed workout, in the order they were done.
func (q *Queries) ListSetsForSession(ctx context.Context, arg ListSetsForSessionParams) ([]SetLog, error) {
	rows, err := q.db.Query(ctx, listSetsForSession, arg.UserID, arg.ActivitySessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SetLog{}
	for rows.Next() {
		var i SetLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivitySessionID,
			&i.LogDate,
			&i.ExerciseSlug,
			&i.ExerciseName,
			&i.SetNumber,
			&i.WeightKg,
			&i.Reps,
			&i.PerformedAt,
			&i.Kind,
			&i.Rir,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
