package documents_test

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/NorthAIProject/north-client/internal/documents"
	"github.com/NorthAIProject/north-client/internal/documents/parse"
)

// readPDF loads a fixture, skipping the test when it is absent rather than
// failing: the fixtures are generated by TestMain-free helper scripts on some
// machines, and a missing one should not look like a broken parser.
func readPDF(t *testing.T, name string) []byte {
	t.Helper()
	body, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Skipf("fixture %s is not present: %v", name, err)
	}
	return body
}

func TestPDFExtractsTextWithPageHeadings(t *testing.T) {
	doc, err := parse.PDF("physio-report.pdf", readPDF(t, "physio-report.pdf"))
	if err != nil {
		t.Fatal(err)
	}

	if doc.Kind != parse.KindPDF {
		t.Errorf("kind = %q", doc.Kind)
	}
	if len(doc.Headings) == 0 {
		t.Fatal("no page headings were produced")
	}
	if doc.Headings[0].Text != "Page 1" {
		t.Errorf("first heading = %q, want %q", doc.Headings[0].Text, "Page 1")
	}

	text := strings.Join(doc.Lines, "\n")
	if !strings.Contains(text, "shoulder") {
		t.Errorf("the extracted text is missing the document's content:\n%s", text)
	}
}

// The invariant every citation depends on has to hold for PDFs too, even though
// the lines are North's extraction rather than the file's own.
func TestPDFChunksQuoteTheirOwnLineRange(t *testing.T) {
	doc, err := parse.PDF("physio-report.pdf", readPDF(t, "physio-report.pdf"))
	if err != nil {
		t.Fatal(err)
	}

	chunks := documents.ChunkDocument(doc, documents.Options{})
	if len(chunks) == 0 {
		t.Fatal("the PDF produced no chunks")
	}

	for _, c := range chunks {
		if c.StartLine < 1 || c.EndLine > len(doc.Lines) {
			t.Fatalf("chunk %d range %d-%d is outside the document", c.Ordinal, c.StartLine, c.EndLine)
		}
		want := strings.Join(doc.Lines[c.StartLine-1:c.EndLine], "\n")
		if c.Content != want {
			t.Errorf("chunk %d does not quote its own lines:\n got: %q\nwant: %q", c.Ordinal, c.Content, want)
		}
	}

	// The heading trail is what makes a PDF citation usable: "Page 2" is
	// something a person can act on, a line number into North's extraction is
	// not.
	var withPage int
	for _, c := range chunks {
		for _, h := range c.HeadingPath {
			if strings.HasPrefix(h, "Page ") {
				withPage++
			}
		}
	}
	if withPage == 0 {
		t.Error("no chunk carries a page in its heading path")
	}
}

// A scan is a photograph of a page. Telling the person that specifically beats
// "this document produced nothing to search", which sounds like North is broken.
func TestPDFWithNoTextLayerSaysSo(t *testing.T) {
	_, err := parse.PDF("scan.pdf", readPDF(t, "scan-no-text.pdf"))
	if !errors.Is(err, parse.ErrNoText) {
		t.Errorf("error = %v, want ErrNoText", err)
	}
}

func TestGarbageIsRejectedRatherThanIndexed(t *testing.T) {
	_, err := parse.PDF("broken.pdf", []byte("this is not a pdf at all"))
	if err == nil {
		t.Fatal("a non-PDF was accepted")
	}
	if !strings.Contains(err.Error(), "could not open") {
		t.Errorf("error = %v; the message should be one a person can read", err)
	}
}

// Parse must route by extension and MIME, not guess from content.
func TestParseRoutesPDFsToThePDFReader(t *testing.T) {
	_, err := parse.Parse("notes.pdf", "application/pdf", "not really a pdf")
	if err == nil {
		t.Error("a .pdf was parsed as text")
	}
}
