// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pushdb

import (
	"time"

	"github.com/google/uuid"
)

type PushSubscription struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Endpoint   string
	P256dh     string
	Auth       string
	UserAgent  string
	CreatedAt  time.Time
	LastUsedAt *time.Time
	FailedAt   *time.Time
}
