// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pushdb

import (
	"context"

	"github.com/google/uuid"
)

const countPushSubscriptions = `-- name: CountPushSubscriptions :one
SELECT count(*)::int FROM push_subscriptions
WHERE user_id = $1
`

func (q *Queries) CountPushSubscriptions(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPushSubscriptions, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :exec
DELETE FROM push_subscriptions
WHERE id = $1
`

func (q *Queries) DeletePushSubscription(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePushSubscription, id)
	return err
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :execrows
DELETE FROM push_subscriptions
WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionByEndpointParams struct {
	UserID   uuid.UUID
	Endpoint string
}

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, arg DeletePushSubscriptionByEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, arg.UserID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, user_id, endpoint, p256dh, auth, user_agent, created_at, last_used_at, failed_at FROM push_subscriptions
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListPushSubscriptions(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushSubscription{}
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPushSubscriptionFailed = `-- name: MarkPushSubscriptionFailed :exec
UPDATE push_subscriptions
SET failed_at = now()
WHERE id = $1
`

func (q *Queries) MarkPushSubscriptionFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPushSubscriptionFailed, id)
	return err
}

const markPushSubscriptionUsed = `-- name: MarkPushSubscriptionUsed :exec
UPDATE push_subscriptions
SET last_used_at = now(),
    failed_at    = NULL
WHERE id = $1
`

func (q *Queries) MarkPushSubscriptionUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPushSubscriptionUsed, id)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE
SET user_id    = EXCLUDED.user_id,
    p256dh     = EXCLUDED.p256dh,
    auth       = EXCLUDED.auth,
    user_agent = EXCLUDED.user_agent,
    failed_at  = NULL
RETURNING id, user_id, endpoint, p256dh, auth, user_agent, created_at, last_used_at, failed_at
`

type UpsertPushSubscriptionParams struct {
	UserID    uuid.UUID
	Endpoint  string
	P256dh    string
	Auth      string
	UserAgent string
}

// A re-subscribe from the same browser replaces the keys and clears any
// earlier failure. A browser that signed in as somebody else moves with them.
func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.FailedAt,
	)
	return i, err
}
