// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package inboxdb

import (
	"time"

	"github.com/google/uuid"
)

type InboxItem struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Source     string
	Text       string
	Suggestion []byte
	Status     string
	FiledAs    *string
	FiledRef   *uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
