// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package newsdb

import (
	"time"

	"github.com/google/uuid"
)

type NewsTickerItem struct {
	ID          uuid.UUID
	ItemKey     string
	Title       string
	Url         string
	Source      string
	FeedUrl     string
	PublishedAt time.Time
	FetchedAt   time.Time
}

type UserNewsFeed struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FeedUrl   string
	Title     string
	CreatedAt time.Time
}
