// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package newsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUserNewsFeeds = `-- name: CountUserNewsFeeds :one
SELECT count(*) FROM user_news_feeds WHERE user_id = $1
`

func (q *Queries) CountUserNewsFeeds(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserNewsFeeds, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserNewsFeed = `-- name: CreateUserNewsFeed :one
INSERT INTO user_news_feeds (user_id, feed_url, title) VALUES ($1, $2, $3) RETURNING id, user_id, feed_url, title, created_at
`

type CreateUserNewsFeedParams struct {
	UserID  uuid.UUID
	FeedUrl string
	Title   string
}

func (q *Queries) CreateUserNewsFeed(ctx context.Context, arg CreateUserNewsFeedParams) (UserNewsFeed, error) {
	row := q.db.QueryRow(ctx, createUserNewsFeed, arg.UserID, arg.FeedUrl, arg.Title)
	var i UserNewsFeed
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedUrl,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}

const deleteUserNewsFeed = `-- name: DeleteUserNewsFeed :execrows
DELETE FROM user_news_feeds WHERE id = $1 AND user_id = $2
`

type DeleteUserNewsFeedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUserNewsFeed(ctx context.Context, arg DeleteUserNewsFeedParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserNewsFeed, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDistinctUserNewsFeedURLs = `-- name: ListDistinctUserNewsFeedURLs :many
SELECT DISTINCT feed_url FROM user_news_feeds ORDER BY feed_url
`

func (q *Queries) ListDistinctUserNewsFeedURLs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listDistinctUserNewsFeedURLs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var feed_url string
		if err := rows.Scan(&feed_url); err != nil {
			return nil, err
		}
		items = append(items, feed_url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsTickerItems = `-- name: ListNewsTickerItems :many
SELECT id, item_key, title, url, source, feed_url, published_at, fetched_at FROM news_ticker_items
ORDER BY published_at DESC, id DESC
LIMIT $1
`

func (q *Queries) ListNewsTickerItems(ctx context.Context, limit int32) ([]NewsTickerItem, error) {
	rows, err := q.db.Query(ctx, listNewsTickerItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NewsTickerItem{}
	for rows.Next() {
		var i NewsTickerItem
		if err := rows.Scan(
			&i.ID,
			&i.ItemKey,
			&i.Title,
			&i.Url,
			&i.Source,
			&i.FeedUrl,
			&i.PublishedAt,
			&i.FetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserNewsFeeds = `-- name: ListUserNewsFeeds :many
SELECT id, user_id, feed_url, title, created_at FROM user_news_feeds WHERE user_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListUserNewsFeeds(ctx context.Context, userID uuid.UUID) ([]UserNewsFeed, error) {
	rows, err := q.db.Query(ctx, listUserNewsFeeds, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserNewsFeed{}
	for rows.Next() {
		var i UserNewsFeed
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FeedUrl,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneNewsTickerItemsBeyond = `-- name: PruneNewsTickerItemsBeyond :exec
DELETE FROM news_ticker_items
WHERE id NOT IN (SELECT id FROM news_ticker_items ORDER BY published_at DESC, id DESC LIMIT $1)
`

func (q *Queries) PruneNewsTickerItemsBeyond(ctx context.Context, limit int32) error {
	_, err := q.db.Exec(ctx, pruneNewsTickerItemsBeyond, limit)
	return err
}

const pruneNewsTickerItemsOlderThan = `-- name: PruneNewsTickerItemsOlderThan :exec
DELETE FROM news_ticker_items WHERE published_at < $1
`

func (q *Queries) PruneNewsTickerItemsOlderThan(ctx context.Context, publishedAt time.Time) error {
	_, err := q.db.Exec(ctx, pruneNewsTickerItemsOlderThan, publishedAt)
	return err
}

const upsertNewsTickerItem = `-- name: UpsertNewsTickerItem :exec
INSERT INTO news_ticker_items (item_key, title, url, source, feed_url, published_at, fetched_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (item_key) DO UPDATE
SET title = EXCLUDED.title, url = EXCLUDED.url, source = EXCLUDED.source,
    feed_url = EXCLUDED.feed_url, published_at = EXCLUDED.published_at, fetched_at = now()
`

type UpsertNewsTickerItemParams struct {
	ItemKey     string
	Title       string
	Url         string
	Source      string
	FeedUrl     string
	PublishedAt time.Time
}

func (q *Queries) UpsertNewsTickerItem(ctx context.Context, arg UpsertNewsTickerItemParams) error {
	_, err := q.db.Exec(ctx, upsertNewsTickerItem,
		arg.ItemKey,
		arg.Title,
		arg.Url,
		arg.Source,
		arg.FeedUrl,
		arg.PublishedAt,
	)
	return err
}
