// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package biometricsdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserBiometric struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WeightKg    float64
	HeightCm    float64
	DateOfBirth pgtype.Date
	Sex         string
	IsCurrent   bool
	CreatedAt   time.Time
}
