// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package biometricsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const currentBiometric = `-- name: CurrentBiometric :one
SELECT id, user_id, weight_kg, height_cm, date_of_birth, sex, is_current, created_at FROM user_biometrics WHERE user_id = $1 AND is_current
`

func (q *Queries) CurrentBiometric(ctx context.Context, userID uuid.UUID) (UserBiometric, error) {
	row := q.db.QueryRow(ctx, currentBiometric, userID)
	var i UserBiometric
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.HeightCm,
		&i.DateOfBirth,
		&i.Sex,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const insertBiometric = `-- name: InsertBiometric :one
INSERT INTO user_biometrics (user_id, weight_kg, height_cm, date_of_birth, sex, is_current)
VALUES ($1, $2, $3, $4, $5, true)
RETURNING id, user_id, weight_kg, height_cm, date_of_birth, sex, is_current, created_at
`

type InsertBiometricParams struct {
	UserID      uuid.UUID
	WeightKg    float64
	HeightCm    float64
	DateOfBirth pgtype.Date
	Sex         string
}

func (q *Queries) InsertBiometric(ctx context.Context, arg InsertBiometricParams) (UserBiometric, error) {
	row := q.db.QueryRow(ctx, insertBiometric,
		arg.UserID,
		arg.WeightKg,
		arg.HeightCm,
		arg.DateOfBirth,
		arg.Sex,
	)
	var i UserBiometric
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.WeightKg,
		&i.HeightCm,
		&i.DateOfBirth,
		&i.Sex,
		&i.IsCurrent,
		&i.CreatedAt,
	)
	return i, err
}

const listBiometrics = `-- name: ListBiometrics :many
SELECT id, user_id, weight_kg, height_cm, date_of_birth, sex, is_current, created_at FROM user_biometrics
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListBiometricsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListBiometrics(ctx context.Context, arg ListBiometricsParams) ([]UserBiometric, error) {
	rows, err := q.db.Query(ctx, listBiometrics, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBiometric{}
	for rows.Next() {
		var i UserBiometric
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.WeightKg,
			&i.HeightCm,
			&i.DateOfBirth,
			&i.Sex,
			&i.IsCurrent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetCurrentBiometrics = `-- name: UnsetCurrentBiometrics :exec
UPDATE user_biometrics SET is_current = false WHERE user_id = $1 AND is_current
`

func (q *Queries) UnsetCurrentBiometrics(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsetCurrentBiometrics, userID)
	return err
}
