-- +goose Up
-- Written cues for catalogue rows that had artwork and no text.
--
-- Generated by scripts/exercise-cues on 2026-09-07 from
-- github.com/yuhonas/free-exercise-db (Unlicense — public domain, no
-- attribution obligation and no condition that follows the text downstream).
-- That licence is why this source and not the two better-known alternatives:
-- see the command's doc comment for the measurements.
--
-- Matched on the exact normalised name, which is the only join the two
-- catalogues share. Deliberately narrow: a looser match is how a squat's
-- instructions end up on a deadlift, and a row with no cues is a much smaller
-- problem than a row with the wrong ones.
--
-- Only rows that are still empty are touched, so this cannot overwrite text
-- somebody wrote by hand, and re-running it is a no-op.

UPDATE exercises SET instructions = 'Stand up and extend your arms straight out by the sides. The arms should be parallel to the floor and perpendicular (90-degree angle) to your torso. This will be your starting position. Slowly start to make circles of about 1 foot in diameter with each outstretched arm. Breathe normally as you perform the movement. Continue the circular motion of the outstretched arms for about ten seconds. Then reverse the movement, going the opposite direction.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'armcircles'
   AND instructions = '';

UPDATE exercises SET instructions = 'Begin with your arms extended straight out in front of you, holding the band with both hands. Initiate the movement by performing a reverse fly motion, moving your hands out laterally to your sides. Keep your elbows extended as you perform the movement, bringing the band to your chest. Ensure that you keep your shoulders back during the exercise. Pause as you complete the movement, returning to the starting position under control.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'bandpullapart'
   AND instructions = '';

UPDATE exercises SET instructions = 'Stand with your feet shoulder width apart. You can place your hands behind your head. This will be your starting position. Begin the movement by flexing your knees and hips, sitting back with your hips. Continue down to full depth if you are able,and quickly reverse the motion until you return to the starting position. As you squat, keep your head and chest up and push your knees out.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'bodyweightsquat'
   AND instructions = '';

UPDATE exercises SET instructions = 'Kneel below a high pulley that contains a rope attachment. Grasp cable rope attachment and lower the rope until your hands are placed next to your face. Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position. With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second. Slowly return to the starting position as you inhale. Tip: Make sure that you keep constant tension on the abs throughout the movement. Also, do not choose a weight so heavy that the lower back handles the brunt of the work. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'cablecrunch'
   AND instructions = '';

UPDATE exercises SET instructions = 'Adjust the pulleys to the appropriate height and adjust the weight. The pulleys should be above your head. Grab the left pulley with your right hand and the right pulley with your left hand, crossing them in front of you. This will be your starting position. Initiate the movement by moving your arms back and outward, keeping your arms straight as you execute the movement. Pause at the end of the motion before returning the handles to the start position.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'cablereardeltfly'
   AND instructions = '';

UPDATE exercises SET instructions = 'Get on your hands and knees, walk your hands in front of you. Lower your buttocks down to sit on your heels. Let your arms drag along the floor as you sit back to stretch your entire spine. Once you settle onto your heels, bring your hands next to your feet and relax. "breathe" into your back. Rest your forehead on the floor. Avoid this position if you have knee problems.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'childspose'
   AND instructions = '';

UPDATE exercises SET instructions = 'Grab the pull-up bar with the palms facing your torso and a grip closer than the shoulder width. As you have both arms extended in front of you holding the bar at the chosen grip width, keep your torso as straight as possible while creating a curvature on your lower back and sticking your chest out. This is your starting position. Tip: Keeping the torso as straight as possible maximizes biceps stimulation while minimizing back involvement. As you breathe out, pull your torso up until your head is around the level of the pull-up bar. Concentrate on using the biceps muscles in order to perform the movement. Keep the elbows close to your body. Tip: The upper torso should remain stationary as it moves through space and only the arms should move. The forearms should do no other work other than hold the bar. After a second of squeezing the biceps in the contracted position, slowly lower your torso back to the starting position; when your arms are fully extended. Breathe in as you perform this portion of the movement. Repeat this motion for the prescribed amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'chinup'
   AND instructions = '';

UPDATE exercises SET instructions = 'Begin lying on your back with your hands extended above you toward the ceiling. Bring your feet, knees, and hips up to 90 degrees. Exhale hard to bring your ribcage down and flatten your back onto the floor, rotating your pelvis up and squeezing your glutes. Hold this position throughout the movement. This will be your starting position. Initiate the exercise by extending one leg, straightening the knee and hip to bring the leg just above the ground. Maintain the position of your lumbar and pelvis as you perform the movement, as your back is going to want to arch. Stay tight and return the working leg to the starting position. Repeat on the opposite side, alternating until the set is complete.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'deadbug'
   AND instructions = '';

UPDATE exercises SET instructions = 'Lie on the floor face down and place your hands about 36 inches apart while holding your torso up at arms length. Move your feet up to a box or bench. This will be your starting position. Next, lower yourself downward until your chest almost touches the floor as you inhale. Now breathe out and press your upper body back up to the starting position while squeezing your chest. After a brief pause at the top contracted position, you can begin to lower yourself downward again for as many repetitions as needed.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'declinepushup'
   AND instructions = '';

UPDATE exercises SET instructions = 'Grab a barbell with a supinated grip (palms facing forward) and get your elbows close to your torso and back. This will be your starting position. As you exhale, curl the bar up while keeping the elbows to the back as you "Drag" the bar up by keeping it in contact with your torso. Tip: As you can see, you will not be keeping the elbows pinned to your sides, but instead you will be bringing them back. Also, do not lift your shoulders. Slowly go back to the starting position as you keep the bar in contact with the torso at all times. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'dragcurl'
   AND instructions = '';

UPDATE exercises SET instructions = 'Stand up straight while holding a dumbbell on the left hand (palms facing the torso) as you have the right hand holding your waist. Your feet should be placed at shoulder width. This will be your starting position. While keeping your back straight and your head up, bend only at the waist to the right as far as possible. Breathe in as you bend to the side. Then hold for a second and come back up to the starting position as you exhale. Tip: Keep the rest of the body stationary. Now repeat the movement but bending to the left instead. Hold for a second and come back to the starting position. Repeat for the recommended amount of repetitions and then change hands.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'dumbbellsidebend'
   AND instructions = '';

UPDATE exercises SET instructions = 'Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'facepull'
   AND instructions = '';

UPDATE exercises SET instructions = 'Stand holding a light kettlebell by the horns close to your chest. This will be your starting position. Squat down between your legs until your hamstrings are on your calves. Keep your chest and head up and your back straight. At the bottom position, pause and use your elbows to push your knees out. Return to the starting position, and repeat for 10-20 repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'gobletsquat'
   AND instructions = '';

UPDATE exercises SET instructions = 'Begin with a bar on a rack at shoulder height. Rack the bar across the rear of your shoulders as you would a power squat, not on top of your shoulders. Keep your back tight, shoulder blades pinched together, and your knees slightly bent. Step back from the rack. Begin by bending at the hips, moving them back as you bend over to near parallel. Keep your back arched and your cervical spine in proper alignment. Reverse the motion by extending through the hips with your glutes and hamstrings. Continue until you have returned to the starting position.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'goodmorning'
   AND instructions = '';

UPDATE exercises SET instructions = 'Place the back of your torso against the back pad of the machine and hook your shoulders under the shoulder pads provided. Position your legs in the platform using a shoulder width medium stance with the toes slightly pointed out. Tip: Keep your head up at all times and also maintain the back on the pad at all times. Place your arms on the side handles of the machine and disengage the safety bars (which on most designs is done by moving the side handles from a facing front position to a diagonal position). Now straighten your legs without locking the knees. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section). Begin to slowly lower the unit by bending the knees as you maintain a straight posture with the head up (back on the pad at all times). Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly. Begin to raise the unit as you exhale by pushing the floor with mainly with the heel of your foot as you straighten the legs again and go back to the starting position. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'hacksquat'
   AND instructions = '';

UPDATE exercises SET instructions = 'Lie on your back with one leg extended above you, with the hip at ninety degrees. Keep the other leg flat on the floor. Loop a belt, band, or rope over the ball of your foot. This will be your starting position. Pull on the belt to create tension in the calves and hamstrings. Hold this stretch for 10-30 seconds, and repeat with the other leg.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'hamstringstretch'
   AND instructions = '';

UPDATE exercises SET instructions = 'Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position. Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so. Go back slowly to the starting position as you breathe in. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'hanginglegraise'
   AND instructions = '';

UPDATE exercises SET instructions = 'Stand with your feet close together. Keeping your legs straight, stretch down and put your hands on the floor directly in front of you. This will be your starting position. Begin by walking your hands forward slowly, alternating your left and your right. As you do so, bend only at the hip, keeping your legs straight. Keep going until your body is parallel to the ground in a pushup position. Now, keep your hands in place and slowly take short steps with your feet, moving only a few inches at a time. Continue walking until your feet are by hour hands, keeping your legs straight as you do so.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'inchworm'
   AND instructions = '';

UPDATE exercises SET instructions = 'Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position. While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second. Slowly begin to bring the dumbbells back to starting position as your breathe in. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'inclinedumbbellcurl'
   AND instructions = '';

UPDATE exercises SET instructions = 'Stand facing bench or sturdy elevated platform. Place hands on edge of bench or platform, slightly wider than shoulder width. Position forefoot back from bench or platform with arms and body straight. Arms should be perpendicular to body. Keeping body straight, lower chest to edge of box or platform by bending arms. Push body up until arms are extended. Repeat.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'inclinepushup'
   AND instructions = '';

UPDATE exercises SET instructions = 'Position a bar in a rack to about waist height. You can also use a smith machine. Take a wider than shoulder width grip on the bar and position yourself hanging underneath the bar. Your body should be straight with your heels on the ground with your arms fully extended. This will be your starting position. Begin by flexing the elbow, pulling your chest towards the bar. Retract your shoulder blades as you perform the movement. Pause at the top of the motion, and return yourself to the start position. Repeat for the desired number of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'invertedrow'
   AND instructions = '';

UPDATE exercises SET instructions = 'Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section). Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position. As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle. Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale. Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'legpress'
   AND instructions = '';

UPDATE exercises SET instructions = 'Connect a standard handle to a tower, and—if possible—position the cable to shoulder height. If not, a low pulley will suffice. With your side to the cable, grab the handle with both hands and step away from the tower. You should be approximately arm''s length away from the pulley, with the tension of the weight on the cable. With your feet positioned hip-width apart and knees slightly bent, hold the cable to the middle of your chest. This will be your starting position. Press the cable away from your chest, fully extending both arms. You core should be tight and engaged. Hold the repetition for several seconds before returning to the starting position. At the conclusion of the set, repeat facing the other direction.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'pallofpress'
   AND instructions = '';

UPDATE exercises SET instructions = 'To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar. With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position. As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched. As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'preachercurl'
   AND instructions = '';

UPDATE exercises SET instructions = 'Lie down on the floor with your legs fully extended and arms to the side of your torso with the palms on the floor. Your arms should be stationary for the entire exercise. Move your legs up so that your thighs are perpendicular to the floor and feet are together and parallel to the floor. This is the starting position. While inhaling, move your legs towards the torso as you roll your pelvis backwards and you raise your hips off the floor. At the end of this movement your knees will be touching your chest. Hold the contraction for a second and move your legs back to the starting position while exhaling. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'reversecrunch'
   AND instructions = '';

UPDATE exercises SET instructions = 'Place your feet between the pads after loading an appropriate weight. Lay on the top pad, allowing your hips to hang off the back, while grasping the handles to hold your position. To begin the movement, flex the hips, pulling the legs forward. Reverse the motion by extending the hips, kicking the leg back. It is very important not to over-extend the hip on this movement, stopping short of your full range of motion. Return by again flexing the hip, pulling the carriage forward as far as you can. Repeat for the desired number of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'reversehyperextension'
   AND instructions = '';

UPDATE exercises SET instructions = 'Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion. Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position. Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control. Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'romaniandeadlift'
   AND instructions = '';

UPDATE exercises SET instructions = 'Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees. Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position. Twist your torso to the right side until your arms are parallel with the floor while breathing out. Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'russiantwist'
   AND instructions = '';

UPDATE exercises SET instructions = 'Take a pronated grip on a pull-up bar. From a hanging position, raise yourself a few inches without using your arms. Do this by depressing your shoulder girdle in a reverse shrugging motion. Pause at the completion of the movement, and then slowly return to the starting position before performing more repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'scapularpullup'
   AND instructions = '';

UPDATE exercises SET instructions = 'Adjust the machine lever to fit your height and sit on the machine with your back against the back support pad. Place the back of lower leg on top of padded lever (just a few inches under the calves) and secure the lap pad against your thighs, just above the knees. Then grasp the side handles on the machine as you point your toes straight (or you can also use any of the other two stances) and ensure that the legs are fully straight right in front of you. This will be your starting position. As you exhale, pull the machine lever as far as possible to the back of your thighs by flexing at the knees. Keep your torso stationary at all times. Hold the contracted position for a second. Slowly return to the starting position as you breathe in. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'seatedlegcurl'
   AND instructions = '';

UPDATE exercises SET instructions = 'Place a flat bench underneath the smith machine. Now place the barbell at a height that you can reach when lying down and your arms are almost fully extended. Once the weight you need is selected, lie down on the flat bench. Using a pronated grip that is wider than shoulder width, unlock the bar from the rack and hold it straight over you with your arms locked. This will be your starting position. As you breathe in, come down slowly until you feel the bar on your middle chest. After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up. Repeat the movement for the prescribed amount of repetitions. When you are done, lock the bar back in the rack.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'smithmachinebenchpress'
   AND instructions = '';

UPDATE exercises SET instructions = 'To begin, first set the bar on the height that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it. Hold on to the bar using both arms at each side (palms facing forward), unlock it and lift it off the rack by first pushing with your legs and at the same time straightening your torso. Position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance which targets overall development; however you can choose any of the three stances discussed in the foot stances section). Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly. Begin to raise the bar as you exhale by pushing the floor with the heel of your foot as you straighten the legs again and go back to the starting position. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'smithmachinesquat'
   AND instructions = '';

UPDATE exercises SET instructions = 'Start out by setting the bar on the part of the preacher bench that you would normally sit on. Make sure to align the barbell properly so that it is balanced and will not fall off. Move to the front side of the preacher bench (the part where the arms usually lay) and position yourself to lay at a 45 degree slant with your torso and stomach pressed against the front side of the preacher bench. Make sure that your feet (especially the toes) are well positioned on the floor and place your upper arms on top of the pad located on the inside part of the preacher bench. Use your arms to grab the barbell with a supinated grip (palms facing up) at about shoulder width apart or slightly closer from each other. Slowly begin to lift the barbell upwards and exhale. Hold the contracted position for a second as you squeeze the biceps. Slowly begin to bring the barbell back to the starting position as your breathe in. . Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'spidercurl'
   AND instructions = '';

UPDATE exercises SET instructions = 'Standing with your feet shoulder width apart, take a dumbbell in each hand. Raise the dumbbells to head height, the elbows out and about 90 degrees. This will be your starting position. Maintaining strict technique with no leg drive or leaning back, extend through the elbow to raise the weights together directly above your head. Pause, and slowly return the weight to the starting position.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'standingdumbbellpress'
   AND instructions = '';

UPDATE exercises SET instructions = 'You will start by grabbing the wide bar from the top pulley of a pulldown machine and using a wider than shoulder-width pronated (palms down) grip. Step backwards two feet or so. Bend your torso forward at the waist by around 30-degrees with your arms fully extended in front of you and a slight bend at the elbows. If your arms are not fully extended then you need to step a bit more backwards until they are. Once your arms are fully extended and your torso is slightly bent at the waist, tighten the lats and then you are ready to begin. While keeping the arms straight, pull the bar down by contracting the lats until your hands are next to the side of the thighs. Breathe out as you perform this step. While keeping the arms straight, go back to the starting position while breathing in. Repeat for the recommended amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'straightarmpulldown'
   AND instructions = '';

UPDATE exercises SET instructions = 'For this exercise load a trap bar, also known as a hex bar, to an appropriate weight resting on the ground. Stand in the center of the apparatus and grasp both handles. Lower your hips, look forward with your head and keep your chest up. Begin the movement by driving through the heels and extend your hips and knees. Avoid rounding your back at all times. At the completion of the movement, lower the weight back to the ground under control.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'trapbardeadlift'
   AND instructions = '';

UPDATE exercises SET instructions = 'Sit down on a pull-down machine with a wide bar attached to the top pulley. Make sure that you adjust the knee pad of the machine to fit your height. These pads will prevent your body from being raised by the resistance attached to the bar. Grab the bar with the palms facing forward using the prescribed grip. Note on grips: For a wide grip, your hands need to be spaced out at a distance wider than shoulder width. For a medium grip, your hands need to be spaced out at a distance equal to your shoulder width and for a close grip at a distance smaller than your shoulder width. As you have both arms extended in front of you holding the bar at the chosen grip width, bring your torso back around 30 degrees or so while creating a curvature on your lower back and sticking your chest out. This is your starting position. As you breathe out, bring the bar down until it touches your upper chest by drawing the shoulders and the upper arms down and back. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. The upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the bar; therefore do not try to pull down the bar using the forearms. After a second at the contracted position squeezing your shoulder blades together, slowly raise the bar back to the starting position when your arms are fully extended and the lats are fully stretched. Inhale during this portion of the movement. Repeat this motion for the prescribed amount of repetitions.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'widegriplatpulldown'
   AND instructions = '';

UPDATE exercises SET instructions = 'This is a three-part stretch. Begin by lunging forward, with your front foot flat on the ground and on the toes of your back foot. With your knees bent, squat down until your knee is almost touching the ground. Keep your torso erect, and hold this position for 10-20 seconds. Now, place the arm on the same side as your front leg on the ground, with the elbow next to the foot. Your other hand should be placed on the ground, parallel to your lead leg, to help support you during this portion of the stretch. After 10-20 seconds, place your hands on either side of your front foot. Raise the toes of the front foot off of the ground, and straighten your leg. You may need to reposition your rear leg to do so. Hold for 10-20 seconds, and then repeat the entire sequence for the other side.', updated_at = now()
 WHERE regexp_replace(lower(name), '[^a-z0-9]', '', 'g') = 'worldsgreateststretch'
   AND instructions = '';

-- +goose Down
-- Not reversible by row: the column had no other content to restore, and
-- emptying every match would also discard anything written since. Rows that
-- were filled here stay filled.
SELECT 1;
