// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package nudgesdb

import (
	"time"

	"github.com/google/uuid"
)

type UserNudge struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Kind        string
	DedupeKey   string
	Title       string
	Body        string
	Href        string
	ReadAt      *time.Time
	DismissedAt *time.Time
	CreatedAt   time.Time
}
