// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package workoutsdb

import (
	"time"

	"github.com/google/uuid"
)

type WorkoutIntake struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Goal           string
	Experience     string
	DaysPerWeek    int16
	SessionMinutes int16
	Equipment      []string
	Limitations    string
	CreatedAt      time.Time
}

type WorkoutPlan struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	IntakeID   uuid.UUID
	Name       string
	Plan       []byte
	Model      string
	Provider   string
	CreatedAt  time.Time
	Source     string
	EditedFrom *uuid.UUID
}
