// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package workoutsdb

import (
	"context"

	"github.com/google/uuid"
)

const createIntake = `-- name: CreateIntake :one
INSERT INTO workout_intakes (user_id, goal, experience, days_per_week, session_minutes, equipment, limitations)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, goal, experience, days_per_week, session_minutes, equipment, limitations, created_at
`

type CreateIntakeParams struct {
	UserID         uuid.UUID
	Goal           string
	Experience     string
	DaysPerWeek    int16
	SessionMinutes int16
	Equipment      []string
	Limitations    string
}

func (q *Queries) CreateIntake(ctx context.Context, arg CreateIntakeParams) (WorkoutIntake, error) {
	row := q.db.QueryRow(ctx, createIntake,
		arg.UserID,
		arg.Goal,
		arg.Experience,
		arg.DaysPerWeek,
		arg.SessionMinutes,
		arg.Equipment,
		arg.Limitations,
	)
	var i WorkoutIntake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goal,
		&i.Experience,
		&i.DaysPerWeek,
		&i.SessionMinutes,
		&i.Equipment,
		&i.Limitations,
		&i.CreatedAt,
	)
	return i, err
}

const createPlan = `-- name: CreatePlan :one
INSERT INTO workout_plans (user_id, intake_id, name, plan, model, provider)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, intake_id, name, plan, model, provider, created_at
`

type CreatePlanParams struct {
	UserID   uuid.UUID
	IntakeID uuid.UUID
	Name     string
	Plan     []byte
	Model    string
	Provider string
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (WorkoutPlan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.UserID,
		arg.IntakeID,
		arg.Name,
		arg.Plan,
		arg.Model,
		arg.Provider,
	)
	var i WorkoutPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntakeID,
		&i.Name,
		&i.Plan,
		&i.Model,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}

const getIntake = `-- name: GetIntake :one
SELECT id, user_id, goal, experience, days_per_week, session_minutes, equipment, limitations, created_at FROM workout_intakes WHERE id = $1 AND user_id = $2
`

type GetIntakeParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetIntake(ctx context.Context, arg GetIntakeParams) (WorkoutIntake, error) {
	row := q.db.QueryRow(ctx, getIntake, arg.ID, arg.UserID)
	var i WorkoutIntake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goal,
		&i.Experience,
		&i.DaysPerWeek,
		&i.SessionMinutes,
		&i.Equipment,
		&i.Limitations,
		&i.CreatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, user_id, intake_id, name, plan, model, provider, created_at FROM workout_plans WHERE id = $1 AND user_id = $2
`

type GetPlanParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetPlan(ctx context.Context, arg GetPlanParams) (WorkoutPlan, error) {
	row := q.db.QueryRow(ctx, getPlan, arg.ID, arg.UserID)
	var i WorkoutPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntakeID,
		&i.Name,
		&i.Plan,
		&i.Model,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}

const latestIntake = `-- name: LatestIntake :one
SELECT id, user_id, goal, experience, days_per_week, session_minutes, equipment, limitations, created_at FROM workout_intakes
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) LatestIntake(ctx context.Context, userID uuid.UUID) (WorkoutIntake, error) {
	row := q.db.QueryRow(ctx, latestIntake, userID)
	var i WorkoutIntake
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Goal,
		&i.Experience,
		&i.DaysPerWeek,
		&i.SessionMinutes,
		&i.Equipment,
		&i.Limitations,
		&i.CreatedAt,
	)
	return i, err
}

const latestPlan = `-- name: LatestPlan :one
SELECT id, user_id, intake_id, name, plan, model, provider, created_at FROM workout_plans
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// Feeds the coach's context, so it can reference the plan the user is actually
// following instead of asking them to describe it again.
func (q *Queries) LatestPlan(ctx context.Context, userID uuid.UUID) (WorkoutPlan, error) {
	row := q.db.QueryRow(ctx, latestPlan, userID)
	var i WorkoutPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IntakeID,
		&i.Name,
		&i.Plan,
		&i.Model,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, user_id, intake_id, name, plan, model, provider, created_at FROM workout_plans
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListPlansParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]WorkoutPlan, error) {
	rows, err := q.db.Query(ctx, listPlans, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutPlan{}
	for rows.Next() {
		var i WorkoutPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IntakeID,
			&i.Name,
			&i.Plan,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
