// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sleepdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSleepLog = `-- name: DeleteSleepLog :exec
DELETE FROM sleep_logs WHERE id = $1 AND user_id = $2
`

type DeleteSleepLogParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSleepLog(ctx context.Context, arg DeleteSleepLogParams) error {
	_, err := q.db.Exec(ctx, deleteSleepLog, arg.ID, arg.UserID)
	return err
}

const getSleepLogForDate = `-- name: GetSleepLogForDate :one
SELECT id, user_id, local_date, duration_minutes, quality, bedtime, wake_time, notes, created_at, updated_at FROM sleep_logs
WHERE user_id = $1 AND local_date = $2
`

type GetSleepLogForDateParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
}

func (q *Queries) GetSleepLogForDate(ctx context.Context, arg GetSleepLogForDateParams) (SleepLog, error) {
	row := q.db.QueryRow(ctx, getSleepLogForDate, arg.UserID, arg.LocalDate)
	var i SleepLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocalDate,
		&i.DurationMinutes,
		&i.Quality,
		&i.Bedtime,
		&i.WakeTime,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSleepLogs = `-- name: ListSleepLogs :many
SELECT id, user_id, local_date, duration_minutes, quality, bedtime, wake_time, notes, created_at, updated_at FROM sleep_logs
WHERE user_id = $1
ORDER BY local_date DESC
LIMIT $2
`

type ListSleepLogsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListSleepLogs(ctx context.Context, arg ListSleepLogsParams) ([]SleepLog, error) {
	rows, err := q.db.Query(ctx, listSleepLogs, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SleepLog{}
	for rows.Next() {
		var i SleepLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocalDate,
			&i.DurationMinutes,
			&i.Quality,
			&i.Bedtime,
			&i.WakeTime,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSleepLog = `-- name: UpsertSleepLog :one
INSERT INTO sleep_logs (
    user_id, local_date, duration_minutes, quality, bedtime, wake_time, notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (user_id, local_date) DO UPDATE SET
    duration_minutes = EXCLUDED.duration_minutes,
    quality          = EXCLUDED.quality,
    bedtime          = EXCLUDED.bedtime,
    wake_time        = EXCLUDED.wake_time,
    notes            = EXCLUDED.notes,
    updated_at       = now()
RETURNING id, user_id, local_date, duration_minutes, quality, bedtime, wake_time, notes, created_at, updated_at
`

type UpsertSleepLogParams struct {
	UserID          uuid.UUID
	LocalDate       pgtype.Date
	DurationMinutes int32
	Quality         *int16
	Bedtime         *string
	WakeTime        *string
	Notes           string
}

func (q *Queries) UpsertSleepLog(ctx context.Context, arg UpsertSleepLogParams) (SleepLog, error) {
	row := q.db.QueryRow(ctx, upsertSleepLog,
		arg.UserID,
		arg.LocalDate,
		arg.DurationMinutes,
		arg.Quality,
		arg.Bedtime,
		arg.WakeTime,
		arg.Notes,
	)
	var i SleepLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocalDate,
		&i.DurationMinutes,
		&i.Quality,
		&i.Bedtime,
		&i.WakeTime,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
