// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package documentsdb

import (
	"time"

	"github.com/google/uuid"
)

type Document struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Title              string
	SourceKind         string
	StorageKey         *string
	Body               *string
	Mime               string
	ByteSize           int64
	ContentSha256      string
	LineCount          int32
	Status             string
	ParseError         string
	IndexedAt          *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	DeletedAt          *time.Time
	ChunkerFingerprint string
	ExternalPath       *string
	ExternalMtime      *time.Time
}

type IndexRun struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Kind               string
	StartedAt          time.Time
	CompletedAt        *time.Time
	DocumentsSeen      int32
	DocumentsAdded     int32
	DocumentsUpdated   int32
	DocumentsUnchanged int32
	DocumentsFailed    int32
	ChunksWritten      int32
	ChunksRemoved      int32
	Warnings           []byte
	Success            bool
	ErrorSummary       string
}
