// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package apnsdb

import (
	"time"

	"github.com/google/uuid"
)

type ApnsDevice struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Token       string
	Topic       string
	Environment string
	CreatedAt   time.Time
	LastUsedAt  *time.Time
	FailedAt    *time.Time
}
