// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package apnsdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteAPNsDevice = `-- name: DeleteAPNsDevice :exec
DELETE FROM apns_devices WHERE id = $1
`

func (q *Queries) DeleteAPNsDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPNsDevice, id)
	return err
}

const deleteAPNsDeviceByToken = `-- name: DeleteAPNsDeviceByToken :execrows
DELETE FROM apns_devices WHERE user_id = $1 AND token = $2
`

type DeleteAPNsDeviceByTokenParams struct {
	UserID uuid.UUID
	Token  string
}

func (q *Queries) DeleteAPNsDeviceByToken(ctx context.Context, arg DeleteAPNsDeviceByTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPNsDeviceByToken, arg.UserID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAPNsDevices = `-- name: ListAPNsDevices :many
SELECT id, user_id, token, topic, environment, created_at, last_used_at, failed_at FROM apns_devices WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListAPNsDevices(ctx context.Context, userID uuid.UUID) ([]ApnsDevice, error) {
	rows, err := q.db.Query(ctx, listAPNsDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApnsDevice{}
	for rows.Next() {
		var i ApnsDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Topic,
			&i.Environment,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.FailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAPNsDeviceFailed = `-- name: MarkAPNsDeviceFailed :exec
UPDATE apns_devices SET failed_at = now() WHERE id = $1
`

func (q *Queries) MarkAPNsDeviceFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAPNsDeviceFailed, id)
	return err
}

const markAPNsDeviceUsed = `-- name: MarkAPNsDeviceUsed :exec
UPDATE apns_devices SET last_used_at = now(), failed_at = NULL WHERE id = $1
`

func (q *Queries) MarkAPNsDeviceUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAPNsDeviceUsed, id)
	return err
}

const upsertAPNsDevice = `-- name: UpsertAPNsDevice :one
INSERT INTO apns_devices (user_id, token, topic, environment)
VALUES ($1, $2, $3, $4)
ON CONFLICT (token) DO UPDATE
SET user_id = EXCLUDED.user_id,
    topic = EXCLUDED.topic,
    environment = EXCLUDED.environment,
    failed_at = NULL
RETURNING id, user_id, token, topic, environment, created_at, last_used_at, failed_at
`

type UpsertAPNsDeviceParams struct {
	UserID      uuid.UUID
	Token       string
	Topic       string
	Environment string
}

// A re-register from the same install refreshes its topic and environment and
// clears any earlier failure. An install that signed in as somebody else
// moves with them.
func (q *Queries) UpsertAPNsDevice(ctx context.Context, arg UpsertAPNsDeviceParams) (ApnsDevice, error) {
	row := q.db.QueryRow(ctx, upsertAPNsDevice,
		arg.UserID,
		arg.Token,
		arg.Topic,
		arg.Environment,
	)
	var i ApnsDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Topic,
		&i.Environment,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.FailedAt,
	)
	return i, err
}
