// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package socialdb

import (
	"time"

	"github.com/google/uuid"
)

type Follow struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	Status     string
	CreatedAt  time.Time
	AcceptedAt *time.Time
}

type Invite struct {
	Code      string
	InviterID uuid.UUID
	Channel   string
	CreatedAt time.Time
}

type PhoneVerification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PhoneE164 string
	Attempts  int32
	CreatedAt time.Time
	ClosedAt  *time.Time
}
