// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package socialdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptFollow = `-- name: AcceptFollow :execrows
UPDATE follows SET status = 'accepted', accepted_at = now()
WHERE follower_id = $1 AND followee_id = $2 AND status = 'pending'
`

type AcceptFollowParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) AcceptFollow(ctx context.Context, arg AcceptFollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptFollow, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const block = `-- name: Block :exec
INSERT INTO blocks (blocker_id, blocked_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type BlockParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) Block(ctx context.Context, arg BlockParams) error {
	_, err := q.db.Exec(ctx, block, arg.BlockerID, arg.BlockedID)
	return err
}

const clearPhone = `-- name: ClearPhone :exec
UPDATE users SET phone_e164 = NULL, phone_verified_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) ClearPhone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearPhone, id)
	return err
}

const closePhoneVerification = `-- name: ClosePhoneVerification :exec
UPDATE phone_verifications SET closed_at = now() WHERE id = $1
`

func (q *Queries) ClosePhoneVerification(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, closePhoneVerification, id)
	return err
}

const closePhoneVerifications = `-- name: ClosePhoneVerifications :exec
UPDATE phone_verifications SET closed_at = now()
WHERE user_id = $1 AND closed_at IS NULL
`

func (q *Queries) ClosePhoneVerifications(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, closePhoneVerifications, userID)
	return err
}

const countFollows = `-- name: CountFollows :one
SELECT
    (SELECT count(*) FROM follows f1 WHERE f1.followee_id = $1 AND f1.status = 'accepted') AS followers,
    (SELECT count(*) FROM follows f2 WHERE f2.follower_id = $1 AND f2.status = 'accepted') AS following
`

type CountFollowsRow struct {
	Followers int64
	Following int64
}

func (q *Queries) CountFollows(ctx context.Context, followeeID uuid.UUID) (CountFollowsRow, error) {
	row := q.db.QueryRow(ctx, countFollows, followeeID)
	var i CountFollowsRow
	err := row.Scan(&i.Followers, &i.Following)
	return i, err
}

const countPhoneCheck = `-- name: CountPhoneCheck :one
UPDATE phone_verifications SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

// Counted before the code is checked, so parallel guesses cannot outrun
// the limit.
func (q *Queries) CountPhoneCheck(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPhoneCheck, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const countPhoneStartsByNumber = `-- name: CountPhoneStartsByNumber :one
SELECT count(*) FROM phone_verifications
WHERE phone_e164 = $1 AND created_at > $2
`

type CountPhoneStartsByNumberParams struct {
	PhoneE164 string
	Since     time.Time
}

func (q *Queries) CountPhoneStartsByNumber(ctx context.Context, arg CountPhoneStartsByNumberParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhoneStartsByNumber, arg.PhoneE164, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPhoneStartsByUser = `-- name: CountPhoneStartsByUser :one
SELECT count(*) FROM phone_verifications
WHERE user_id = $1 AND created_at > $2
`

type CountPhoneStartsByUserParams struct {
	UserID uuid.UUID
	Since  time.Time
}

func (q *Queries) CountPhoneStartsByUser(ctx context.Context, arg CountPhoneStartsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPhoneStartsByUser, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRedemptions = `-- name: CountRedemptions :one
SELECT count(*) FROM invite_redemptions r
JOIN invites i ON i.code = r.code
WHERE i.inviter_id = $1
`

func (q *Queries) CountRedemptions(ctx context.Context, inviterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRedemptions, inviterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFacebookOAuthState = `-- name: CreateFacebookOAuthState :exec
INSERT INTO facebook_oauth_states (state_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateFacebookOAuthStateParams struct {
	StateHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateFacebookOAuthState(ctx context.Context, arg CreateFacebookOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createFacebookOAuthState, arg.StateHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code, inviter_id, channel)
VALUES ($1, $2, $3)
ON CONFLICT (inviter_id, channel) DO NOTHING
RETURNING code, inviter_id, channel, created_at
`

type CreateInviteParams struct {
	Code      string
	InviterID uuid.UUID
	Channel   string
}

// ON CONFLICT DO NOTHING returns no row, so a lost race reads the winner's
// code with InviteFor instead of failing.
func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite, arg.Code, arg.InviterID, arg.Channel)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.InviterID,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}

const createPhoneVerification = `-- name: CreatePhoneVerification :one
INSERT INTO phone_verifications (user_id, phone_e164)
VALUES ($1, $2)
RETURNING id, user_id, phone_e164, attempts, created_at, closed_at
`

type CreatePhoneVerificationParams struct {
	UserID    uuid.UUID
	PhoneE164 string
}

func (q *Queries) CreatePhoneVerification(ctx context.Context, arg CreatePhoneVerificationParams) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, createPhoneVerification, arg.UserID, arg.PhoneE164)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneE164,
		&i.Attempts,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const deleteExpiredFacebookOAuthStates = `-- name: DeleteExpiredFacebookOAuthStates :exec
DELETE FROM facebook_oauth_states WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredFacebookOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredFacebookOAuthStates)
	return err
}

const deleteFacebookImport = `-- name: DeleteFacebookImport :exec
DELETE FROM facebook_imports WHERE user_id = $1
`

func (q *Queries) DeleteFacebookImport(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFacebookImport, userID)
	return err
}

const deleteFollow = `-- name: DeleteFollow :execrows
DELETE FROM follows WHERE follower_id = $1 AND followee_id = $2
`

type DeleteFollowParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFollow, arg.FollowerID, arg.FolloweeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteFollowsBetween = `-- name: DeleteFollowsBetween :exec
DELETE FROM follows
WHERE (follower_id = $1 AND followee_id = $2) OR (follower_id = $2 AND followee_id = $1)
`

type DeleteFollowsBetweenParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) DeleteFollowsBetween(ctx context.Context, arg DeleteFollowsBetweenParams) error {
	_, err := q.db.Exec(ctx, deleteFollowsBetween, arg.FollowerID, arg.FolloweeID)
	return err
}

const facebookFriendsHere = `-- name: FacebookFriendsHere :many
SELECT u.id
FROM auth_identities ai JOIN users u ON u.id = ai.user_id
WHERE ai.provider = 'facebook'
  AND ai.provider_subject = ANY($1::text[])
  AND u.handle IS NOT NULL
  AND u.id <> $2
  AND NOT EXISTS (SELECT 1 FROM blocks b
                  WHERE (b.blocker_id = $2 AND b.blocked_id = u.id)
                     OR (b.blocker_id = u.id AND b.blocked_id = $2))
LIMIT 200
`

type FacebookFriendsHereParams struct {
	Subjects []string
	Viewer   uuid.UUID
}

// Accounts linked to any of these Facebook ids that the viewer may be
// shown: a handle, not themselves, no block either way.
func (q *Queries) FacebookFriendsHere(ctx context.Context, arg FacebookFriendsHereParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, facebookFriendsHere, arg.Subjects, arg.Viewer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const facebookImport = `-- name: FacebookImport :one
SELECT people, imported_at FROM facebook_imports
WHERE user_id = $1 AND expires_at > now()
`

type FacebookImportRow struct {
	People     []uuid.UUID
	ImportedAt time.Time
}

func (q *Queries) FacebookImport(ctx context.Context, userID uuid.UUID) (FacebookImportRow, error) {
	row := q.db.QueryRow(ctx, facebookImport, userID)
	var i FacebookImportRow
	err := row.Scan(&i.People, &i.ImportedAt)
	return i, err
}

const facebookOwner = `-- name: FacebookOwner :one

SELECT user_id FROM auth_identities
WHERE provider = 'facebook' AND provider_subject = $1
`

// ---------------------------------------------------------------------------
// Facebook
//
// The link is an auth_identities row with provider 'facebook', the same
// (provider, subject) shape Google and Apple use. Only this package writes
// facebook rows, and nothing signs in with them: there is no Facebook
// sign-in, so removing the row can never lock anybody out.
// ---------------------------------------------------------------------------
func (q *Queries) FacebookOwner(ctx context.Context, providerSubject string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, facebookOwner, providerSubject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getFollow = `-- name: GetFollow :one
SELECT follower_id, followee_id, status, created_at, accepted_at FROM follows WHERE follower_id = $1 AND followee_id = $2
`

type GetFollowParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) GetFollow(ctx context.Context, arg GetFollowParams) (Follow, error) {
	row := q.db.QueryRow(ctx, getFollow, arg.FollowerID, arg.FolloweeID)
	var i Follow
	err := row.Scan(
		&i.FollowerID,
		&i.FolloweeID,
		&i.Status,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getHandle = `-- name: GetHandle :one
SELECT handle FROM users WHERE id = $1
`

func (q *Queries) GetHandle(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, getHandle, id)
	var handle *string
	err := row.Scan(&handle)
	return handle, err
}

const getPhone = `-- name: GetPhone :one

SELECT phone_e164, phone_verified_at FROM users WHERE id = $1
`

type GetPhoneRow struct {
	PhoneE164       *string
	PhoneVerifiedAt *time.Time
}

// ---------------------------------------------------------------------------
// Phone numbers
// ---------------------------------------------------------------------------
func (q *Queries) GetPhone(ctx context.Context, id uuid.UUID) (GetPhoneRow, error) {
	row := q.db.QueryRow(ctx, getPhone, id)
	var i GetPhoneRow
	err := row.Scan(&i.PhoneE164, &i.PhoneVerifiedAt)
	return i, err
}

const inviteByCode = `-- name: InviteByCode :one
SELECT i.code, i.inviter_id, i.channel, u.display_name, u.handle
FROM invites i JOIN users u ON u.id = i.inviter_id
WHERE i.code = $1
`

type InviteByCodeRow struct {
	Code        string
	InviterID   uuid.UUID
	Channel     string
	DisplayName string
	Handle      *string
}

func (q *Queries) InviteByCode(ctx context.Context, code string) (InviteByCodeRow, error) {
	row := q.db.QueryRow(ctx, inviteByCode, code)
	var i InviteByCodeRow
	err := row.Scan(
		&i.Code,
		&i.InviterID,
		&i.Channel,
		&i.DisplayName,
		&i.Handle,
	)
	return i, err
}

const inviteFor = `-- name: InviteFor :one
SELECT code, inviter_id, channel, created_at FROM invites WHERE inviter_id = $1 AND channel = $2
`

type InviteForParams struct {
	InviterID uuid.UUID
	Channel   string
}

func (q *Queries) InviteFor(ctx context.Context, arg InviteForParams) (Invite, error) {
	row := q.db.QueryRow(ctx, inviteFor, arg.InviterID, arg.Channel)
	var i Invite
	err := row.Scan(
		&i.Code,
		&i.InviterID,
		&i.Channel,
		&i.CreatedAt,
	)
	return i, err
}

const isBlockedEitherWay = `-- name: IsBlockedEitherWay :one
SELECT EXISTS (
    SELECT 1 FROM blocks
    WHERE (blocker_id = $1 AND blocked_id = $2) OR (blocker_id = $2 AND blocked_id = $1)
)
`

type IsBlockedEitherWayParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) IsBlockedEitherWay(ctx context.Context, arg IsBlockedEitherWayParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEitherWay, arg.BlockerID, arg.BlockedID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isFacebookConnected = `-- name: IsFacebookConnected :one
SELECT EXISTS (SELECT 1 FROM auth_identities WHERE user_id = $1 AND provider = 'facebook')
`

func (q *Queries) IsFacebookConnected(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isFacebookConnected, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const linkFacebook = `-- name: LinkFacebook :one
INSERT INTO auth_identities (user_id, provider, provider_subject)
VALUES ($1, 'facebook', $2)
ON CONFLICT (provider, provider_subject) DO NOTHING
RETURNING user_id
`

type LinkFacebookParams struct {
	UserID  uuid.UUID
	Subject string
}

// ON CONFLICT DO NOTHING returns no row when another account took the id
// first; the caller reads the owner again.
func (q *Queries) LinkFacebook(ctx context.Context, arg LinkFacebookParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, linkFacebook, arg.UserID, arg.Subject)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const listBlocked = `-- name: ListBlocked :many
SELECT u.id, u.display_name, u.handle
FROM blocks b JOIN users u ON u.id = b.blocked_id
WHERE b.blocker_id = $1
ORDER BY b.created_at DESC
`

type ListBlockedRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
}

func (q *Queries) ListBlocked(ctx context.Context, blockerID uuid.UUID) ([]ListBlockedRow, error) {
	rows, err := q.db.Query(ctx, listBlocked, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockedRow{}
	for rows.Next() {
		var i ListBlockedRow
		if err := rows.Scan(&i.ID, &i.DisplayName, &i.Handle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT u.id, u.display_name, u.handle, f.status, f.created_at
FROM follows f JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = $1
ORDER BY f.created_at DESC
`

type ListFollowersRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
	Status      string
	CreatedAt   time.Time
}

func (q *Queries) ListFollowers(ctx context.Context, followeeID uuid.UUID) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, followeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowersRow{}
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Handle,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowing = `-- name: ListFollowing :many
SELECT u.id, u.display_name, u.handle, f.status, f.created_at
FROM follows f JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = $1
ORDER BY f.created_at DESC
`

type ListFollowingRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
	Status      string
	CreatedAt   time.Time
}

func (q *Queries) ListFollowing(ctx context.Context, followerID uuid.UUID) ([]ListFollowingRow, error) {
	rows, err := q.db.Query(ctx, listFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFollowingRow{}
	for rows.Next() {
		var i ListFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Handle,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserForPhone = `-- name: LockUserForPhone :exec
SELECT 1 FROM users WHERE id = $1 FOR UPDATE
`

// Serialises one account's starts so two at once cannot both slip under
// the rate limit.
func (q *Queries) LockUserForPhone(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockUserForPhone, id)
	return err
}

const matchContactHashes = `-- name: MatchContactHashes :many
SELECT u.id, u.display_name, u.handle,
       COALESCE((SELECT f.status FROM follows f WHERE f.follower_id = $1 AND f.followee_id = u.id), '')::text AS following
FROM users u
WHERE u.handle IS NOT NULL
  AND u.id <> $1
  AND (encode(sha256(convert_to(lower(u.email::text), 'UTF8')), 'hex') = ANY($2::text[])
       OR (u.phone_verified_at IS NOT NULL
           AND encode(sha256(convert_to(u.phone_e164, 'UTF8')), 'hex') = ANY($3::text[])))
  AND NOT EXISTS (SELECT 1 FROM blocks b
                  WHERE (b.blocker_id = $1 AND b.blocked_id = u.id)
                     OR (b.blocker_id = u.id AND b.blocked_id = $1))
ORDER BY u.display_name
LIMIT 200
`

type MatchContactHashesParams struct {
	Viewer      uuid.UUID
	EmailHashes []string
	PhoneHashes []string
}

type MatchContactHashesRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
	Following   string
}

// People whose email, lower-cased, or verified phone number, E.164, hashes
// to one of the given SHA-256 hex strings. Only accounts with a handle:
// choosing one is choosing to be findable, which keeps this from answering
// "is this address on Khepri?" for somebody who never asked to be found. An
// unverified number matches nothing. Blocks hide either way.
func (q *Queries) MatchContactHashes(ctx context.Context, arg MatchContactHashesParams) ([]MatchContactHashesRow, error) {
	rows, err := q.db.Query(ctx, matchContactHashes, arg.Viewer, arg.EmailHashes, arg.PhoneHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchContactHashesRow{}
	for rows.Next() {
		var i MatchContactHashesRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Handle,
			&i.Following,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pendingPhoneVerification = `-- name: PendingPhoneVerification :one
SELECT id, user_id, phone_e164, attempts, created_at, closed_at FROM phone_verifications
WHERE user_id = $1 AND closed_at IS NULL AND created_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type PendingPhoneVerificationParams struct {
	UserID uuid.UUID
	Since  time.Time
}

func (q *Queries) PendingPhoneVerification(ctx context.Context, arg PendingPhoneVerificationParams) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, pendingPhoneVerification, arg.UserID, arg.Since)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PhoneE164,
		&i.Attempts,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const peopleByIDs = `-- name: PeopleByIDs :many
SELECT u.id, u.display_name, u.handle,
       COALESCE((SELECT f.status FROM follows f WHERE f.follower_id = $1 AND f.followee_id = u.id), '')::text AS following
FROM users u
WHERE u.id = ANY($2::uuid[])
  AND u.handle IS NOT NULL
  AND u.id <> $1
  AND NOT EXISTS (SELECT 1 FROM blocks b
                  WHERE (b.blocker_id = $1 AND b.blocked_id = u.id)
                     OR (b.blocker_id = u.id AND b.blocked_id = $1))
ORDER BY u.display_name
`

type PeopleByIDsParams struct {
	Viewer uuid.UUID
	Ids    []uuid.UUID
}

type PeopleByIDsRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
	Following   string
}

// The same filter again at read time: in the hour an import lives, somebody
// may clear their handle or block the viewer.
func (q *Queries) PeopleByIDs(ctx context.Context, arg PeopleByIDsParams) ([]PeopleByIDsRow, error) {
	rows, err := q.db.Query(ctx, peopleByIDs, arg.Viewer, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PeopleByIDsRow{}
	for rows.Next() {
		var i PeopleByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Handle,
			&i.Following,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const personByHandle = `-- name: PersonByHandle :one
SELECT id, display_name, handle FROM users WHERE handle = $1
`

type PersonByHandleRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
}

func (q *Queries) PersonByHandle(ctx context.Context, handle *string) (PersonByHandleRow, error) {
	row := q.db.QueryRow(ctx, personByHandle, handle)
	var i PersonByHandleRow
	err := row.Scan(&i.ID, &i.DisplayName, &i.Handle)
	return i, err
}

const personByID = `-- name: PersonByID :one
SELECT id, display_name, handle FROM users WHERE id = $1
`

type PersonByIDRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
}

func (q *Queries) PersonByID(ctx context.Context, id uuid.UUID) (PersonByIDRow, error) {
	row := q.db.QueryRow(ctx, personByID, id)
	var i PersonByIDRow
	err := row.Scan(&i.ID, &i.DisplayName, &i.Handle)
	return i, err
}

const prunePhoneVerifications = `-- name: PrunePhoneVerifications :exec
DELETE FROM phone_verifications WHERE created_at < $1
`

func (q *Queries) PrunePhoneVerifications(ctx context.Context, before time.Time) error {
	_, err := q.db.Exec(ctx, prunePhoneVerifications, before)
	return err
}

const redeem = `-- name: Redeem :one
INSERT INTO invite_redemptions (invitee_id, code)
VALUES ($1, $2)
ON CONFLICT (invitee_id) DO NOTHING
RETURNING redeemed_at
`

type RedeemParams struct {
	InviteeID uuid.UUID
	Code      string
}

// The insert is the claim: one invite per new account, the first one wins.
func (q *Queries) Redeem(ctx context.Context, arg RedeemParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, redeem, arg.InviteeID, arg.Code)
	var redeemed_at time.Time
	err := row.Scan(&redeemed_at)
	return redeemed_at, err
}

const releasePhone = `-- name: ReleasePhone :exec
UPDATE users SET phone_e164 = NULL, phone_verified_at = NULL, updated_at = now()
WHERE phone_e164 = $1 AND id <> $2
`

type ReleasePhoneParams struct {
	Phone  *string
	Keeper uuid.UUID
}

// The number leaves any other account that held it: the latest account to
// prove possession wins.
func (q *Queries) ReleasePhone(ctx context.Context, arg ReleasePhoneParams) error {
	_, err := q.db.Exec(ctx, releasePhone, arg.Phone, arg.Keeper)
	return err
}

const saveFacebookImport = `-- name: SaveFacebookImport :exec
INSERT INTO facebook_imports (user_id, people, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET people = EXCLUDED.people, imported_at = now(), expires_at = EXCLUDED.expires_at
`

type SaveFacebookImportParams struct {
	UserID    uuid.UUID
	People    []uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) SaveFacebookImport(ctx context.Context, arg SaveFacebookImportParams) error {
	_, err := q.db.Exec(ctx, saveFacebookImport, arg.UserID, arg.People, arg.ExpiresAt)
	return err
}

const setHandle = `-- name: SetHandle :one
UPDATE users SET handle = $2, updated_at = now()
WHERE id = $1
RETURNING handle
`

type SetHandleParams struct {
	ID     uuid.UUID
	Handle *string
}

func (q *Queries) SetHandle(ctx context.Context, arg SetHandleParams) (*string, error) {
	row := q.db.QueryRow(ctx, setHandle, arg.ID, arg.Handle)
	var handle *string
	err := row.Scan(&handle)
	return handle, err
}

const setPhone = `-- name: SetPhone :exec
UPDATE users SET phone_e164 = $2, phone_verified_at = now(), updated_at = now()
WHERE id = $1
`

type SetPhoneParams struct {
	ID    uuid.UUID
	Phone *string
}

func (q *Queries) SetPhone(ctx context.Context, arg SetPhoneParams) error {
	_, err := q.db.Exec(ctx, setPhone, arg.ID, arg.Phone)
	return err
}

const takeFacebookOAuthState = `-- name: TakeFacebookOAuthState :one
DELETE FROM facebook_oauth_states
WHERE state_hash = $1 AND expires_at > now()
RETURNING user_id
`

// Single use: the row is gone whether or not the connection then succeeds.
func (q *Queries) TakeFacebookOAuthState(ctx context.Context, stateHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, takeFacebookOAuthState, stateHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const unblock = `-- name: Unblock :execrows
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockParams struct {
	BlockerID uuid.UUID
	BlockedID uuid.UUID
}

func (q *Queries) Unblock(ctx context.Context, arg UnblockParams) (int64, error) {
	result, err := q.db.Exec(ctx, unblock, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkFacebook = `-- name: UnlinkFacebook :exec
DELETE FROM auth_identities WHERE user_id = $1 AND provider = 'facebook'
`

func (q *Queries) UnlinkFacebook(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkFacebook, userID)
	return err
}

const upsertFollow = `-- name: UpsertFollow :one
INSERT INTO follows (follower_id, followee_id, status, accepted_at)
VALUES ($1, $2, $3, CASE WHEN $3::text = 'accepted' THEN now() END)
ON CONFLICT (follower_id, followee_id) DO UPDATE
SET status      = CASE WHEN follows.status = 'accepted' OR EXCLUDED.status = 'accepted' THEN 'accepted' ELSE 'pending' END,
    accepted_at = COALESCE(follows.accepted_at, EXCLUDED.accepted_at)
RETURNING follower_id, followee_id, status, created_at, accepted_at
`

type UpsertFollowParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	Status     string
}

// A follow request stays pending until accepted; asking again changes
// nothing, and an accepted follow is never demoted back to pending.
func (q *Queries) UpsertFollow(ctx context.Context, arg UpsertFollowParams) (Follow, error) {
	row := q.db.QueryRow(ctx, upsertFollow, arg.FollowerID, arg.FolloweeID, arg.Status)
	var i Follow
	err := row.Scan(
		&i.FollowerID,
		&i.FolloweeID,
		&i.Status,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}
