// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package achievementsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const feed = `-- name: Feed :many
SELECT a.id, a.user_id, a.category, a.kind, a.title, a.detail, a.occurred_at,
       u.display_name, u.handle,
       (SELECT count(*) FROM kudos k WHERE k.achievement_id = a.id) AS kudos,
       EXISTS (SELECT 1 FROM kudos k WHERE k.achievement_id = a.id AND k.user_id = $1) AS kudoed
FROM achievements a
JOIN users u ON u.id = a.user_id
WHERE a.occurred_at < $2
  AND (
    a.user_id = $1
    OR (
      EXISTS (SELECT 1 FROM follows f
              WHERE f.follower_id = $1 AND f.followee_id = a.user_id AND f.status = 'accepted')
      AND EXISTS (SELECT 1 FROM achievement_sharing s
                  WHERE s.user_id = a.user_id AND s.category = a.category AND s.shared)
      AND NOT EXISTS (SELECT 1 FROM blocks b
                      WHERE (b.blocker_id = $1 AND b.blocked_id = a.user_id)
                         OR (b.blocker_id = a.user_id AND b.blocked_id = $1))
    )
  )
ORDER BY a.occurred_at DESC
LIMIT $3
`

type FeedParams struct {
	Viewer uuid.UUID
	Before time.Time
	Lim    int32
}

type FeedRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Category    string
	Kind        string
	Title       string
	Detail      string
	OccurredAt  time.Time
	DisplayName string
	Handle      *string
	Kudos       int64
	Kudoed      bool
}

// Your own achievements, and those of people you follow (accepted) in the
// categories they share, minus anybody blocked either way. Newest first,
// before a cursor.
func (q *Queries) Feed(ctx context.Context, arg FeedParams) ([]FeedRow, error) {
	rows, err := q.db.Query(ctx, feed, arg.Viewer, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FeedRow{}
	for rows.Next() {
		var i FeedRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Kind,
			&i.Title,
			&i.Detail,
			&i.OccurredAt,
			&i.DisplayName,
			&i.Handle,
			&i.Kudos,
			&i.Kudoed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const giveKudos = `-- name: GiveKudos :execrows
INSERT INTO kudos (achievement_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type GiveKudosParams struct {
	AchievementID uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) GiveKudos(ctx context.Context, arg GiveKudosParams) (int64, error) {
	result, err := q.db.Exec(ctx, giveKudos, arg.AchievementID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSharing = `-- name: ListSharing :many
SELECT category, shared FROM achievement_sharing WHERE user_id = $1
`

type ListSharingRow struct {
	Category string
	Shared   bool
}

func (q *Queries) ListSharing(ctx context.Context, userID uuid.UUID) ([]ListSharingRow, error) {
	rows, err := q.db.Query(ctx, listSharing, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSharingRow{}
	for rows.Next() {
		var i ListSharingRow
		if err := rows.Scan(&i.Category, &i.Shared); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownAchievements = `-- name: OwnAchievements :many
SELECT id, category, kind, title, detail, occurred_at FROM achievements
WHERE user_id = $1 ORDER BY occurred_at DESC
`

type OwnAchievementsRow struct {
	ID         uuid.UUID
	Category   string
	Kind       string
	Title      string
	Detail     string
	OccurredAt time.Time
}

func (q *Queries) OwnAchievements(ctx context.Context, userID uuid.UUID) ([]OwnAchievementsRow, error) {
	rows, err := q.db.Query(ctx, ownAchievements, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OwnAchievementsRow{}
	for rows.Next() {
		var i OwnAchievementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Kind,
			&i.Title,
			&i.Detail,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const record = `-- name: Record :one
INSERT INTO achievements (user_id, category, kind, title, detail, occurred_at, source_key)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, kind, source_key) DO NOTHING
RETURNING id
`

type RecordParams struct {
	UserID     uuid.UUID
	Category   string
	Kind       string
	Title      string
	Detail     string
	OccurredAt time.Time
	SourceKey  string
}

// The unique key is the dedupe: the same moment recorded twice is one row.
func (q *Queries) Record(ctx context.Context, arg RecordParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, record,
		arg.UserID,
		arg.Category,
		arg.Kind,
		arg.Title,
		arg.Detail,
		arg.OccurredAt,
		arg.SourceKey,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const setSharing = `-- name: SetSharing :exec
INSERT INTO achievement_sharing (user_id, category, shared)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, category) DO UPDATE SET shared = EXCLUDED.shared
`

type SetSharingParams struct {
	UserID   uuid.UUID
	Category string
	Shared   bool
}

func (q *Queries) SetSharing(ctx context.Context, arg SetSharingParams) error {
	_, err := q.db.Exec(ctx, setSharing, arg.UserID, arg.Category, arg.Shared)
	return err
}

const takeKudos = `-- name: TakeKudos :exec
DELETE FROM kudos WHERE achievement_id = $1 AND user_id = $2
`

type TakeKudosParams struct {
	AchievementID uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) TakeKudos(ctx context.Context, arg TakeKudosParams) error {
	_, err := q.db.Exec(ctx, takeKudos, arg.AchievementID, arg.UserID)
	return err
}

const visible = `-- name: Visible :one
SELECT a.user_id, a.title FROM achievements a
WHERE a.id = $1
  AND (
    a.user_id = $2
    OR (
      EXISTS (SELECT 1 FROM follows f
              WHERE f.follower_id = $2 AND f.followee_id = a.user_id AND f.status = 'accepted')
      AND EXISTS (SELECT 1 FROM achievement_sharing s
                  WHERE s.user_id = a.user_id AND s.category = a.category AND s.shared)
      AND NOT EXISTS (SELECT 1 FROM blocks b
                      WHERE (b.blocker_id = $2 AND b.blocked_id = a.user_id)
                         OR (b.blocker_id = a.user_id AND b.blocked_id = $2))
    )
  )
`

type VisibleParams struct {
	ID     uuid.UUID
	Viewer uuid.UUID
}

type VisibleRow struct {
	UserID uuid.UUID
	Title  string
}

// Whether the viewer may see (and so give kudos to) one achievement, by the
// same rule as the feed; returns its owner and title for the notification.
func (q *Queries) Visible(ctx context.Context, arg VisibleParams) (VisibleRow, error) {
	row := q.db.QueryRow(ctx, visible, arg.ID, arg.Viewer)
	var i VisibleRow
	err := row.Scan(&i.UserID, &i.Title)
	return i, err
}
