// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package goalsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addGoalUpdate = `-- name: AddGoalUpdate :one
INSERT INTO goal_updates (goal_id, user_id, note, progress)
VALUES ($1, $2, $3, $4)
RETURNING id, goal_id, user_id, note, progress, created_at
`

type AddGoalUpdateParams struct {
	GoalID   uuid.UUID
	UserID   uuid.UUID
	Note     string
	Progress *int16
}

func (q *Queries) AddGoalUpdate(ctx context.Context, arg AddGoalUpdateParams) (GoalUpdate, error) {
	row := q.db.QueryRow(ctx, addGoalUpdate,
		arg.GoalID,
		arg.UserID,
		arg.Note,
		arg.Progress,
	)
	var i GoalUpdate
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Note,
		&i.Progress,
		&i.CreatedAt,
	)
	return i, err
}

const countOverdueMilestones = `-- name: CountOverdueMilestones :one
SELECT COUNT(*)::int
FROM goal_milestones m
INNER JOIN goals g ON g.id = m.goal_id AND g.user_id = m.user_id
WHERE m.user_id = $1
  AND g.status = 'active'
  AND m.status = 'open'
  AND m.target_date IS NOT NULL
  AND m.target_date < CURRENT_DATE
`

// Open checkpoints on active goals whose date has passed.
func (q *Queries) CountOverdueMilestones(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOverdueMilestones, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (user_id, title, motivation, success, category, target_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, motivation, success, category, status, target_date, created_at, updated_at, closed_at
`

type CreateGoalParams struct {
	UserID     uuid.UUID
	Title      string
	Motivation string
	Success    string
	Category   string
	TargetDate pgtype.Date
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Title,
		arg.Motivation,
		arg.Success,
		arg.Category,
		arg.TargetDate,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Motivation,
		&i.Success,
		&i.Category,
		&i.Status,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO goal_milestones (goal_id, user_id, title, target_date, position)
VALUES (
    $1, $2, $3, $4,
    (SELECT COALESCE(MAX(position), -1) + 1 FROM goal_milestones WHERE goal_id = $1)
)
RETURNING id, goal_id, user_id, title, status, position, target_date, completed_at, created_at, updated_at
`

type CreateMilestoneParams struct {
	GoalID     uuid.UUID
	UserID     uuid.UUID
	Title      string
	TargetDate pgtype.Date
}

// Position is MAX+1 for this goal so appends stay stable without a round trip.
func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (GoalMilestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.GoalID,
		arg.UserID,
		arg.Title,
		arg.TargetDate,
	)
	var i GoalMilestone
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.TargetDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals WHERE id = $1 AND user_id = $2
`

type DeleteGoalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteGoal(ctx context.Context, arg DeleteGoalParams) error {
	_, err := q.db.Exec(ctx, deleteGoal, arg.ID, arg.UserID)
	return err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM goal_milestones WHERE id = $1 AND user_id = $2
`

type DeleteMilestoneParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMilestone(ctx context.Context, arg DeleteMilestoneParams) error {
	_, err := q.db.Exec(ctx, deleteMilestone, arg.ID, arg.UserID)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT id, user_id, title, motivation, success, category, status, target_date, created_at, updated_at, closed_at FROM goals WHERE id = $1 AND user_id = $2
`

type GetGoalParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetGoal(ctx context.Context, arg GetGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoal, arg.ID, arg.UserID)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Motivation,
		&i.Success,
		&i.Category,
		&i.Status,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, goal_id, user_id, title, status, position, target_date, completed_at, created_at, updated_at FROM goal_milestones WHERE id = $1 AND user_id = $2
`

type GetMilestoneParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMilestone(ctx context.Context, arg GetMilestoneParams) (GoalMilestone, error) {
	row := q.db.QueryRow(ctx, getMilestone, arg.ID, arg.UserID)
	var i GoalMilestone
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.TargetDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestGoalUpdates = `-- name: LatestGoalUpdates :many
SELECT DISTINCT ON (goal_id) id, goal_id, user_id, note, progress, created_at
FROM goal_updates
WHERE user_id = $1
ORDER BY goal_id, created_at DESC
`

// The most recent note per goal, for the coach's context and the goal list.
func (q *Queries) LatestGoalUpdates(ctx context.Context, userID uuid.UUID) ([]GoalUpdate, error) {
	rows, err := q.db.Query(ctx, latestGoalUpdates, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoalUpdate{}
	for rows.Next() {
		var i GoalUpdate
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.Note,
			&i.Progress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGoals = `-- name: ListActiveGoals :many
SELECT id, user_id, title, motivation, success, category, status, target_date, created_at, updated_at, closed_at FROM goals
WHERE user_id = $1 AND status = 'active'
ORDER BY
    -- Goals with a deadline surface first, soonest first; open-ended goals
    -- follow. NULLS LAST is the whole point: a goal with no date is not urgent.
    target_date ASC NULLS LAST,
    created_at DESC
LIMIT $2
`

type ListActiveGoalsParams struct {
	UserID uuid.UUID
	Limit  int32
}

// Loaded on every coach message, so it is deliberately narrow.
func (q *Queries) ListActiveGoals(ctx context.Context, arg ListActiveGoalsParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listActiveGoals, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Motivation,
			&i.Success,
			&i.Category,
			&i.Status,
			&i.TargetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalUpdates = `-- name: ListGoalUpdates :many
SELECT id, goal_id, user_id, note, progress, created_at FROM goal_updates
WHERE goal_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListGoalUpdatesParams struct {
	GoalID uuid.UUID
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListGoalUpdates(ctx context.Context, arg ListGoalUpdatesParams) ([]GoalUpdate, error) {
	rows, err := q.db.Query(ctx, listGoalUpdates, arg.GoalID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoalUpdate{}
	for rows.Next() {
		var i GoalUpdate
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.Note,
			&i.Progress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalUpdatesBetween = `-- name: ListGoalUpdatesBetween :many
SELECT u.id, u.goal_id, u.user_id, u.note, u.progress, u.created_at, g.title AS goal_title
FROM goal_updates u
JOIN goals g ON g.id = u.goal_id
WHERE u.user_id = $1 AND u.created_at >= $2 AND u.created_at < $3
ORDER BY u.created_at DESC
`

type ListGoalUpdatesBetweenParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

type ListGoalUpdatesBetweenRow struct {
	ID        uuid.UUID
	GoalID    uuid.UUID
	UserID    uuid.UUID
	Note      string
	Progress  *int16
	CreatedAt time.Time
	GoalTitle string
}

// Every note across every goal in a window, for the activity timeline. Joins
// the title in so the feed can name the goal without a second round trip.
func (q *Queries) ListGoalUpdatesBetween(ctx context.Context, arg ListGoalUpdatesBetweenParams) ([]ListGoalUpdatesBetweenRow, error) {
	rows, err := q.db.Query(ctx, listGoalUpdatesBetween, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalUpdatesBetweenRow{}
	for rows.Next() {
		var i ListGoalUpdatesBetweenRow
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.Note,
			&i.Progress,
			&i.CreatedAt,
			&i.GoalTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoals = `-- name: ListGoals :many
SELECT id, user_id, title, motivation, success, category, status, target_date, created_at, updated_at, closed_at FROM goals
WHERE user_id = $1
ORDER BY (status = 'active') DESC, created_at DESC
LIMIT $2
`

type ListGoalsParams struct {
	UserID uuid.UUID
	Limit  int32
}

// Active first, then everything else, because the active ones are what the
// person is actually doing.
func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Motivation,
			&i.Success,
			&i.Category,
			&i.Status,
			&i.TargetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsCreatedBetween = `-- name: ListGoalsCreatedBetween :many
SELECT id, user_id, title, motivation, success, category, status, target_date, created_at, updated_at, closed_at FROM goals
WHERE user_id = $1 AND created_at >= $2 AND created_at < $3
ORDER BY created_at DESC
`

type ListGoalsCreatedBetweenParams struct {
	UserID      uuid.UUID
	CreatedAt   time.Time
	CreatedAt_2 time.Time
}

func (q *Queries) ListGoalsCreatedBetween(ctx context.Context, arg ListGoalsCreatedBetweenParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsCreatedBetween, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Motivation,
			&i.Success,
			&i.Category,
			&i.Status,
			&i.TargetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestones = `-- name: ListMilestones :many
SELECT id, goal_id, user_id, title, status, position, target_date, completed_at, created_at, updated_at FROM goal_milestones
WHERE goal_id = $1 AND user_id = $2
ORDER BY position ASC, created_at ASC
`

type ListMilestonesParams struct {
	GoalID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ListMilestones(ctx context.Context, arg ListMilestonesParams) ([]GoalMilestone, error) {
	rows, err := q.db.Query(ctx, listMilestones, arg.GoalID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GoalMilestone{}
	for rows.Next() {
		var i GoalMilestone
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.UserID,
			&i.Title,
			&i.Status,
			&i.Position,
			&i.TargetDate,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const milestoneCounts = `-- name: MilestoneCounts :many
SELECT goal_id,
       COUNT(*)::int AS total,
       COUNT(*) FILTER (WHERE status = 'completed')::int AS completed
FROM goal_milestones
WHERE user_id = $1
GROUP BY goal_id
`

type MilestoneCountsRow struct {
	GoalID    uuid.UUID
	Total     int32
	Completed int32
}

// One row per goal that has any milestones, for the list and the coach.
func (q *Queries) MilestoneCounts(ctx context.Context, userID uuid.UUID) ([]MilestoneCountsRow, error) {
	rows, err := q.db.Query(ctx, milestoneCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MilestoneCountsRow{}
	for rows.Next() {
		var i MilestoneCountsRow
		if err := rows.Scan(&i.GoalID, &i.Total, &i.Completed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGoalStatus = `-- name: SetGoalStatus :one
UPDATE goals
SET status     = $3,
    -- Stamped when the goal leaves 'active' and cleared if it comes back, so
    -- reopening a goal does not leave it looking finished.
    closed_at  = CASE WHEN $3::text = 'active' THEN NULL ELSE now() END,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, motivation, success, category, status, target_date, created_at, updated_at, closed_at
`

type SetGoalStatusParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Status string
}

func (q *Queries) SetGoalStatus(ctx context.Context, arg SetGoalStatusParams) (Goal, error) {
	row := q.db.QueryRow(ctx, setGoalStatus, arg.ID, arg.UserID, arg.Status)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Motivation,
		&i.Success,
		&i.Category,
		&i.Status,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const setMilestoneStatus = `-- name: SetMilestoneStatus :one
UPDATE goal_milestones
SET status       = $3,
    -- Stamped when it is completed and cleared if it is reopened, so a
    -- reopened checkpoint does not still look finished.
    completed_at = CASE WHEN $3::text = 'completed' THEN now() ELSE NULL END,
    updated_at   = now()
WHERE id = $1 AND user_id = $2
RETURNING id, goal_id, user_id, title, status, position, target_date, completed_at, created_at, updated_at
`

type SetMilestoneStatusParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Status string
}

func (q *Queries) SetMilestoneStatus(ctx context.Context, arg SetMilestoneStatusParams) (GoalMilestone, error) {
	row := q.db.QueryRow(ctx, setMilestoneStatus, arg.ID, arg.UserID, arg.Status)
	var i GoalMilestone
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.TargetDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET title       = $3,
    motivation  = $4,
    success     = $5,
    category    = $6,
    target_date = $7,
    updated_at  = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, motivation, success, category, status, target_date, created_at, updated_at, closed_at
`

type UpdateGoalParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Title      string
	Motivation string
	Success    string
	Category   string
	TargetDate pgtype.Date
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Motivation,
		arg.Success,
		arg.Category,
		arg.TargetDate,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Motivation,
		&i.Success,
		&i.Category,
		&i.Status,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE goal_milestones
SET title       = $3,
    target_date = $4,
    updated_at  = now()
WHERE id = $1 AND user_id = $2
RETURNING id, goal_id, user_id, title, status, position, target_date, completed_at, created_at, updated_at
`

type UpdateMilestoneParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Title      string
	TargetDate pgtype.Date
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (GoalMilestone, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.TargetDate,
	)
	var i GoalMilestone
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Position,
		&i.TargetDate,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
