// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package activitydb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activeActivitySession = `-- name: ActiveActivitySession :one
SELECT id, user_id, activity_code, source, status, weight_kg_snapshot, started_at, paused_at, total_paused_seconds, ended_at, calories_burned, external_id, created_at, updated_at FROM activity_sessions WHERE user_id = $1 AND status IN ('active', 'paused')
`

func (q *Queries) ActiveActivitySession(ctx context.Context, userID uuid.UUID) (ActivitySession, error) {
	row := q.db.QueryRow(ctx, activeActivitySession, userID)
	var i ActivitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityCode,
		&i.Source,
		&i.Status,
		&i.WeightKgSnapshot,
		&i.StartedAt,
		&i.PausedAt,
		&i.TotalPausedSeconds,
		&i.EndedAt,
		&i.CaloriesBurned,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelActivitySession = `-- name: CancelActivitySession :exec
UPDATE activity_sessions
SET status = 'cancelled', ended_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2
`

type CancelActivitySessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) CancelActivitySession(ctx context.Context, arg CancelActivitySessionParams) error {
	_, err := q.db.Exec(ctx, cancelActivitySession, arg.ID, arg.UserID)
	return err
}

const completeActivitySession = `-- name: CompleteActivitySession :one
UPDATE activity_sessions
SET status = 'completed', ended_at = $3, calories_burned = $4, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, activity_code, source, status, weight_kg_snapshot, started_at, paused_at, total_paused_seconds, ended_at, calories_burned, external_id, created_at, updated_at
`

type CompleteActivitySessionParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	EndedAt        *time.Time
	CaloriesBurned *float64
}

func (q *Queries) CompleteActivitySession(ctx context.Context, arg CompleteActivitySessionParams) (ActivitySession, error) {
	row := q.db.QueryRow(ctx, completeActivitySession,
		arg.ID,
		arg.UserID,
		arg.EndedAt,
		arg.CaloriesBurned,
	)
	var i ActivitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityCode,
		&i.Source,
		&i.Status,
		&i.WeightKgSnapshot,
		&i.StartedAt,
		&i.PausedAt,
		&i.TotalPausedSeconds,
		&i.EndedAt,
		&i.CaloriesBurned,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createActivitySession = `-- name: CreateActivitySession :one
INSERT INTO activity_sessions (user_id, activity_code, weight_kg_snapshot)
VALUES ($1, $2, $3)
RETURNING id, user_id, activity_code, source, status, weight_kg_snapshot, started_at, paused_at, total_paused_seconds, ended_at, calories_burned, external_id, created_at, updated_at
`

type CreateActivitySessionParams struct {
	UserID           uuid.UUID
	ActivityCode     string
	WeightKgSnapshot float64
}

func (q *Queries) CreateActivitySession(ctx context.Context, arg CreateActivitySessionParams) (ActivitySession, error) {
	row := q.db.QueryRow(ctx, createActivitySession, arg.UserID, arg.ActivityCode, arg.WeightKgSnapshot)
	var i ActivitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityCode,
		&i.Source,
		&i.Status,
		&i.WeightKgSnapshot,
		&i.StartedAt,
		&i.PausedAt,
		&i.TotalPausedSeconds,
		&i.EndedAt,
		&i.CaloriesBurned,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivitySession = `-- name: GetActivitySession :one
SELECT id, user_id, activity_code, source, status, weight_kg_snapshot, started_at, paused_at, total_paused_seconds, ended_at, calories_burned, external_id, created_at, updated_at FROM activity_sessions WHERE id = $1 AND user_id = $2
`

type GetActivitySessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetActivitySession(ctx context.Context, arg GetActivitySessionParams) (ActivitySession, error) {
	row := q.db.QueryRow(ctx, getActivitySession, arg.ID, arg.UserID)
	var i ActivitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityCode,
		&i.Source,
		&i.Status,
		&i.WeightKgSnapshot,
		&i.StartedAt,
		&i.PausedAt,
		&i.TotalPausedSeconds,
		&i.EndedAt,
		&i.CaloriesBurned,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivitySessions = `-- name: ListActivitySessions :many
SELECT id, user_id, activity_code, source, status, weight_kg_snapshot, started_at, paused_at, total_paused_seconds, ended_at, calories_burned, external_id, created_at, updated_at FROM activity_sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListActivitySessionsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListActivitySessions(ctx context.Context, arg ListActivitySessionsParams) ([]ActivitySession, error) {
	rows, err := q.db.Query(ctx, listActivitySessions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivitySession{}
	for rows.Next() {
		var i ActivitySession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ActivityCode,
			&i.Source,
			&i.Status,
			&i.WeightKgSnapshot,
			&i.StartedAt,
			&i.PausedAt,
			&i.TotalPausedSeconds,
			&i.EndedAt,
			&i.CaloriesBurned,
			&i.ExternalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseActivitySession = `-- name: PauseActivitySession :one
UPDATE activity_sessions
SET status = 'paused', paused_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, activity_code, source, status, weight_kg_snapshot, started_at, paused_at, total_paused_seconds, ended_at, calories_burned, external_id, created_at, updated_at
`

type PauseActivitySessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) PauseActivitySession(ctx context.Context, arg PauseActivitySessionParams) (ActivitySession, error) {
	row := q.db.QueryRow(ctx, pauseActivitySession, arg.ID, arg.UserID)
	var i ActivitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityCode,
		&i.Source,
		&i.Status,
		&i.WeightKgSnapshot,
		&i.StartedAt,
		&i.PausedAt,
		&i.TotalPausedSeconds,
		&i.EndedAt,
		&i.CaloriesBurned,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resumeActivitySession = `-- name: ResumeActivitySession :one
UPDATE activity_sessions
SET status = 'active', paused_at = NULL, total_paused_seconds = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, activity_code, source, status, weight_kg_snapshot, started_at, paused_at, total_paused_seconds, ended_at, calories_burned, external_id, created_at, updated_at
`

type ResumeActivitySessionParams struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	TotalPausedSeconds int32
}

func (q *Queries) ResumeActivitySession(ctx context.Context, arg ResumeActivitySessionParams) (ActivitySession, error) {
	row := q.db.QueryRow(ctx, resumeActivitySession, arg.ID, arg.UserID, arg.TotalPausedSeconds)
	var i ActivitySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ActivityCode,
		&i.Source,
		&i.Status,
		&i.WeightKgSnapshot,
		&i.StartedAt,
		&i.PausedAt,
		&i.TotalPausedSeconds,
		&i.EndedAt,
		&i.CaloriesBurned,
		&i.ExternalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumActivityCaloriesSince = `-- name: SumActivityCaloriesSince :one
SELECT COALESCE(SUM(calories_burned), 0)::double precision AS total
FROM activity_sessions
WHERE user_id = $1 AND status = 'completed' AND ended_at >= $2
`

type SumActivityCaloriesSinceParams struct {
	UserID  uuid.UUID
	EndedAt *time.Time
}

func (q *Queries) SumActivityCaloriesSince(ctx context.Context, arg SumActivityCaloriesSinceParams) (float64, error) {
	row := q.db.QueryRow(ctx, sumActivityCaloriesSince, arg.UserID, arg.EndedAt)
	var total float64
	err := row.Scan(&total)
	return total, err
}
