// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package weeklydb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type WeeklyFocus struct {
	UserID     uuid.UUID
	WeekStart  pgtype.Date
	Priorities []string
	Volume     string
	ReviewedAt time.Time
}
