// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package weeklydb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFocus = `-- name: GetFocus :one
SELECT user_id, week_start, priorities, volume, reviewed_at FROM weekly_focus WHERE user_id = $1 AND week_start = $2
`

type GetFocusParams struct {
	UserID    uuid.UUID
	WeekStart pgtype.Date
}

func (q *Queries) GetFocus(ctx context.Context, arg GetFocusParams) (WeeklyFocus, error) {
	row := q.db.QueryRow(ctx, getFocus, arg.UserID, arg.WeekStart)
	var i WeeklyFocus
	err := row.Scan(
		&i.UserID,
		&i.WeekStart,
		&i.Priorities,
		&i.Volume,
		&i.ReviewedAt,
	)
	return i, err
}

const upsertFocus = `-- name: UpsertFocus :one
INSERT INTO weekly_focus (user_id, week_start, priorities, volume)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, week_start) DO UPDATE
SET priorities = EXCLUDED.priorities, volume = EXCLUDED.volume, reviewed_at = now()
RETURNING user_id, week_start, priorities, volume, reviewed_at
`

type UpsertFocusParams struct {
	UserID     uuid.UUID
	WeekStart  pgtype.Date
	Priorities []string
	Volume     string
}

func (q *Queries) UpsertFocus(ctx context.Context, arg UpsertFocusParams) (WeeklyFocus, error) {
	row := q.db.QueryRow(ctx, upsertFocus,
		arg.UserID,
		arg.WeekStart,
		arg.Priorities,
		arg.Volume,
	)
	var i WeeklyFocus
	err := row.Scan(
		&i.UserID,
		&i.WeekStart,
		&i.Priorities,
		&i.Volume,
		&i.ReviewedAt,
	)
	return i, err
}
