// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package daydb

import (
	"context"

	"github.com/google/uuid"
)

const deleteDayRule = `-- name: DeleteDayRule :exec
DELETE FROM day_rules WHERE user_id = $1 AND kind = $2
`

type DeleteDayRuleParams struct {
	UserID uuid.UUID
	Kind   string
}

func (q *Queries) DeleteDayRule(ctx context.Context, arg DeleteDayRuleParams) error {
	_, err := q.db.Exec(ctx, deleteDayRule, arg.UserID, arg.Kind)
	return err
}

const listDayRules = `-- name: ListDayRules :many
SELECT user_id, kind, at_time, enabled, updated_at FROM day_rules
WHERE user_id = $1
ORDER BY at_time, kind
`

func (q *Queries) ListDayRules(ctx context.Context, userID uuid.UUID) ([]DayRule, error) {
	rows, err := q.db.Query(ctx, listDayRules, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DayRule{}
	for rows.Next() {
		var i DayRule
		if err := rows.Scan(
			&i.UserID,
			&i.Kind,
			&i.AtTime,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDayRule = `-- name: UpsertDayRule :one
INSERT INTO day_rules (user_id, kind, at_time, enabled)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, kind) DO UPDATE
SET at_time = EXCLUDED.at_time, enabled = EXCLUDED.enabled, updated_at = now()
RETURNING user_id, kind, at_time, enabled, updated_at
`

type UpsertDayRuleParams struct {
	UserID  uuid.UUID
	Kind    string
	AtTime  string
	Enabled bool
}

func (q *Queries) UpsertDayRule(ctx context.Context, arg UpsertDayRuleParams) (DayRule, error) {
	row := q.db.QueryRow(ctx, upsertDayRule,
		arg.UserID,
		arg.Kind,
		arg.AtTime,
		arg.Enabled,
	)
	var i DayRule
	err := row.Scan(
		&i.UserID,
		&i.Kind,
		&i.AtTime,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}
