// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package notificationsdb

import (
	"time"

	"github.com/google/uuid"
)

type UserNotificationPref struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	NudgeMissedCheckin bool
	NudgeGoalDeadline  bool
	WeeklyReportAuto   bool
	QuietHoursEnabled  bool
	QuietStart         string
	QuietEnd           string
	UpdatedAt          time.Time
	DailyBriefingAuto  bool
}
