// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package decisionsdb

import (
	"context"

	"github.com/google/uuid"
)

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (user_id, title, options, rationale, outcome)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, options, rationale, outcome, decided_at, created_at, updated_at
`

type CreateDecisionParams struct {
	UserID    uuid.UUID
	Title     string
	Options   string
	Rationale string
	Outcome   string
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.UserID,
		arg.Title,
		arg.Options,
		arg.Rationale,
		arg.Outcome,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Options,
		&i.Rationale,
		&i.Outcome,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDecision = `-- name: DeleteDecision :execrows
DELETE FROM decisions WHERE id = $1 AND user_id = $2
`

type DeleteDecisionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDecision(ctx context.Context, arg DeleteDecisionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDecision, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDecision = `-- name: GetDecision :one
SELECT id, user_id, title, options, rationale, outcome, decided_at, created_at, updated_at FROM decisions WHERE id = $1 AND user_id = $2
`

type GetDecisionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDecision(ctx context.Context, arg GetDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, getDecision, arg.ID, arg.UserID)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Options,
		&i.Rationale,
		&i.Outcome,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, user_id, title, options, rationale, outcome, decided_at, created_at, updated_at FROM decisions
WHERE user_id = $1
ORDER BY decided_at DESC, created_at DESC
LIMIT $2
`

type ListDecisionsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListDecisions(ctx context.Context, arg ListDecisionsParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Decision{}
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Options,
			&i.Rationale,
			&i.Outcome,
			&i.DecidedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDecision = `-- name: UpdateDecision :one
UPDATE decisions
SET title      = $3,
    options    = $4,
    rationale  = $5,
    outcome    = $6,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, title, options, rationale, outcome, decided_at, created_at, updated_at
`

type UpdateDecisionParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Options   string
	Rationale string
	Outcome   string
}

func (q *Queries) UpdateDecision(ctx context.Context, arg UpdateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, updateDecision,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Options,
		arg.Rationale,
		arg.Outcome,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Options,
		&i.Rationale,
		&i.Outcome,
		&i.DecidedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
