// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package checkinsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCheckIn = `-- name: DeleteCheckIn :execrows
DELETE FROM check_ins WHERE id = $1 AND user_id = $2
`

type DeleteCheckInParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCheckIn(ctx context.Context, arg DeleteCheckInParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheckIn, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCheckIn = `-- name: GetCheckIn :one
SELECT id, user_id, local_date, mood, energy, wins, challenges, notes, related_goal_id, created_at, updated_at FROM check_ins WHERE id = $1 AND user_id = $2
`

type GetCheckInParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetCheckIn(ctx context.Context, arg GetCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCheckIn, arg.ID, arg.UserID)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocalDate,
		&i.Mood,
		&i.Energy,
		&i.Wins,
		&i.Challenges,
		&i.Notes,
		&i.RelatedGoalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckInByDate = `-- name: GetCheckInByDate :one
SELECT id, user_id, local_date, mood, energy, wins, challenges, notes, related_goal_id, created_at, updated_at FROM check_ins WHERE user_id = $1 AND local_date = $2
`

type GetCheckInByDateParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
}

func (q *Queries) GetCheckInByDate(ctx context.Context, arg GetCheckInByDateParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, getCheckInByDate, arg.UserID, arg.LocalDate)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocalDate,
		&i.Mood,
		&i.Energy,
		&i.Wins,
		&i.Challenges,
		&i.Notes,
		&i.RelatedGoalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCheckInDates = `-- name: ListCheckInDates :many
SELECT local_date FROM check_ins
WHERE user_id = $1
ORDER BY local_date DESC
LIMIT $2
`

type ListCheckInDatesParams struct {
	UserID uuid.UUID
	Limit  int32
}

// Newest first; used to compute streaks without loading full rows.
func (q *Queries) ListCheckInDates(ctx context.Context, arg ListCheckInDatesParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, listCheckInDates, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var local_date pgtype.Date
		if err := rows.Scan(&local_date); err != nil {
			return nil, err
		}
		items = append(items, local_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckIns = `-- name: ListCheckIns :many
SELECT id, user_id, local_date, mood, energy, wins, challenges, notes, related_goal_id, created_at, updated_at FROM check_ins
WHERE user_id = $1
ORDER BY local_date DESC
LIMIT $2
`

type ListCheckInsParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListCheckIns(ctx context.Context, arg ListCheckInsParams) ([]CheckIn, error) {
	rows, err := q.db.Query(ctx, listCheckIns, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckIn{}
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocalDate,
			&i.Mood,
			&i.Energy,
			&i.Wins,
			&i.Challenges,
			&i.Notes,
			&i.RelatedGoalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckInsBetween = `-- name: ListCheckInsBetween :many
SELECT id, user_id, local_date, mood, energy, wins, challenges, notes, related_goal_id, created_at, updated_at FROM check_ins
WHERE user_id = $1 AND local_date >= $2 AND local_date < $3
ORDER BY local_date DESC
`

type ListCheckInsBetweenParams struct {
	UserID      uuid.UUID
	LocalDate   pgtype.Date
	LocalDate_2 pgtype.Date
}

// Half-open [since, until) so consecutive windows tile without overlapping.
// Unbounded on purpose: the window itself is the limit.
func (q *Queries) ListCheckInsBetween(ctx context.Context, arg ListCheckInsBetweenParams) ([]CheckIn, error) {
	rows, err := q.db.Query(ctx, listCheckInsBetween, arg.UserID, arg.LocalDate, arg.LocalDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckIn{}
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocalDate,
			&i.Mood,
			&i.Energy,
			&i.Wins,
			&i.Challenges,
			&i.Notes,
			&i.RelatedGoalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCheckInsSince = `-- name: ListCheckInsSince :many
SELECT id, user_id, local_date, mood, energy, wins, challenges, notes, related_goal_id, created_at, updated_at FROM check_ins
WHERE user_id = $1 AND local_date >= $2
ORDER BY local_date DESC
LIMIT $3
`

type ListCheckInsSinceParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
	Limit     int32
}

func (q *Queries) ListCheckInsSince(ctx context.Context, arg ListCheckInsSinceParams) ([]CheckIn, error) {
	rows, err := q.db.Query(ctx, listCheckInsSince, arg.UserID, arg.LocalDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckIn{}
	for rows.Next() {
		var i CheckIn
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LocalDate,
			&i.Mood,
			&i.Energy,
			&i.Wins,
			&i.Challenges,
			&i.Notes,
			&i.RelatedGoalID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCheckIn = `-- name: UpdateCheckIn :one
UPDATE check_ins
SET mood            = $3,
    energy          = $4,
    wins            = $5,
    challenges      = $6,
    notes           = $7,
    related_goal_id = $8,
    updated_at      = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, local_date, mood, energy, wins, challenges, notes, related_goal_id, created_at, updated_at
`

type UpdateCheckInParams struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Mood          int16
	Energy        int16
	Wins          string
	Challenges    string
	Notes         string
	RelatedGoalID *uuid.UUID
}

func (q *Queries) UpdateCheckIn(ctx context.Context, arg UpdateCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, updateCheckIn,
		arg.ID,
		arg.UserID,
		arg.Mood,
		arg.Energy,
		arg.Wins,
		arg.Challenges,
		arg.Notes,
		arg.RelatedGoalID,
	)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocalDate,
		&i.Mood,
		&i.Energy,
		&i.Wins,
		&i.Challenges,
		&i.Notes,
		&i.RelatedGoalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCheckIn = `-- name: UpsertCheckIn :one
INSERT INTO check_ins (
    user_id, local_date, mood, energy, wins, challenges, notes, related_goal_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (user_id, local_date) DO UPDATE SET
    mood            = EXCLUDED.mood,
    energy          = EXCLUDED.energy,
    wins            = EXCLUDED.wins,
    challenges      = EXCLUDED.challenges,
    notes           = EXCLUDED.notes,
    related_goal_id = EXCLUDED.related_goal_id,
    updated_at      = now()
RETURNING id, user_id, local_date, mood, energy, wins, challenges, notes, related_goal_id, created_at, updated_at
`

type UpsertCheckInParams struct {
	UserID        uuid.UUID
	LocalDate     pgtype.Date
	Mood          int16
	Energy        int16
	Wins          string
	Challenges    string
	Notes         string
	RelatedGoalID *uuid.UUID
}

func (q *Queries) UpsertCheckIn(ctx context.Context, arg UpsertCheckInParams) (CheckIn, error) {
	row := q.db.QueryRow(ctx, upsertCheckIn,
		arg.UserID,
		arg.LocalDate,
		arg.Mood,
		arg.Energy,
		arg.Wins,
		arg.Challenges,
		arg.Notes,
		arg.RelatedGoalID,
	)
	var i CheckIn
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LocalDate,
		&i.Mood,
		&i.Energy,
		&i.Wins,
		&i.Challenges,
		&i.Notes,
		&i.RelatedGoalID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
