// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package mediadb

import (
	"time"

	"github.com/google/uuid"
)

type FormAnalysis struct {
	ID        uuid.UUID
	MediaID   uuid.UUID
	UserID    uuid.UUID
	Status    string
	Analysis  []byte
	Error     string
	Model     string
	Provider  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Medium struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Kind         string
	MimeType     string
	SizeBytes    int64
	StorageKey   string
	OriginalName string
	CreatedAt    time.Time
}
