// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package mediadb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeAnalysis = `-- name: CompleteAnalysis :exec
UPDATE form_analyses
SET status = 'done', analysis = $2, model = $3, provider = $4, updated_at = now()
WHERE id = $1
`

type CompleteAnalysisParams struct {
	ID       uuid.UUID
	Analysis []byte
	Model    string
	Provider string
}

func (q *Queries) CompleteAnalysis(ctx context.Context, arg CompleteAnalysisParams) error {
	_, err := q.db.Exec(ctx, completeAnalysis,
		arg.ID,
		arg.Analysis,
		arg.Model,
		arg.Provider,
	)
	return err
}

const countUserMediaByKind = `-- name: CountUserMediaByKind :one
SELECT count(*)::int FROM media WHERE user_id = $1 AND kind = $2
`

type CountUserMediaByKindParams struct {
	UserID uuid.UUID
	Kind   string
}

func (q *Queries) CountUserMediaByKind(ctx context.Context, arg CountUserMediaByKindParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUserMediaByKind, arg.UserID, arg.Kind)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAnalysis = `-- name: CreateAnalysis :one
INSERT INTO form_analyses (media_id, user_id)
VALUES ($1, $2)
RETURNING id, media_id, user_id, status, analysis, error, model, provider, created_at, updated_at
`

type CreateAnalysisParams struct {
	MediaID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) CreateAnalysis(ctx context.Context, arg CreateAnalysisParams) (FormAnalysis, error) {
	row := q.db.QueryRow(ctx, createAnalysis, arg.MediaID, arg.UserID)
	var i FormAnalysis
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Status,
		&i.Analysis,
		&i.Error,
		&i.Model,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (user_id, kind, mime_type, size_bytes, storage_key, original_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, kind, mime_type, size_bytes, storage_key, original_name, created_at
`

type CreateMediaParams struct {
	UserID       uuid.UUID
	Kind         string
	MimeType     string
	SizeBytes    int64
	StorageKey   string
	OriginalName string
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.UserID,
		arg.Kind,
		arg.MimeType,
		arg.SizeBytes,
		arg.StorageKey,
		arg.OriginalName,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.OriginalName,
		&i.CreatedAt,
	)
	return i, err
}

const failAnalysis = `-- name: FailAnalysis :exec
UPDATE form_analyses
SET status = 'failed', error = $2, updated_at = now()
WHERE id = $1
`

type FailAnalysisParams struct {
	ID    uuid.UUID
	Error string
}

func (q *Queries) FailAnalysis(ctx context.Context, arg FailAnalysisParams) error {
	_, err := q.db.Exec(ctx, failAnalysis, arg.ID, arg.Error)
	return err
}

const getAnalysis = `-- name: GetAnalysis :one
SELECT id, media_id, user_id, status, analysis, error, model, provider, created_at, updated_at FROM form_analyses WHERE id = $1 AND user_id = $2
`

type GetAnalysisParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetAnalysis(ctx context.Context, arg GetAnalysisParams) (FormAnalysis, error) {
	row := q.db.QueryRow(ctx, getAnalysis, arg.ID, arg.UserID)
	var i FormAnalysis
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Status,
		&i.Analysis,
		&i.Error,
		&i.Model,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnalysisByMedia = `-- name: GetAnalysisByMedia :one
SELECT id, media_id, user_id, status, analysis, error, model, provider, created_at, updated_at FROM form_analyses WHERE media_id = $1
`

func (q *Queries) GetAnalysisByMedia(ctx context.Context, mediaID uuid.UUID) (FormAnalysis, error) {
	row := q.db.QueryRow(ctx, getAnalysisByMedia, mediaID)
	var i FormAnalysis
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.UserID,
		&i.Status,
		&i.Analysis,
		&i.Error,
		&i.Model,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedia = `-- name: GetMedia :one
SELECT id, user_id, kind, mime_type, size_bytes, storage_key, original_name, created_at FROM media WHERE id = $1 AND user_id = $2
`

type GetMediaParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMedia(ctx context.Context, arg GetMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, arg.ID, arg.UserID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.OriginalName,
		&i.CreatedAt,
	)
	return i, err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT id, user_id, kind, mime_type, size_bytes, storage_key, original_name, created_at FROM media WHERE id = $1
`

// Unscoped, for the worker, which acts on behalf of the system rather than a
// signed-in user. Never reachable from a handler.
func (q *Queries) GetMediaByID(ctx context.Context, id uuid.UUID) (Medium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.MimeType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.OriginalName,
		&i.CreatedAt,
	)
	return i, err
}

const latestUserMediaCreatedAt = `-- name: LatestUserMediaCreatedAt :one
SELECT created_at FROM media
WHERE user_id = $1 AND kind = $2
ORDER BY created_at DESC
LIMIT 1
`

type LatestUserMediaCreatedAtParams struct {
	UserID uuid.UUID
	Kind   string
}

func (q *Queries) LatestUserMediaCreatedAt(ctx context.Context, arg LatestUserMediaCreatedAtParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, latestUserMediaCreatedAt, arg.UserID, arg.Kind)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const listAnalyses = `-- name: ListAnalyses :many
SELECT id, media_id, user_id, status, analysis, error, model, provider, created_at, updated_at FROM form_analyses
WHERE user_id = $1 AND status = 'done'
ORDER BY created_at DESC
LIMIT $2
`

type ListAnalysesParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListAnalyses(ctx context.Context, arg ListAnalysesParams) ([]FormAnalysis, error) {
	rows, err := q.db.Query(ctx, listAnalyses, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FormAnalysis{}
	for rows.Next() {
		var i FormAnalysis
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.UserID,
			&i.Status,
			&i.Analysis,
			&i.Error,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startAnalysis = `-- name: StartAnalysis :exec
UPDATE form_analyses
SET status = 'running', updated_at = now()
WHERE id = $1
`

func (q *Queries) StartAnalysis(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, startAnalysis, id)
	return err
}
