// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package connectionsdb

import (
	"context"

	"github.com/google/uuid"
)

const getAgentConnectionByTokenHash = `-- name: GetAgentConnectionByTokenHash :one
SELECT id, user_id, name, client_kind, token_hash, token_prefix, created_at, last_used_at, revoked_at FROM agent_connections
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAgentConnectionByTokenHash(ctx context.Context, tokenHash []byte) (AgentConnection, error) {
	row := q.db.QueryRow(ctx, getAgentConnectionByTokenHash, tokenHash)
	var i AgentConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ClientKind,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAgentConnection = `-- name: InsertAgentConnection :one
INSERT INTO agent_connections (user_id, name, client_kind, token_hash, token_prefix)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, client_kind, token_hash, token_prefix, created_at, last_used_at, revoked_at
`

type InsertAgentConnectionParams struct {
	UserID      uuid.UUID
	Name        string
	ClientKind  string
	TokenHash   []byte
	TokenPrefix string
}

func (q *Queries) InsertAgentConnection(ctx context.Context, arg InsertAgentConnectionParams) (AgentConnection, error) {
	row := q.db.QueryRow(ctx, insertAgentConnection,
		arg.UserID,
		arg.Name,
		arg.ClientKind,
		arg.TokenHash,
		arg.TokenPrefix,
	)
	var i AgentConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ClientKind,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAgentConnections = `-- name: ListAgentConnections :many
SELECT id, user_id, name, client_kind, token_hash, token_prefix, created_at, last_used_at, revoked_at FROM agent_connections
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAgentConnections(ctx context.Context, userID uuid.UUID) ([]AgentConnection, error) {
	rows, err := q.db.Query(ctx, listAgentConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentConnection{}
	for rows.Next() {
		var i AgentConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.ClientKind,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAgentConnection = `-- name: RevokeAgentConnection :execrows
UPDATE agent_connections
SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAgentConnectionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Scoped by user_id as well as id: the id comes from a form, and without the
// second predicate a guessed id would revoke somebody else's connection.
func (q *Queries) RevokeAgentConnection(ctx context.Context, arg RevokeAgentConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAgentConnection, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAgentConnection = `-- name: TouchAgentConnection :exec
UPDATE agent_connections
SET last_used_at = now()
WHERE id = $1
  AND (last_used_at IS NULL OR last_used_at < now() - interval '5 minutes')
`

// TouchAgentConnection records that a token was used, but only once the
// stored value has gone stale. An agent listing tools in a loop would
// otherwise write on every request, and "last used" is never read at a
// resolution that would notice the difference.
func (q *Queries) TouchAgentConnection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAgentConnection, id)
	return err
}
