// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package reportsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveReport = `-- name: ArchiveReport :one
UPDATE reports
SET archived_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND archived_at IS NULL
RETURNING id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at
`

type ArchiveReportParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ArchiveReport(ctx context.Context, arg ArchiveReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, archiveReport, arg.ID, arg.UserID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.LastError,
		&i.GeneratedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (user_id, kind, period_start, period_end, title, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at
`

type CreateReportParams struct {
	UserID      uuid.UUID
	Kind        string
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
	Title       string
	Status      string
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.UserID,
		arg.Kind,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Title,
		arg.Status,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.LastError,
		&i.GeneratedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveReportForWeek = `-- name: GetActiveReportForWeek :one
SELECT id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at FROM reports
WHERE user_id = $1
  AND kind = $2
  AND period_start = $3
  AND archived_at IS NULL
`

type GetActiveReportForWeekParams struct {
	UserID      uuid.UUID
	Kind        string
	PeriodStart pgtype.Date
}

func (q *Queries) GetActiveReportForWeek(ctx context.Context, arg GetActiveReportForWeekParams) (Report, error) {
	row := q.db.QueryRow(ctx, getActiveReportForWeek, arg.UserID, arg.Kind, arg.PeriodStart)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.LastError,
		&i.GeneratedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at FROM reports WHERE id = $1 AND user_id = $2
`

type GetReportParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, arg.ID, arg.UserID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.LastError,
		&i.GeneratedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const latestReadyReport = `-- name: LatestReadyReport :one
SELECT id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at FROM reports
WHERE user_id = $1
  AND status = 'ready'
  AND archived_at IS NULL
ORDER BY period_start DESC
LIMIT 1
`

func (q *Queries) LatestReadyReport(ctx context.Context, userID uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, latestReadyReport, userID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.LastError,
		&i.GeneratedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at FROM reports
WHERE user_id = $1
  AND ($3::boolean OR archived_at IS NULL)
ORDER BY period_start DESC, created_at DESC
LIMIT $2
`

type ListReportsParams struct {
	UserID          uuid.UUID
	Limit           int32
	IncludeArchived bool
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, arg.UserID, arg.Limit, arg.IncludeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.LastError,
			&i.GeneratedAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportFailed = `-- name: MarkReportFailed :one
UPDATE reports
SET status     = 'failed',
    last_error = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at
`

type MarkReportFailedParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	LastError string
}

func (q *Queries) MarkReportFailed(ctx context.Context, arg MarkReportFailedParams) (Report, error) {
	row := q.db.QueryRow(ctx, markReportFailed, arg.ID, arg.UserID, arg.LastError)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.LastError,
		&i.GeneratedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markReportPending = `-- name: MarkReportPending :one
UPDATE reports
SET status      = 'pending',
    last_error  = '',
    updated_at  = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at
`

type MarkReportPendingParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) MarkReportPending(ctx context.Context, arg MarkReportPendingParams) (Report, error) {
	row := q.db.QueryRow(ctx, markReportPending, arg.ID, arg.UserID)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.LastError,
		&i.GeneratedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveGeneratedReport = `-- name: SaveGeneratedReport :one
UPDATE reports
SET status       = 'ready',
    body         = $3,
    last_error   = '',
    generated_at = now(),
    updated_at   = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, kind, period_start, period_end, title, body, status, last_error, generated_at, archived_at, created_at, updated_at
`

type SaveGeneratedReportParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Body   string
}

func (q *Queries) SaveGeneratedReport(ctx context.Context, arg SaveGeneratedReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, saveGeneratedReport, arg.ID, arg.UserID, arg.Body)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.LastError,
		&i.GeneratedAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
