// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package fastingdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteFast = `-- name: DeleteFast :execrows
DELETE FROM fasting_sessions WHERE id = $1 AND user_id = $2
`

type DeleteFastParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFast(ctx context.Context, arg DeleteFastParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFast, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listFastsOverlapping = `-- name: ListFastsOverlapping :many
SELECT id, user_id, started_at, ended_at, target_hours, created_at FROM fasting_sessions
WHERE user_id = $1 AND started_at < $3 AND (ended_at IS NULL OR ended_at > $2)
ORDER BY started_at DESC
`

type ListFastsOverlappingParams struct {
	UserID    uuid.UUID
	EndedAt   *time.Time
	StartedAt time.Time
}

// Every fast that touches [since, until), open ones included, newest first.
func (q *Queries) ListFastsOverlapping(ctx context.Context, arg ListFastsOverlappingParams) ([]FastingSession, error) {
	rows, err := q.db.Query(ctx, listFastsOverlapping, arg.UserID, arg.EndedAt, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FastingSession{}
	for rows.Next() {
		var i FastingSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StartedAt,
			&i.EndedAt,
			&i.TargetHours,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openFast = `-- name: OpenFast :one
SELECT id, user_id, started_at, ended_at, target_hours, created_at FROM fasting_sessions WHERE user_id = $1 AND ended_at IS NULL
`

func (q *Queries) OpenFast(ctx context.Context, userID uuid.UUID) (FastingSession, error) {
	row := q.db.QueryRow(ctx, openFast, userID)
	var i FastingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TargetHours,
		&i.CreatedAt,
	)
	return i, err
}

const startFast = `-- name: StartFast :one
INSERT INTO fasting_sessions (user_id, started_at, target_hours)
VALUES ($1, $2, $3)
RETURNING id, user_id, started_at, ended_at, target_hours, created_at
`

type StartFastParams struct {
	UserID      uuid.UUID
	StartedAt   time.Time
	TargetHours int16
}

func (q *Queries) StartFast(ctx context.Context, arg StartFastParams) (FastingSession, error) {
	row := q.db.QueryRow(ctx, startFast, arg.UserID, arg.StartedAt, arg.TargetHours)
	var i FastingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TargetHours,
		&i.CreatedAt,
	)
	return i, err
}

const stopFast = `-- name: StopFast :one
UPDATE fasting_sessions SET ended_at = $2
WHERE user_id = $1 AND ended_at IS NULL
RETURNING id, user_id, started_at, ended_at, target_hours, created_at
`

type StopFastParams struct {
	UserID  uuid.UUID
	EndedAt *time.Time
}

func (q *Queries) StopFast(ctx context.Context, arg StopFastParams) (FastingSession, error) {
	row := q.db.QueryRow(ctx, stopFast, arg.UserID, arg.EndedAt)
	var i FastingSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StartedAt,
		&i.EndedAt,
		&i.TargetHours,
		&i.CreatedAt,
	)
	return i, err
}
