// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stravadb

import (
	"time"

	"github.com/google/uuid"
)

type StravaActivity struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	StravaID            int64
	Name                string
	SportType           string
	StartDate           time.Time
	DistanceM           float64
	MovingTimeS         int32
	ElapsedTimeS        int32
	TotalElevationGainM float64
	AverageSpeedMs      float64
	SummaryPolyline     string
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type StravaConnection struct {
	UserID             uuid.UUID
	AthleteID          int64
	AccessToken        string
	RefreshToken       string
	ExpiresAt          time.Time
	Scopes             string
	LastSyncedAt       *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AccessTokenSealed  []byte
	RefreshTokenSealed []byte
}
