// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package stravadb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteStravaConnection = `-- name: DeleteStravaConnection :exec
DELETE FROM strava_connections WHERE user_id = $1
`

func (q *Queries) DeleteStravaConnection(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStravaConnection, userID)
	return err
}

const getStravaConnection = `-- name: GetStravaConnection :one
SELECT user_id, athlete_id, access_token, refresh_token, expires_at, scopes, last_synced_at, created_at, updated_at, access_token_sealed, refresh_token_sealed, last_sync_error, last_sync_attempted_at FROM strava_connections WHERE user_id = $1
`

func (q *Queries) GetStravaConnection(ctx context.Context, userID uuid.UUID) (StravaConnection, error) {
	row := q.db.QueryRow(ctx, getStravaConnection, userID)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessTokenSealed,
		&i.RefreshTokenSealed,
		&i.LastSyncError,
		&i.LastSyncAttemptedAt,
	)
	return i, err
}

const listStravaActivities = `-- name: ListStravaActivities :many
SELECT id, user_id, strava_id, name, sport_type, start_date, distance_m, moving_time_s, elapsed_time_s, total_elevation_gain_m, average_speed_ms, summary_polyline, created_at, updated_at FROM strava_activities
WHERE user_id = $1
ORDER BY start_date DESC
LIMIT $2
`

type ListStravaActivitiesParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListStravaActivities(ctx context.Context, arg ListStravaActivitiesParams) ([]StravaActivity, error) {
	rows, err := q.db.Query(ctx, listStravaActivities, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StravaActivity{}
	for rows.Next() {
		var i StravaActivity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StravaID,
			&i.Name,
			&i.SportType,
			&i.StartDate,
			&i.DistanceM,
			&i.MovingTimeS,
			&i.ElapsedTimeS,
			&i.TotalElevationGainM,
			&i.AverageSpeedMs,
			&i.SummaryPolyline,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStravaConnectionsDueForSync = `-- name: ListStravaConnectionsDueForSync :many
SELECT user_id FROM strava_connections
WHERE last_synced_at IS NULL
   OR last_synced_at < $1::timestamptz
ORDER BY last_synced_at ASC NULLS FIRST
LIMIT $2::int
`

type ListStravaConnectionsDueForSyncParams struct {
	Before  time.Time
	MaxRows int32
}

// Connections the periodic sweep should re-sync: never synced, or not since
// the cutoff. Ordered oldest first so a backlog drains fairly rather than
// starving whoever sorts last by id.
func (q *Queries) ListStravaConnectionsDueForSync(ctx context.Context, arg ListStravaConnectionsDueForSyncParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listStravaConnectionsDueForSync, arg.Before, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStravaSyncFailed = `-- name: MarkStravaSyncFailed :exec
UPDATE strava_connections
SET last_sync_attempted_at = now(),
    last_sync_error        = $2,
    updated_at             = now()
WHERE user_id = $1
`

type MarkStravaSyncFailedParams struct {
	UserID        uuid.UUID
	LastSyncError string
}

// last_synced_at is deliberately untouched. It is the window the next import
// starts from, and advancing it on a failure would skip whatever that run
// never managed to fetch.
func (q *Queries) MarkStravaSyncFailed(ctx context.Context, arg MarkStravaSyncFailedParams) error {
	_, err := q.db.Exec(ctx, markStravaSyncFailed, arg.UserID, arg.LastSyncError)
	return err
}

const markStravaSynced = `-- name: MarkStravaSynced :exec
UPDATE strava_connections
SET last_synced_at         = $2,
    last_sync_attempted_at = now(),
    last_sync_error        = '',
    updated_at             = now()
WHERE user_id = $1
`

type MarkStravaSyncedParams struct {
	UserID       uuid.UUID
	LastSyncedAt *time.Time
}

// Success clears the error as well as moving the watermark: a card that keeps
// showing yesterday's failure after today's sync worked is worse than one that
// shows nothing.
func (q *Queries) MarkStravaSynced(ctx context.Context, arg MarkStravaSyncedParams) error {
	_, err := q.db.Exec(ctx, markStravaSynced, arg.UserID, arg.LastSyncedAt)
	return err
}

const sumStravaActivitiesBetween = `-- name: SumStravaActivitiesBetween :one
SELECT
    count(*)::bigint                                           AS activities,
    coalesce(sum(distance_m), 0)::double precision             AS distance_m,
    coalesce(sum(total_elevation_gain_m), 0)::double precision AS elevation_m
FROM strava_activities
WHERE user_id = $1
  AND start_date >= $2::timestamptz
  AND start_date <  $3::timestamptz
`

type SumStravaActivitiesBetweenParams struct {
	UserID uuid.UUID
	Since  time.Time
	Until  time.Time
}

type SumStravaActivitiesBetweenRow struct {
	Activities int64
	DistanceM  float64
	ElevationM float64
}

// Half-open window, matching timerange.Range. Both summed columns are NOT NULL,
// so the coalesce only guards the empty-set case, where sum() returns NULL.
func (q *Queries) SumStravaActivitiesBetween(ctx context.Context, arg SumStravaActivitiesBetweenParams) (SumStravaActivitiesBetweenRow, error) {
	row := q.db.QueryRow(ctx, sumStravaActivitiesBetween, arg.UserID, arg.Since, arg.Until)
	var i SumStravaActivitiesBetweenRow
	err := row.Scan(&i.Activities, &i.DistanceM, &i.ElevationM)
	return i, err
}

const updateStravaTokens = `-- name: UpdateStravaTokens :one
UPDATE strava_connections
SET access_token         = $2,
    refresh_token        = $3,
    access_token_sealed  = $4,
    refresh_token_sealed = $5,
    expires_at           = $6,
    updated_at           = now()
WHERE user_id = $1
RETURNING user_id, athlete_id, access_token, refresh_token, expires_at, scopes, last_synced_at, created_at, updated_at, access_token_sealed, refresh_token_sealed, last_sync_error, last_sync_attempted_at
`

type UpdateStravaTokensParams struct {
	UserID             uuid.UUID
	AccessToken        string
	RefreshToken       string
	AccessTokenSealed  []byte
	RefreshTokenSealed []byte
	ExpiresAt          time.Time
}

func (q *Queries) UpdateStravaTokens(ctx context.Context, arg UpdateStravaTokensParams) (StravaConnection, error) {
	row := q.db.QueryRow(ctx, updateStravaTokens,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenSealed,
		arg.RefreshTokenSealed,
		arg.ExpiresAt,
	)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessTokenSealed,
		&i.RefreshTokenSealed,
		&i.LastSyncError,
		&i.LastSyncAttemptedAt,
	)
	return i, err
}

const upsertStravaActivity = `-- name: UpsertStravaActivity :exec
INSERT INTO strava_activities (
    user_id, strava_id, name, sport_type, start_date,
    distance_m, moving_time_s, elapsed_time_s,
    total_elevation_gain_m, average_speed_ms, summary_polyline
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (user_id, strava_id) DO UPDATE SET
    name                   = EXCLUDED.name,
    sport_type             = EXCLUDED.sport_type,
    start_date             = EXCLUDED.start_date,
    distance_m             = EXCLUDED.distance_m,
    moving_time_s          = EXCLUDED.moving_time_s,
    elapsed_time_s         = EXCLUDED.elapsed_time_s,
    total_elevation_gain_m = EXCLUDED.total_elevation_gain_m,
    average_speed_ms       = EXCLUDED.average_speed_ms,
    summary_polyline       = EXCLUDED.summary_polyline,
    updated_at             = now()
`

type UpsertStravaActivityParams struct {
	UserID              uuid.UUID
	StravaID            int64
	Name                string
	SportType           string
	StartDate           time.Time
	DistanceM           float64
	MovingTimeS         int32
	ElapsedTimeS        int32
	TotalElevationGainM float64
	AverageSpeedMs      float64
	SummaryPolyline     string
}

func (q *Queries) UpsertStravaActivity(ctx context.Context, arg UpsertStravaActivityParams) error {
	_, err := q.db.Exec(ctx, upsertStravaActivity,
		arg.UserID,
		arg.StravaID,
		arg.Name,
		arg.SportType,
		arg.StartDate,
		arg.DistanceM,
		arg.MovingTimeS,
		arg.ElapsedTimeS,
		arg.TotalElevationGainM,
		arg.AverageSpeedMs,
		arg.SummaryPolyline,
	)
	return err
}

const upsertStravaConnection = `-- name: UpsertStravaConnection :one
INSERT INTO strava_connections (
    user_id, athlete_id,
    access_token, refresh_token,
    access_token_sealed, refresh_token_sealed,
    expires_at, scopes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (user_id) DO UPDATE SET
    athlete_id           = EXCLUDED.athlete_id,
    access_token         = EXCLUDED.access_token,
    refresh_token        = EXCLUDED.refresh_token,
    access_token_sealed  = EXCLUDED.access_token_sealed,
    refresh_token_sealed = EXCLUDED.refresh_token_sealed,
    expires_at           = EXCLUDED.expires_at,
    scopes               = EXCLUDED.scopes,
    updated_at           = now()
RETURNING user_id, athlete_id, access_token, refresh_token, expires_at, scopes, last_synced_at, created_at, updated_at, access_token_sealed, refresh_token_sealed, last_sync_error, last_sync_attempted_at
`

type UpsertStravaConnectionParams struct {
	UserID             uuid.UUID
	AthleteID          int64
	AccessToken        string
	RefreshToken       string
	AccessTokenSealed  []byte
	RefreshTokenSealed []byte
	ExpiresAt          time.Time
	Scopes             string
}

// Both forms of each token are written together, and exactly one of each pair
// carries a value: sealed when the deployment has an encryption key, plaintext
// when it does not. Writing both clears whichever the previous write used, so a
// row that was plaintext before a key was configured does not keep a readable
// copy alongside the sealed one.
func (q *Queries) UpsertStravaConnection(ctx context.Context, arg UpsertStravaConnectionParams) (StravaConnection, error) {
	row := q.db.QueryRow(ctx, upsertStravaConnection,
		arg.UserID,
		arg.AthleteID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.AccessTokenSealed,
		arg.RefreshTokenSealed,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccessTokenSealed,
		&i.RefreshTokenSealed,
		&i.LastSyncError,
		&i.LastSyncAttemptedAt,
	)
	return i, err
}
