// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package stravadb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteStravaConnection = `-- name: DeleteStravaConnection :exec
DELETE FROM strava_connections WHERE user_id = $1
`

func (q *Queries) DeleteStravaConnection(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStravaConnection, userID)
	return err
}

const getStravaConnection = `-- name: GetStravaConnection :one
SELECT user_id, athlete_id, access_token, refresh_token, expires_at, scopes, last_synced_at, created_at, updated_at FROM strava_connections WHERE user_id = $1
`

func (q *Queries) GetStravaConnection(ctx context.Context, userID uuid.UUID) (StravaConnection, error) {
	row := q.db.QueryRow(ctx, getStravaConnection, userID)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markStravaSynced = `-- name: MarkStravaSynced :exec
UPDATE strava_connections
SET last_synced_at = $2, updated_at = now()
WHERE user_id = $1
`

type MarkStravaSyncedParams struct {
	UserID       uuid.UUID
	LastSyncedAt *time.Time
}

func (q *Queries) MarkStravaSynced(ctx context.Context, arg MarkStravaSyncedParams) error {
	_, err := q.db.Exec(ctx, markStravaSynced, arg.UserID, arg.LastSyncedAt)
	return err
}

const updateStravaTokens = `-- name: UpdateStravaTokens :one
UPDATE strava_connections
SET access_token = $2, refresh_token = $3, expires_at = $4, updated_at = now()
WHERE user_id = $1
RETURNING user_id, athlete_id, access_token, refresh_token, expires_at, scopes, last_synced_at, created_at, updated_at
`

type UpdateStravaTokensParams struct {
	UserID       uuid.UUID
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
}

func (q *Queries) UpdateStravaTokens(ctx context.Context, arg UpdateStravaTokensParams) (StravaConnection, error) {
	row := q.db.QueryRow(ctx, updateStravaTokens,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertStravaConnection = `-- name: UpsertStravaConnection :one
INSERT INTO strava_connections (
    user_id, athlete_id, access_token, refresh_token, expires_at, scopes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id) DO UPDATE SET
    athlete_id    = EXCLUDED.athlete_id,
    access_token  = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    expires_at    = EXCLUDED.expires_at,
    scopes        = EXCLUDED.scopes,
    updated_at    = now()
RETURNING user_id, athlete_id, access_token, refresh_token, expires_at, scopes, last_synced_at, created_at, updated_at
`

type UpsertStravaConnectionParams struct {
	UserID       uuid.UUID
	AthleteID    int64
	AccessToken  string
	RefreshToken string
	ExpiresAt    time.Time
	Scopes       string
}

func (q *Queries) UpsertStravaConnection(ctx context.Context, arg UpsertStravaConnectionParams) (StravaConnection, error) {
	row := q.db.QueryRow(ctx, upsertStravaConnection,
		arg.UserID,
		arg.AthleteID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.Scopes,
	)
	var i StravaConnection
	err := row.Scan(
		&i.UserID,
		&i.AthleteID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.Scopes,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
