// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package vaultdb

import (
	"time"

	"github.com/google/uuid"
)

type VaultConnection struct {
	UserID     uuid.UUID
	RootPath   string
	LastSyncAt *time.Time
	LastError  string
	Enabled    bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
