// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersdb

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Conversation struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FormAnalysis struct {
	ID        uuid.UUID
	MediaID   uuid.UUID
	UserID    uuid.UUID
	Status    string
	Analysis  []byte
	Error     string
	Model     string
	Provider  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Job struct {
	ID          uuid.UUID
	Kind        string
	Payload     []byte
	Status      string
	Attempts    int16
	MaxAttempts int16
	RunAfter    time.Time
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Medium struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Kind         string
	MimeType     string
	SizeBytes    int64
	StorageKey   string
	OriginalName string
	CreatedAt    time.Time
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        string
	Parts          []byte
	Usage          []byte
	Model          *string
	Provider       *string
	CreatedAt      time.Time
}

type Session struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	CreatedAt  time.Time
	LastSeenAt time.Time
	UserAgent  *string
	Ip         *netip.Addr
}

type User struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  string
	DisplayName   string
	Timezone      string
	CoachingStyle *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type WorkoutIntake struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Goal           string
	Experience     string
	DaysPerWeek    int16
	SessionMinutes int16
	Equipment      []string
	Limitations    string
	CreatedAt      time.Time
}

type WorkoutPlan struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	IntakeID  uuid.UUID
	Name      string
	Plan      []byte
	Model     string
	Provider  string
	CreatedAt time.Time
}
