// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package usersdb

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  *string
	DisplayName   string
	Timezone      string
	CoachingStyle *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Tier          string
	OnboardedAt   *time.Time
	CoachingTone  string
	// BCP 47 tag chosen by the user: en, pt-PT, pt-BR or es. Not inferred from timezone.
	Locale string
}
