// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package usersdb

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, timezone)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, display_name, timezone, coaching_style, created_at, updated_at, tier, onboarded_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash *string
	DisplayName  string
	Timezone     string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.CoachingStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.OnboardedAt,
	)
	return i, err
}

const createUserWithID = `-- name: CreateUserWithID :one
INSERT INTO users (id, email, password_hash, display_name, timezone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, password_hash, display_name, timezone, coaching_style, created_at, updated_at, tier, onboarded_at
`

type CreateUserWithIDParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash *string
	DisplayName  string
	Timezone     string
}

// Used when a passkey registration ceremony needs a stable user handle
// (WebAuthnID) before the row is inserted.
func (q *Queries) CreateUserWithID(ctx context.Context, arg CreateUserWithIDParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithID,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.CoachingStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.OnboardedAt,
	)
	return i, err
}

const emailExists = `-- name: EmailExists :one
SELECT EXISTS (SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) EmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, emailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, timezone, coaching_style, created_at, updated_at, tier, onboarded_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.CoachingStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.OnboardedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, timezone, coaching_style, created_at, updated_at, tier, onboarded_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.CoachingStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.OnboardedAt,
	)
	return i, err
}

const listOnboardedUsers = `-- name: ListOnboardedUsers :many
SELECT id, email, password_hash, display_name, timezone, coaching_style, created_at, updated_at, tier, onboarded_at FROM users
WHERE onboarded_at IS NOT NULL
  AND ($1::uuid = '00000000-0000-0000-0000-000000000000' OR id > $1)
ORDER BY id
LIMIT $2
`

type ListOnboardedUsersParams struct {
	After       uuid.UUID
	ResultLimit int32
}

// Keyset page of accounts the nudge sweep may evaluate. First-run users
// stay silent until they finish or skip onboarding.
func (q *Queries) ListOnboardedUsers(ctx context.Context, arg ListOnboardedUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listOnboardedUsers, arg.After, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Timezone,
			&i.CoachingStyle,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Tier,
			&i.OnboardedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserOnboarded = `-- name: MarkUserOnboarded :one
UPDATE users
SET onboarded_at = now(),
    updated_at   = now()
WHERE id = $1
  AND onboarded_at IS NULL
RETURNING id, email, password_hash, display_name, timezone, coaching_style, created_at, updated_at, tier, onboarded_at
`

// Sets the first-run flag once. A second call returns the row unchanged.
func (q *Queries) MarkUserOnboarded(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, markUserOnboarded, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.CoachingStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.OnboardedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at    = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name   = $2,
    timezone       = $3,
    coaching_style = $4,
    updated_at     = now()
WHERE id = $1
RETURNING id, email, password_hash, display_name, timezone, coaching_style, created_at, updated_at, tier, onboarded_at
`

type UpdateUserProfileParams struct {
	ID            uuid.UUID
	DisplayName   string
	Timezone      string
	CoachingStyle *string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.Timezone,
		arg.CoachingStyle,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.CoachingStyle,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Tier,
		&i.OnboardedAt,
	)
	return i, err
}
