// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package conversationsdb

import (
	"time"

	"github.com/google/uuid"
)

type Conversation struct {
	ID                    uuid.UUID
	UserID                uuid.UUID
	Title                 *string
	CreatedAt             time.Time
	UpdatedAt             time.Time
	MemoriesExtractedAt   *time.Time
	Kind                  string
	Summary               string
	ContextSummary        string
	ContextSummaryThrough *time.Time
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	Role           string
	Content        string
	Parts          []byte
	Usage          []byte
	Model          *string
	Provider       *string
	CreatedAt      time.Time
	EvidenceRefs   []string
	ToolCalls      []byte
	ToolResults    []byte
}
