// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package conversationsdb

import (
	"context"

	"github.com/google/uuid"
)

const appendMessage = `-- name: AppendMessage :one
INSERT INTO messages (conversation_id, role, content, parts, usage, model, provider, evidence_refs)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, conversation_id, role, content, parts, usage, model, provider, created_at, evidence_refs
`

type AppendMessageParams struct {
	ConversationID uuid.UUID
	Role           string
	Content        string
	Parts          []byte
	Usage          []byte
	Model          *string
	Provider       *string
	EvidenceRefs   []string
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, appendMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Parts,
		arg.Usage,
		arg.Model,
		arg.Provider,
		arg.EvidenceRefs,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.Parts,
		&i.Usage,
		&i.Model,
		&i.Provider,
		&i.CreatedAt,
		&i.EvidenceRefs,
	)
	return i, err
}

const countMessages = `-- name: CountMessages :one
SELECT count(*) FROM messages WHERE conversation_id = $1
`

func (q *Queries) CountMessages(ctx context.Context, conversationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessages, conversationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (user_id, title)
VALUES ($1, $2)
RETURNING id, user_id, title, created_at, updated_at
`

type CreateConversationParams struct {
	UserID uuid.UUID
	Title  *string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.UserID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations
WHERE id = $1 AND user_id = $2
`

type DeleteConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.UserID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, created_at, updated_at FROM conversations
WHERE id = $1 AND user_id = $2
`

type GetConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Scoped by user_id, not just id. Authorisation belongs in the query: a handler
// that forgets to check ownership then returns nothing rather than someone
// else's conversation.
func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, created_at, updated_at FROM conversations
WHERE user_id = $1
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListConversationsParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, conversation_id, role, content, parts, usage, model, provider, created_at, evidence_refs FROM messages
WHERE conversation_id = $1
ORDER BY created_at
LIMIT $2
`

type ListMessagesParams struct {
	ConversationID uuid.UUID
	Limit          int32
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Parts,
			&i.Usage,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.EvidenceRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentMessages = `-- name: RecentMessages :many
SELECT id, conversation_id, role, content, parts, usage, model, provider, created_at, evidence_refs FROM messages
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type RecentMessagesParams struct {
	ConversationID uuid.UUID
	Limit          int32
}

// The tail of a conversation, for the context builder. Selected newest-first so
// the limit keeps the most recent turns, then reversed in Go into reading
// order. Ordering oldest-first with a limit would return the beginning of the
// conversation, which is the opposite of what context needs.
func (q *Queries) RecentMessages(ctx context.Context, arg RecentMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, recentMessages, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Parts,
			&i.Usage,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.EvidenceRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recentUserMessages = `-- name: RecentUserMessages :many
SELECT m.id, m.conversation_id, m.role, m.content, m.parts, m.usage, m.model, m.provider, m.created_at, m.evidence_refs
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
WHERE c.user_id = $1 AND m.role = 'user'
ORDER BY m.created_at DESC
LIMIT $2
`

type RecentUserMessagesParams struct {
	UserID uuid.UUID
	Limit  int32
}

// The user's own recent messages across every conversation, so the coach has
// continuity even in a brand new one.
func (q *Queries) RecentUserMessages(ctx context.Context, arg RecentUserMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, recentUserMessages, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Parts,
			&i.Usage,
			&i.Model,
			&i.Provider,
			&i.CreatedAt,
			&i.EvidenceRefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationTitle = `-- name: SetConversationTitle :exec
UPDATE conversations
SET title = $2, updated_at = now()
WHERE id = $1
`

type SetConversationTitleParams struct {
	ID    uuid.UUID
	Title *string
}

func (q *Queries) SetConversationTitle(ctx context.Context, arg SetConversationTitleParams) error {
	_, err := q.db.Exec(ctx, setConversationTitle, arg.ID, arg.Title)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}
