// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package hydrationdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createHydrationEntry = `-- name: CreateHydrationEntry :one
INSERT INTO hydration_logs (user_id, log_date, amount_ml)
VALUES ($1, $2, $3)
RETURNING id, user_id, log_date, amount_ml, logged_at
`

type CreateHydrationEntryParams struct {
	UserID   uuid.UUID
	LogDate  pgtype.Date
	AmountMl int32
}

func (q *Queries) CreateHydrationEntry(ctx context.Context, arg CreateHydrationEntryParams) (HydrationLog, error) {
	row := q.db.QueryRow(ctx, createHydrationEntry, arg.UserID, arg.LogDate, arg.AmountMl)
	var i HydrationLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.AmountMl,
		&i.LoggedAt,
	)
	return i, err
}

const deleteHydrationEntry = `-- name: DeleteHydrationEntry :exec
DELETE FROM hydration_logs WHERE id = $1 AND user_id = $2
`

type DeleteHydrationEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteHydrationEntry(ctx context.Context, arg DeleteHydrationEntryParams) error {
	_, err := q.db.Exec(ctx, deleteHydrationEntry, arg.ID, arg.UserID)
	return err
}

const listHydrationEntriesForDate = `-- name: ListHydrationEntriesForDate :many
SELECT id, user_id, log_date, amount_ml, logged_at FROM hydration_logs
WHERE user_id = $1 AND log_date = $2
ORDER BY logged_at DESC
`

type ListHydrationEntriesForDateParams struct {
	UserID  uuid.UUID
	LogDate pgtype.Date
}

func (q *Queries) ListHydrationEntriesForDate(ctx context.Context, arg ListHydrationEntriesForDateParams) ([]HydrationLog, error) {
	rows, err := q.db.Query(ctx, listHydrationEntriesForDate, arg.UserID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HydrationLog{}
	for rows.Next() {
		var i HydrationLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.AmountMl,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumHydrationByDateSince = `-- name: SumHydrationByDateSince :many
SELECT
    log_date,
    COALESCE(SUM(amount_ml), 0)::bigint AS total_ml,
    COUNT(*)::bigint                    AS entry_count
FROM hydration_logs
WHERE user_id = $1 AND log_date >= $2
GROUP BY log_date
ORDER BY log_date DESC
`

type SumHydrationByDateSinceParams struct {
	UserID  uuid.UUID
	LogDate pgtype.Date
}

type SumHydrationByDateSinceRow struct {
	LogDate    pgtype.Date
	TotalMl    int64
	EntryCount int64
}

func (q *Queries) SumHydrationByDateSince(ctx context.Context, arg SumHydrationByDateSinceParams) ([]SumHydrationByDateSinceRow, error) {
	rows, err := q.db.Query(ctx, sumHydrationByDateSince, arg.UserID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumHydrationByDateSinceRow{}
	for rows.Next() {
		var i SumHydrationByDateSinceRow
		if err := rows.Scan(&i.LogDate, &i.TotalMl, &i.EntryCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumHydrationForDate = `-- name: SumHydrationForDate :one
SELECT
    COALESCE(SUM(amount_ml), 0)::bigint AS total_ml,
    COUNT(*)::bigint                    AS entry_count
FROM hydration_logs
WHERE user_id = $1 AND log_date = $2
`

type SumHydrationForDateParams struct {
	UserID  uuid.UUID
	LogDate pgtype.Date
}

type SumHydrationForDateRow struct {
	TotalMl    int64
	EntryCount int64
}

func (q *Queries) SumHydrationForDate(ctx context.Context, arg SumHydrationForDateParams) (SumHydrationForDateRow, error) {
	row := q.db.QueryRow(ctx, sumHydrationForDate, arg.UserID, arg.LogDate)
	var i SumHydrationForDateRow
	err := row.Scan(&i.TotalMl, &i.EntryCount)
	return i, err
}
