// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package messagingdb

import (
	"time"

	"github.com/google/uuid"
)

type MessagingLink struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Platform     string
	ExternalID   string
	LastUpdateID int64
	CreatedAt    time.Time
	LastSeenAt   *time.Time
	// The platform account (Telegram bot id) whose sequence last_update_id belongs to. Empty when the platform has no such notion.
	AccountID string
}
