// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package messagingdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimMessagingUpdate = `-- name: ClaimMessagingUpdate :one
UPDATE messaging_links
SET last_update_id = $3,
    account_id     = $4,
    last_seen_at   = now()
WHERE platform = $1
  AND external_id = $2
  AND ($3 > last_update_id OR account_id IS DISTINCT FROM $4)
RETURNING id, user_id, platform, external_id, last_update_id, created_at, last_seen_at, account_id
`

type ClaimMessagingUpdateParams struct {
	Platform     string
	ExternalID   string
	LastUpdateID int64
	AccountID    string
}

// ClaimMessagingUpdate resolves the sender and rejects a redelivery in one
// statement.
//
// These are the same question. An adapter acknowledges an update before it
// answers it, so the platform will redeliver anything whose acknowledgement
// was lost; doing the watermark check separately from the lookup would leave a
// window where two deliveries of one message both pass it. The predicate on
// last_update_id makes the advance the claim.
//
// No rows means one of two things — not linked, or already seen — and the
// caller distinguishes them with GetMessagingLink. Cheap, because that only
// happens off the common path.
// The account check is what makes a bot change safe. Update ids are a sequence
// per bot, so a different bot's ids are not comparable with this row's
// watermark at all — they are a new sequence that happens to start lower.
// Without this, swapping bots makes every existing link permanently deaf, and
// silently, because a lower id is indistinguishable from a redelivery.
//
// IS DISTINCT FROM rather than <>: it is the form that treats a first-ever
// claim on a legacy row the same as a genuine change.
func (q *Queries) ClaimMessagingUpdate(ctx context.Context, arg ClaimMessagingUpdateParams) (MessagingLink, error) {
	row := q.db.QueryRow(ctx, claimMessagingUpdate,
		arg.Platform,
		arg.ExternalID,
		arg.LastUpdateID,
		arg.AccountID,
	)
	var i MessagingLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ExternalID,
		&i.LastUpdateID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AccountID,
	)
	return i, err
}

const createMessagingLinkCode = `-- name: CreateMessagingLinkCode :exec
INSERT INTO messaging_link_codes (code_hash, user_id, platform, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateMessagingLinkCodeParams struct {
	CodeHash  []byte
	UserID    uuid.UUID
	Platform  string
	ExpiresAt time.Time
}

func (q *Queries) CreateMessagingLinkCode(ctx context.Context, arg CreateMessagingLinkCodeParams) error {
	_, err := q.db.Exec(ctx, createMessagingLinkCode,
		arg.CodeHash,
		arg.UserID,
		arg.Platform,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredMessagingLinkCodes = `-- name: DeleteExpiredMessagingLinkCodes :exec
DELETE FROM messaging_link_codes
WHERE expires_at < $1 AND redeemed_at IS NULL
`

// Housekeeping for codes nobody ever sent. Spent codes are kept: the tombstone
// is what lets a replay be recognised rather than merely missed.
func (q *Queries) DeleteExpiredMessagingLinkCodes(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredMessagingLinkCodes, expiresAt)
	return err
}

const deleteMessagingLink = `-- name: DeleteMessagingLink :execrows
DELETE FROM messaging_links
WHERE user_id = $1 AND platform = $2
`

type DeleteMessagingLinkParams struct {
	UserID   uuid.UUID
	Platform string
}

// Scoped by user_id as well as platform: this is reached from a form, and
// without the second predicate it would unlink by platform alone.
func (q *Queries) DeleteMessagingLink(ctx context.Context, arg DeleteMessagingLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMessagingLink, arg.UserID, arg.Platform)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMessagingLinkCodesForUser = `-- name: DeleteMessagingLinkCodesForUser :exec
DELETE FROM messaging_link_codes
WHERE user_id = $1 AND platform = $2
`

type DeleteMessagingLinkCodesForUserParams struct {
	UserID   uuid.UUID
	Platform string
}

// Issuing a code invalidates any earlier one for the same platform, so a
// person who asks twice cannot be confused about which of two codes is live,
// and an abandoned code stops being redeemable the moment it is replaced.
func (q *Queries) DeleteMessagingLinkCodesForUser(ctx context.Context, arg DeleteMessagingLinkCodesForUserParams) error {
	_, err := q.db.Exec(ctx, deleteMessagingLinkCodesForUser, arg.UserID, arg.Platform)
	return err
}

const getMessagingLink = `-- name: GetMessagingLink :one
SELECT id, user_id, platform, external_id, last_update_id, created_at, last_seen_at, account_id FROM messaging_links
WHERE platform = $1 AND external_id = $2
`

type GetMessagingLinkParams struct {
	Platform   string
	ExternalID string
}

func (q *Queries) GetMessagingLink(ctx context.Context, arg GetMessagingLinkParams) (MessagingLink, error) {
	row := q.db.QueryRow(ctx, getMessagingLink, arg.Platform, arg.ExternalID)
	var i MessagingLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ExternalID,
		&i.LastUpdateID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AccountID,
	)
	return i, err
}

const insertMessagingLink = `-- name: InsertMessagingLink :one
INSERT INTO messaging_links (user_id, platform, external_id, last_seen_at)
VALUES ($1, $2, $3, now())
RETURNING id, user_id, platform, external_id, last_update_id, created_at, last_seen_at, account_id
`

type InsertMessagingLinkParams struct {
	UserID     uuid.UUID
	Platform   string
	ExternalID string
}

// InsertMessagingLink deliberately has no ON CONFLICT clause.
//
// A chat that is already linked is not a race to paper over: linked to the
// same account it is a no-op, and linked to a different one it is somebody
// trying to attach a stranger's chat to their own account. Those need
// different answers, so the unique violation is raised and the caller decides
// — the same shape as linkGoogleIdentity in internal/auth.
func (q *Queries) InsertMessagingLink(ctx context.Context, arg InsertMessagingLinkParams) (MessagingLink, error) {
	row := q.db.QueryRow(ctx, insertMessagingLink, arg.UserID, arg.Platform, arg.ExternalID)
	var i MessagingLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ExternalID,
		&i.LastUpdateID,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.AccountID,
	)
	return i, err
}

const listMessagingLinksByUser = `-- name: ListMessagingLinksByUser :many
SELECT id, user_id, platform, external_id, last_update_id, created_at, last_seen_at, account_id FROM messaging_links
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListMessagingLinksByUser(ctx context.Context, userID uuid.UUID) ([]MessagingLink, error) {
	rows, err := q.db.Query(ctx, listMessagingLinksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagingLink{}
	for rows.Next() {
		var i MessagingLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.ExternalID,
			&i.LastUpdateID,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.AccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemMessagingLinkCode = `-- name: RedeemMessagingLinkCode :one
UPDATE messaging_link_codes
SET redeemed_at = now()
WHERE code_hash = $1
  AND platform = $2
  AND redeemed_at IS NULL
  AND expires_at > now()
RETURNING user_id
`

type RedeemMessagingLinkCodeParams struct {
	CodeHash []byte
	Platform string
}

// RedeemMessagingLinkCode spends a code and reports whose it was.
//
// Single use is enforced here rather than in Go: the UPDATE ... WHERE
// redeemed_at IS NULL is atomic, so two messages arriving with the same code
// can only produce one winner. Expiry is checked in the same predicate for the
// same reason.
func (q *Queries) RedeemMessagingLinkCode(ctx context.Context, arg RedeemMessagingLinkCodeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, redeemMessagingLinkCode, arg.CodeHash, arg.Platform)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
