// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package accountdb

import (
	"time"

	"github.com/google/uuid"
)

type AccountEvent struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Event     string
	Detail    []byte
	CreatedAt time.Time
}
