// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package memoriesdb

import (
	"time"

	"github.com/google/uuid"
)

type UserMemory struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	Category             string
	Content              string
	Status               string
	Pinned               bool
	Source               string
	SourceConversationID *uuid.UUID
	Confidence           *float32
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DeletedAt            *time.Time
	Excluded             bool
	// When this fact stopped being true. NULL means it still is.
	ValidTo *time.Time
	// The memory this one replaces. Set at extraction as a proposal; acted on when this row is approved.
	SupersedesID *uuid.UUID
}
