// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package memoriesdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPendingMemories = `-- name: CountPendingMemories :one
SELECT count(*)::int AS count
FROM user_memories
WHERE user_id = $1 AND deleted_at IS NULL AND status = 'pending'
`

func (q *Queries) CountPendingMemories(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingMemories, userID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createMemory = `-- name: CreateMemory :one
INSERT INTO user_memories (
    user_id, category, content, status, pinned, excluded, source, source_conversation_id, confidence,
    supersedes_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10
)
RETURNING id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id
`

type CreateMemoryParams struct {
	UserID               uuid.UUID
	Category             string
	Content              string
	Status               string
	Pinned               bool
	Excluded             bool
	Source               string
	SourceConversationID *uuid.UUID
	Confidence           *float32
	SupersedesID         *uuid.UUID
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (UserMemory, error) {
	row := q.db.QueryRow(ctx, createMemory,
		arg.UserID,
		arg.Category,
		arg.Content,
		arg.Status,
		arg.Pinned,
		arg.Excluded,
		arg.Source,
		arg.SourceConversationID,
		arg.Confidence,
		arg.SupersedesID,
	)
	var i UserMemory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Content,
		&i.Status,
		&i.Pinned,
		&i.Source,
		&i.SourceConversationID,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Excluded,
		&i.ValidTo,
		&i.SupersedesID,
	)
	return i, err
}

const getMemory = `-- name: GetMemory :one
SELECT id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id FROM user_memories
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetMemoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMemory(ctx context.Context, arg GetMemoryParams) (UserMemory, error) {
	row := q.db.QueryRow(ctx, getMemory, arg.ID, arg.UserID)
	var i UserMemory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Content,
		&i.Status,
		&i.Pinned,
		&i.Source,
		&i.SourceConversationID,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Excluded,
		&i.ValidTo,
		&i.SupersedesID,
	)
	return i, err
}

const listActiveContents = `-- name: ListActiveContents :many
SELECT lower(trim(content)) AS content
FROM user_memories
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status IN ('pending', 'approved')
  AND valid_to IS NULL
`

// Used to deduplicate extractions against what is already known or proposed.
//
// Retired facts are deliberately not in this set. People revert: someone who
// went back to training three days a week should be able to have that fact
// proposed again, and excluding superseded rows here is what allows it. The
// cost is that a fact can cycle, which is correct — it is what happened.
func (q *Queries) ListActiveContents(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveContents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var content string
		if err := rows.Scan(&content); err != nil {
			return nil, err
		}
		items = append(items, content)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedForContext = `-- name: ListApprovedForContext :many
SELECT id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id FROM user_memories
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status = 'approved'
  AND NOT excluded
  AND valid_to IS NULL
ORDER BY pinned DESC, updated_at DESC
LIMIT $2
`

type ListApprovedForContextParams struct {
	UserID uuid.UUID
	Limit  int32
}

// valid_to IS NULL keeps retired facts out of the prompt. A superseded fact is
// not deleted — it is history, and the review page still shows it — but the
// coach must never be told two contradicting things and left to pick.
func (q *Queries) ListApprovedForContext(ctx context.Context, arg ListApprovedForContextParams) ([]UserMemory, error) {
	rows, err := q.db.Query(ctx, listApprovedForContext, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserMemory{}
	for rows.Next() {
		var i UserMemory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Content,
			&i.Status,
			&i.Pinned,
			&i.Source,
			&i.SourceConversationID,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Excluded,
			&i.ValidTo,
			&i.SupersedesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentForSupersession = `-- name: ListCurrentForSupersession :many
SELECT id, category, content, pinned, updated_at
FROM user_memories
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status = 'approved'
  AND NOT excluded
  AND valid_to IS NULL
ORDER BY category, updated_at DESC
LIMIT $2
`

type ListCurrentForSupersessionParams struct {
	UserID uuid.UUID
	Limit  int32
}

type ListCurrentForSupersessionRow struct {
	ID        uuid.UUID
	Category  string
	Content   string
	Pinned    bool
	UpdatedAt time.Time
}

// The facts an extraction is allowed to propose replacing.
//
// Approved and current only. A pending fact is not yet believed, and a retired
// one is already gone; offering either to the model would invite it to
// supersede something that was never there.
//
// Pinned facts are included, because the model should still be able to say "this
// one is out of date" about them — SupersedeMemory is what refuses to act on it
// without a human. Leaving them out would instead teach the model that the fact
// does not exist, and it would file a contradicting duplicate.
func (q *Queries) ListCurrentForSupersession(ctx context.Context, arg ListCurrentForSupersessionParams) ([]ListCurrentForSupersessionRow, error) {
	rows, err := q.db.Query(ctx, listCurrentForSupersession, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentForSupersessionRow{}
	for rows.Next() {
		var i ListCurrentForSupersessionRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Content,
			&i.Pinned,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemories = `-- name: ListMemories :many
SELECT id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id FROM user_memories
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY
    pinned DESC,
    excluded ASC,
    CASE status WHEN 'pending' THEN 0 WHEN 'approved' THEN 1 ELSE 2 END,
    updated_at DESC
LIMIT $2
`

type ListMemoriesParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListMemories(ctx context.Context, arg ListMemoriesParams) ([]UserMemory, error) {
	rows, err := q.db.Query(ctx, listMemories, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserMemory{}
	for rows.Next() {
		var i UserMemory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Content,
			&i.Status,
			&i.Pinned,
			&i.Source,
			&i.SourceConversationID,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Excluded,
			&i.ValidTo,
			&i.SupersedesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByStatus = `-- name: ListMemoriesByStatus :many
SELECT id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id FROM user_memories
WHERE user_id = $1
  AND deleted_at IS NULL
  AND status = $2
ORDER BY pinned DESC, excluded ASC, updated_at DESC
LIMIT $3
`

type ListMemoriesByStatusParams struct {
	UserID uuid.UUID
	Status string
	Limit  int32
}

func (q *Queries) ListMemoriesByStatus(ctx context.Context, arg ListMemoriesByStatusParams) ([]UserMemory, error) {
	rows, err := q.db.Query(ctx, listMemoriesByStatus, arg.UserID, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserMemory{}
	for rows.Next() {
		var i UserMemory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Content,
			&i.Status,
			&i.Pinned,
			&i.Source,
			&i.SourceConversationID,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Excluded,
			&i.ValidTo,
			&i.SupersedesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingForConversation = `-- name: ListPendingForConversation :many
SELECT id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id FROM user_memories
WHERE user_id = $1
  AND source_conversation_id = $2
  AND status = 'pending'
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListPendingForConversationParams struct {
	UserID               uuid.UUID
	SourceConversationID *uuid.UUID
}

func (q *Queries) ListPendingForConversation(ctx context.Context, arg ListPendingForConversationParams) ([]UserMemory, error) {
	rows, err := q.db.Query(ctx, listPendingForConversation, arg.UserID, arg.SourceConversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserMemory{}
	for rows.Next() {
		var i UserMemory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Category,
			&i.Content,
			&i.Status,
			&i.Pinned,
			&i.Source,
			&i.SourceConversationID,
			&i.Confidence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Excluded,
			&i.ValidTo,
			&i.SupersedesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchApprovedForContext = `-- name: SearchApprovedForContext :many
WITH q AS (
    SELECT replace(
        websearch_to_tsquery('english', $3::text)::text,
        '&', '|'
    )::tsquery AS tsq
)
SELECT
    m.id,
    m.category,
    m.content,
    m.pinned,
    m.updated_at,
    ts_headline(
        'english',
        m.content,
        q.tsq,
        'StartSel=[, StopSel=], MaxWords=35, MinWords=15, ShortWord=3, HighlightAll=FALSE'
    )::text AS snippet,
    ts_rank_cd(to_tsvector('english', m.content), q.tsq, 32)::float8 AS rank
FROM user_memories m, q
WHERE m.user_id = $1
  AND m.deleted_at IS NULL
  AND m.status = 'approved'
  AND NOT m.excluded
  -- See ListApprovedForContext: retired facts stay out of the prompt, and this
  -- has to match, or which query ran would decide what the coach believes.
  AND m.valid_to IS NULL
  AND (
      m.pinned
      OR to_tsvector('english', m.content) @@ q.tsq
  )
ORDER BY m.pinned DESC, rank DESC, m.updated_at DESC
LIMIT $2
`

type SearchApprovedForContextParams struct {
	UserID      uuid.UUID
	ResultLimit int32
	Query       string
}

type SearchApprovedForContextRow struct {
	ID        uuid.UUID
	Category  string
	Content   string
	Pinned    bool
	UpdatedAt time.Time
	Snippet   string
	Rank      float64
}

// Approved facts ranked against what the user just said.
//
// Pinned facts are matched by `pinned OR ...` rather than being left to the
// ranking. A pinned fact is one the user explicitly said always matters, and
// letting a relevance score outvote that would be the coach forgetting on
// purpose — on the exact facts it was told never to.
//
// The tsvector expression must stay identical to the one indexed in
// migrations/20260808090000_add_memory_and_message_search.sql and mirrored in
// internal/search/rank.go, or this silently becomes a sequential scan.
//
// The query is a sentence someone said to a coach, not a search box, and that
// changes what the operator between the terms has to be. websearch_to_tsquery
// joins terms with AND, so "my shoulder hurts when I press overhead" only
// matches a fact containing every one of those words — which no fact does, so
// the whole thing retrieves nothing. Swapping AND for OR asks the question the
// caller actually meant: which stored facts touch any of this, best first.
//
// The swap is done on the parsed tsquery rather than on the user's text. The
// text has already been through websearch_to_tsquery by then, so it is a
// normalised expression of quoted lexemes, and replacing '&' cannot reach
// inside one. Phrase (<->) and negation (!) operators are left as they are.
func (q *Queries) SearchApprovedForContext(ctx context.Context, arg SearchApprovedForContextParams) ([]SearchApprovedForContextRow, error) {
	rows, err := q.db.Query(ctx, searchApprovedForContext, arg.UserID, arg.ResultLimit, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchApprovedForContextRow{}
	for rows.Next() {
		var i SearchApprovedForContextRow
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Content,
			&i.Pinned,
			&i.UpdatedAt,
			&i.Snippet,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMemoryExcluded = `-- name: SetMemoryExcluded :one
UPDATE user_memories
SET excluded   = $3,
    pinned     = false,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL AND status = 'approved'
RETURNING id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id
`

type SetMemoryExcludedParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Excluded bool
}

func (q *Queries) SetMemoryExcluded(ctx context.Context, arg SetMemoryExcludedParams) (UserMemory, error) {
	row := q.db.QueryRow(ctx, setMemoryExcluded, arg.ID, arg.UserID, arg.Excluded)
	var i UserMemory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Content,
		&i.Status,
		&i.Pinned,
		&i.Source,
		&i.SourceConversationID,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Excluded,
		&i.ValidTo,
		&i.SupersedesID,
	)
	return i, err
}

const setMemoryPinned = `-- name: SetMemoryPinned :one
UPDATE user_memories
SET pinned     = $3,
    excluded   = false,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL AND status = 'approved'
RETURNING id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id
`

type SetMemoryPinnedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Pinned bool
}

func (q *Queries) SetMemoryPinned(ctx context.Context, arg SetMemoryPinnedParams) (UserMemory, error) {
	row := q.db.QueryRow(ctx, setMemoryPinned, arg.ID, arg.UserID, arg.Pinned)
	var i UserMemory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Content,
		&i.Status,
		&i.Pinned,
		&i.Source,
		&i.SourceConversationID,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Excluded,
		&i.ValidTo,
		&i.SupersedesID,
	)
	return i, err
}

const setMemoryStatus = `-- name: SetMemoryStatus :one
UPDATE user_memories
SET status     = $3,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id
`

type SetMemoryStatusParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Status string
}

func (q *Queries) SetMemoryStatus(ctx context.Context, arg SetMemoryStatusParams) (UserMemory, error) {
	row := q.db.QueryRow(ctx, setMemoryStatus, arg.ID, arg.UserID, arg.Status)
	var i UserMemory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Content,
		&i.Status,
		&i.Pinned,
		&i.Source,
		&i.SourceConversationID,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Excluded,
		&i.ValidTo,
		&i.SupersedesID,
	)
	return i, err
}

const softDeleteMemory = `-- name: SoftDeleteMemory :execrows
UPDATE user_memories
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteMemoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) SoftDeleteMemory(ctx context.Context, arg SoftDeleteMemoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMemory, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeMemory = `-- name: SupersedeMemory :one
UPDATE user_memories
SET valid_to   = now(),
    updated_at = now()
WHERE id = $1
  AND user_id = $2
  AND deleted_at IS NULL
  AND status = 'approved'
  AND valid_to IS NULL
  AND NOT pinned
RETURNING id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id
`

type SupersedeMemoryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Retires one fact, at the moment its replacement was approved.
//
// Guards rather than trusts the caller. status = 'approved' because a pending
// fact was never believed and has nothing to retire; valid_to IS NULL so a
// second approval cannot move a date already set; and NOT pinned because a
// pinned fact is one the person said always matters, and retiring that on a
// model's suggestion is not a call this code gets to make.
func (q *Queries) SupersedeMemory(ctx context.Context, arg SupersedeMemoryParams) (UserMemory, error) {
	row := q.db.QueryRow(ctx, supersedeMemory, arg.ID, arg.UserID)
	var i UserMemory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Content,
		&i.Status,
		&i.Pinned,
		&i.Source,
		&i.SourceConversationID,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Excluded,
		&i.ValidTo,
		&i.SupersedesID,
	)
	return i, err
}

const updateMemory = `-- name: UpdateMemory :one
UPDATE user_memories
SET category   = $3,
    content    = $4,
    updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, category, content, status, pinned, source, source_conversation_id, confidence, created_at, updated_at, deleted_at, excluded, valid_to, supersedes_id
`

type UpdateMemoryParams struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Category string
	Content  string
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (UserMemory, error) {
	row := q.db.QueryRow(ctx, updateMemory,
		arg.ID,
		arg.UserID,
		arg.Category,
		arg.Content,
	)
	var i UserMemory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Category,
		&i.Content,
		&i.Status,
		&i.Pinned,
		&i.Source,
		&i.SourceConversationID,
		&i.Confidence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Excluded,
		&i.ValidTo,
		&i.SupersedesID,
	)
	return i, err
}
