// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package mealsdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserDiet = `-- name: AddUserDiet :exec
INSERT INTO user_diet_preferences (user_id, diet_id)
VALUES ($1, $2)
ON CONFLICT (user_id, diet_id) DO NOTHING
`

type AddUserDietParams struct {
	UserID uuid.UUID
	DietID uuid.UUID
}

func (q *Queries) AddUserDiet(ctx context.Context, arg AddUserDietParams) error {
	_, err := q.db.Exec(ctx, addUserDiet, arg.UserID, arg.DietID)
	return err
}

const clearMealPlanDayOverrides = `-- name: ClearMealPlanDayOverrides :exec
UPDATE meal_plan_days SET carb_type = NULL, carb_g = NULL, protein_g = NULL, fat_g = NULL
WHERE meal_plan_id = $1
`

func (q *Queries) ClearMealPlanDayOverrides(ctx context.Context, mealPlanID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearMealPlanDayOverrides, mealPlanID)
	return err
}

const createIngredient = `-- name: CreateIngredient :one

INSERT INTO ingredients (
    user_id, name, brand, category, serving_size_grams,
    calories_per_100g, protein_g_per_100g, fat_g_per_100g, saturated_fat_g_per_100g, carbs_g_per_100g,
    fiber_g_per_100g, sugar_g_per_100g, sodium_mg_per_100g, potassium_mg_per_100g, cholesterol_mg_per_100g
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, user_id, name, brand, category, serving_size_grams, calories_per_100g, protein_g_per_100g, fat_g_per_100g, carbs_g_per_100g, fiber_g_per_100g, sugar_g_per_100g, sodium_mg_per_100g, potassium_mg_per_100g, cholesterol_mg_per_100g, created_at, updated_at, saturated_fat_g_per_100g
`

type CreateIngredientParams struct {
	UserID               *uuid.UUID
	Name                 string
	Brand                string
	Category             string
	ServingSizeGrams     float64
	CaloriesPer100g      float64
	ProteinGPer100g      float64
	FatGPer100g          float64
	SaturatedFatGPer100g float64
	CarbsGPer100g        float64
	FiberGPer100g        float64
	SugarGPer100g        float64
	SodiumMgPer100g      float64
	PotassiumMgPer100g   float64
	CholesterolMgPer100g float64
}

// Ingredients
func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.UserID,
		arg.Name,
		arg.Brand,
		arg.Category,
		arg.ServingSizeGrams,
		arg.CaloriesPer100g,
		arg.ProteinGPer100g,
		arg.FatGPer100g,
		arg.SaturatedFatGPer100g,
		arg.CarbsGPer100g,
		arg.FiberGPer100g,
		arg.SugarGPer100g,
		arg.SodiumMgPer100g,
		arg.PotassiumMgPer100g,
		arg.CholesterolMgPer100g,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Brand,
		&i.Category,
		&i.ServingSizeGrams,
		&i.CaloriesPer100g,
		&i.ProteinGPer100g,
		&i.FatGPer100g,
		&i.CarbsGPer100g,
		&i.FiberGPer100g,
		&i.SugarGPer100g,
		&i.SodiumMgPer100g,
		&i.PotassiumMgPer100g,
		&i.CholesterolMgPer100g,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SaturatedFatGPer100g,
	)
	return i, err
}

const createMeal = `-- name: CreateMeal :one

INSERT INTO meals (meal_plan_id, day_id, name, meal_number)
VALUES ($1, $2, $3, (SELECT COALESCE(MAX(meal_number), 0) + 1 FROM meals WHERE day_id = $2))
RETURNING id, meal_plan_id, meal_number, name, total_macros, created_at, day_id
`

type CreateMealParams struct {
	MealPlanID uuid.UUID
	DayID      uuid.UUID
	Name       string
}

// Meals (within a day)
// Numbered after the day's last meal. Callers hold the plan's lock, so two
// meals added at once cannot take the same number.
func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal, arg.MealPlanID, arg.DayID, arg.Name)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.MealNumber,
		&i.Name,
		&i.TotalMacros,
		&i.CreatedAt,
		&i.DayID,
	)
	return i, err
}

const createMealIngredient = `-- name: CreateMealIngredient :one

INSERT INTO meal_ingredients (meal_id, ingredient_id, quantity_grams, calories, protein_g, fat_g, carbs_g)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, meal_id, ingredient_id, quantity_grams, calories, protein_g, fat_g, carbs_g, created_at
`

type CreateMealIngredientParams struct {
	MealID        uuid.UUID
	IngredientID  uuid.UUID
	QuantityGrams float64
	Calories      float64
	ProteinG      float64
	FatG          float64
	CarbsG        float64
}

// Meal ingredients
func (q *Queries) CreateMealIngredient(ctx context.Context, arg CreateMealIngredientParams) (MealIngredient, error) {
	row := q.db.QueryRow(ctx, createMealIngredient,
		arg.MealID,
		arg.IngredientID,
		arg.QuantityGrams,
		arg.Calories,
		arg.ProteinG,
		arg.FatG,
		arg.CarbsG,
	)
	var i MealIngredient
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.IngredientID,
		&i.QuantityGrams,
		&i.Calories,
		&i.ProteinG,
		&i.FatG,
		&i.CarbsG,
		&i.CreatedAt,
	)
	return i, err
}

const createMealPlan = `-- name: CreateMealPlan :one

INSERT INTO meal_plans (user_id, name, description, objective, activity_level, gender, plan_type, custom_carb_pct, mode)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, name, description, objective, activity_level, gender, total_macros, created_at, updated_at, plan_type, custom_carb_pct, mode
`

type CreateMealPlanParams struct {
	UserID        uuid.UUID
	Name          string
	Description   string
	Objective     string
	ActivityLevel string
	Gender        string
	PlanType      string
	CustomCarbPct *float64
	Mode          string
}

// Meal plans
func (q *Queries) CreateMealPlan(ctx context.Context, arg CreateMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, createMealPlan,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Objective,
		arg.ActivityLevel,
		arg.Gender,
		arg.PlanType,
		arg.CustomCarbPct,
		arg.Mode,
	)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Objective,
		&i.ActivityLevel,
		&i.Gender,
		&i.TotalMacros,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanType,
		&i.CustomCarbPct,
		&i.Mode,
	)
	return i, err
}

const createMealPlanDay = `-- name: CreateMealPlanDay :one

INSERT INTO meal_plan_days (meal_plan_id, weekday) VALUES ($1, $2) RETURNING id, meal_plan_id, weekday, carb_type, carb_g, protein_g, fat_g, created_at
`

type CreateMealPlanDayParams struct {
	MealPlanID uuid.UUID
	Weekday    int16
}

// Days (within a plan)
func (q *Queries) CreateMealPlanDay(ctx context.Context, arg CreateMealPlanDayParams) (MealPlanDay, error) {
	row := q.db.QueryRow(ctx, createMealPlanDay, arg.MealPlanID, arg.Weekday)
	var i MealPlanDay
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.Weekday,
		&i.CarbType,
		&i.CarbG,
		&i.ProteinG,
		&i.FatG,
		&i.CreatedAt,
	)
	return i, err
}

const createMealReminder = `-- name: CreateMealReminder :one

INSERT INTO meal_reminders (user_id, label, time_of_day, days_of_week)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, label, time_of_day, days_of_week, enabled, last_fired_local_date, created_at, updated_at
`

type CreateMealReminderParams struct {
	UserID     uuid.UUID
	Label      string
	TimeOfDay  string
	DaysOfWeek []int16
}

// Meal reminders
func (q *Queries) CreateMealReminder(ctx context.Context, arg CreateMealReminderParams) (MealReminder, error) {
	row := q.db.QueryRow(ctx, createMealReminder,
		arg.UserID,
		arg.Label,
		arg.TimeOfDay,
		arg.DaysOfWeek,
	)
	var i MealReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.TimeOfDay,
		&i.DaysOfWeek,
		&i.Enabled,
		&i.LastFiredLocalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const dailyFoodLogTotals = `-- name: DailyFoodLogTotals :one
SELECT
    COALESCE(SUM(calories), 0)::double precision  AS calories,
    COALESCE(SUM(protein_g), 0)::double precision AS protein_g,
    COALESCE(SUM(fat_g), 0)::double precision     AS fat_g,
    COALESCE(SUM(carbs_g), 0)::double precision   AS carbs_g
FROM food_logs
WHERE user_id = $1 AND log_date = $2
`

type DailyFoodLogTotalsParams struct {
	UserID  uuid.UUID
	LogDate pgtype.Date
}

type DailyFoodLogTotalsRow struct {
	Calories float64
	ProteinG float64
	FatG     float64
	CarbsG   float64
}

func (q *Queries) DailyFoodLogTotals(ctx context.Context, arg DailyFoodLogTotalsParams) (DailyFoodLogTotalsRow, error) {
	row := q.db.QueryRow(ctx, dailyFoodLogTotals, arg.UserID, arg.LogDate)
	var i DailyFoodLogTotalsRow
	err := row.Scan(
		&i.Calories,
		&i.ProteinG,
		&i.FatG,
		&i.CarbsG,
	)
	return i, err
}

const deleteFoodLog = `-- name: DeleteFoodLog :exec
DELETE FROM food_logs WHERE id = $1 AND user_id = $2
`

type DeleteFoodLogParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFoodLog(ctx context.Context, arg DeleteFoodLogParams) error {
	_, err := q.db.Exec(ctx, deleteFoodLog, arg.ID, arg.UserID)
	return err
}

const deleteIngredient = `-- name: DeleteIngredient :exec
DELETE FROM ingredients WHERE id = $1 AND user_id = $2
`

type DeleteIngredientParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

func (q *Queries) DeleteIngredient(ctx context.Context, arg DeleteIngredientParams) error {
	_, err := q.db.Exec(ctx, deleteIngredient, arg.ID, arg.UserID)
	return err
}

const deleteMealIngredient = `-- name: DeleteMealIngredient :exec
DELETE FROM meal_ingredients WHERE id = $1
`

func (q *Queries) DeleteMealIngredient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMealIngredient, id)
	return err
}

const deleteMealOwned = `-- name: DeleteMealOwned :exec
DELETE FROM meals
USING meal_plans
WHERE meals.id = $1 AND meals.meal_plan_id = meal_plans.id AND meal_plans.user_id = $2
`

type DeleteMealOwnedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMealOwned(ctx context.Context, arg DeleteMealOwnedParams) error {
	_, err := q.db.Exec(ctx, deleteMealOwned, arg.ID, arg.UserID)
	return err
}

const deleteMealPlan = `-- name: DeleteMealPlan :exec
DELETE FROM meal_plans WHERE id = $1 AND user_id = $2
`

type DeleteMealPlanParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMealPlan(ctx context.Context, arg DeleteMealPlanParams) error {
	_, err := q.db.Exec(ctx, deleteMealPlan, arg.ID, arg.UserID)
	return err
}

const deleteMealPlanDay = `-- name: DeleteMealPlanDay :exec
DELETE FROM meal_plan_days WHERE id = $1
`

func (q *Queries) DeleteMealPlanDay(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMealPlanDay, id)
	return err
}

const deleteMealReminder = `-- name: DeleteMealReminder :exec
DELETE FROM meal_reminders WHERE id = $1 AND user_id = $2
`

type DeleteMealReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMealReminder(ctx context.Context, arg DeleteMealReminderParams) error {
	_, err := q.db.Exec(ctx, deleteMealReminder, arg.ID, arg.UserID)
	return err
}

const deleteUserDiets = `-- name: DeleteUserDiets :exec
DELETE FROM user_diet_preferences WHERE user_id = $1
`

func (q *Queries) DeleteUserDiets(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserDiets, userID)
	return err
}

const getIngredient = `-- name: GetIngredient :one
SELECT id, user_id, name, brand, category, serving_size_grams, calories_per_100g, protein_g_per_100g, fat_g_per_100g, carbs_g_per_100g, fiber_g_per_100g, sugar_g_per_100g, sodium_mg_per_100g, potassium_mg_per_100g, cholesterol_mg_per_100g, created_at, updated_at, saturated_fat_g_per_100g FROM ingredients
WHERE id = $1 AND (user_id IS NULL OR user_id = $2)
`

type GetIngredientParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

// Visible ingredients are the shared/global set plus the user's own, the same
// rule SearchIngredients applies. Reading one by id used to skip that check,
// which let a hand-crafted ingredient_id on the food-log, meal-plan and capture
// commit forms snapshot another account's private food into the caller's own
// row — leaking its name and full macro profile.
func (q *Queries) GetIngredient(ctx context.Context, arg GetIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredient, arg.ID, arg.UserID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Brand,
		&i.Category,
		&i.ServingSizeGrams,
		&i.CaloriesPer100g,
		&i.ProteinGPer100g,
		&i.FatGPer100g,
		&i.CarbsGPer100g,
		&i.FiberGPer100g,
		&i.SugarGPer100g,
		&i.SodiumMgPer100g,
		&i.PotassiumMgPer100g,
		&i.CholesterolMgPer100g,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SaturatedFatGPer100g,
	)
	return i, err
}

const getMealIngredientOwned = `-- name: GetMealIngredientOwned :one
SELECT mi.id, mi.meal_id, mi.ingredient_id, mi.quantity_grams, mi.calories, mi.protein_g, mi.fat_g, mi.carbs_g, mi.created_at, mi.meal_id AS owned_meal_id
FROM meal_ingredients mi
JOIN meals m ON m.id = mi.meal_id
JOIN meal_plans mp ON mp.id = m.meal_plan_id
WHERE mi.id = $1 AND mp.user_id = $2
`

type GetMealIngredientOwnedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

type GetMealIngredientOwnedRow struct {
	ID            uuid.UUID
	MealID        uuid.UUID
	IngredientID  uuid.UUID
	QuantityGrams float64
	Calories      float64
	ProteinG      float64
	FatG          float64
	CarbsG        float64
	CreatedAt     time.Time
	OwnedMealID   uuid.UUID
}

// Ownership is via meal -> plan, two joins deep.
func (q *Queries) GetMealIngredientOwned(ctx context.Context, arg GetMealIngredientOwnedParams) (GetMealIngredientOwnedRow, error) {
	row := q.db.QueryRow(ctx, getMealIngredientOwned, arg.ID, arg.UserID)
	var i GetMealIngredientOwnedRow
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.IngredientID,
		&i.QuantityGrams,
		&i.Calories,
		&i.ProteinG,
		&i.FatG,
		&i.CarbsG,
		&i.CreatedAt,
		&i.OwnedMealID,
	)
	return i, err
}

const getMealOwned = `-- name: GetMealOwned :one
SELECT m.id, m.meal_plan_id, m.meal_number, m.name, m.total_macros, m.created_at, m.day_id FROM meals m
JOIN meal_plans mp ON mp.id = m.meal_plan_id
WHERE m.id = $1 AND mp.user_id = $2
`

type GetMealOwnedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Ownership is via the parent plan, so a stranger holding the exact meal id
// still finds nothing.
func (q *Queries) GetMealOwned(ctx context.Context, arg GetMealOwnedParams) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealOwned, arg.ID, arg.UserID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.MealNumber,
		&i.Name,
		&i.TotalMacros,
		&i.CreatedAt,
		&i.DayID,
	)
	return i, err
}

const getMealPlan = `-- name: GetMealPlan :one
SELECT id, user_id, name, description, objective, activity_level, gender, total_macros, created_at, updated_at, plan_type, custom_carb_pct, mode FROM meal_plans WHERE id = $1 AND user_id = $2
`

type GetMealPlanParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMealPlan(ctx context.Context, arg GetMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, getMealPlan, arg.ID, arg.UserID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Objective,
		&i.ActivityLevel,
		&i.Gender,
		&i.TotalMacros,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanType,
		&i.CustomCarbPct,
		&i.Mode,
	)
	return i, err
}

const getMealPlanDayOwned = `-- name: GetMealPlanDayOwned :one
SELECT d.id, d.meal_plan_id, d.weekday, d.carb_type, d.carb_g, d.protein_g, d.fat_g, d.created_at FROM meal_plan_days d
JOIN meal_plans mp ON mp.id = d.meal_plan_id
WHERE d.id = $1 AND mp.user_id = $2
`

type GetMealPlanDayOwnedParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMealPlanDayOwned(ctx context.Context, arg GetMealPlanDayOwnedParams) (MealPlanDay, error) {
	row := q.db.QueryRow(ctx, getMealPlanDayOwned, arg.ID, arg.UserID)
	var i MealPlanDay
	err := row.Scan(
		&i.ID,
		&i.MealPlanID,
		&i.Weekday,
		&i.CarbType,
		&i.CarbG,
		&i.ProteinG,
		&i.FatG,
		&i.CreatedAt,
	)
	return i, err
}

const getMealReminder = `-- name: GetMealReminder :one
SELECT id, user_id, label, time_of_day, days_of_week, enabled, last_fired_local_date, created_at, updated_at FROM meal_reminders WHERE id = $1 AND user_id = $2
`

type GetMealReminderParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetMealReminder(ctx context.Context, arg GetMealReminderParams) (MealReminder, error) {
	row := q.db.QueryRow(ctx, getMealReminder, arg.ID, arg.UserID)
	var i MealReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.TimeOfDay,
		&i.DaysOfWeek,
		&i.Enabled,
		&i.LastFiredLocalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFoodLog = `-- name: InsertFoodLog :one

INSERT INTO food_logs (user_id, log_date, meal_id, ingredient_id, quantity_grams, label, calories, protein_g, fat_g, carbs_g)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, log_date, meal_id, ingredient_id, quantity_grams, label, calories, protein_g, fat_g, carbs_g, logged_at
`

type InsertFoodLogParams struct {
	UserID        uuid.UUID
	LogDate       pgtype.Date
	MealID        *uuid.UUID
	IngredientID  *uuid.UUID
	QuantityGrams *float64
	Label         string
	Calories      float64
	ProteinG      float64
	FatG          float64
	CarbsG        float64
}

// Food logs
func (q *Queries) InsertFoodLog(ctx context.Context, arg InsertFoodLogParams) (FoodLog, error) {
	row := q.db.QueryRow(ctx, insertFoodLog,
		arg.UserID,
		arg.LogDate,
		arg.MealID,
		arg.IngredientID,
		arg.QuantityGrams,
		arg.Label,
		arg.Calories,
		arg.ProteinG,
		arg.FatG,
		arg.CarbsG,
	)
	var i FoodLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.MealID,
		&i.IngredientID,
		&i.QuantityGrams,
		&i.Label,
		&i.Calories,
		&i.ProteinG,
		&i.FatG,
		&i.CarbsG,
		&i.LoggedAt,
	)
	return i, err
}

const listDiets = `-- name: ListDiets :many

SELECT id, code, name, description FROM diets ORDER BY name
`

// Diets
func (q *Queries) ListDiets(ctx context.Context) ([]Diet, error) {
	rows, err := q.db.Query(ctx, listDiets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Diet{}
	for rows.Next() {
		var i Diet
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodLogsByDate = `-- name: ListFoodLogsByDate :many
SELECT id, user_id, log_date, meal_id, ingredient_id, quantity_grams, label, calories, protein_g, fat_g, carbs_g, logged_at FROM food_logs WHERE user_id = $1 AND log_date = $2 ORDER BY logged_at
`

type ListFoodLogsByDateParams struct {
	UserID  uuid.UUID
	LogDate pgtype.Date
}

func (q *Queries) ListFoodLogsByDate(ctx context.Context, arg ListFoodLogsByDateParams) ([]FoodLog, error) {
	rows, err := q.db.Query(ctx, listFoodLogsByDate, arg.UserID, arg.LogDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodLog{}
	for rows.Next() {
		var i FoodLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.MealID,
			&i.IngredientID,
			&i.QuantityGrams,
			&i.Label,
			&i.Calories,
			&i.ProteinG,
			&i.FatG,
			&i.CarbsG,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoodLogsByRange = `-- name: ListFoodLogsByRange :many
SELECT id, user_id, log_date, meal_id, ingredient_id, quantity_grams, label, calories, protein_g, fat_g, carbs_g, logged_at FROM food_logs WHERE user_id = $1 AND log_date BETWEEN $2 AND $3 ORDER BY log_date, logged_at
`

type ListFoodLogsByRangeParams struct {
	UserID    uuid.UUID
	LogDate   pgtype.Date
	LogDate_2 pgtype.Date
}

func (q *Queries) ListFoodLogsByRange(ctx context.Context, arg ListFoodLogsByRangeParams) ([]FoodLog, error) {
	rows, err := q.db.Query(ctx, listFoodLogsByRange, arg.UserID, arg.LogDate, arg.LogDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FoodLog{}
	for rows.Next() {
		var i FoodLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.MealID,
			&i.IngredientID,
			&i.QuantityGrams,
			&i.Label,
			&i.Calories,
			&i.ProteinG,
			&i.FatG,
			&i.CarbsG,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealIngredients = `-- name: ListMealIngredients :many
SELECT mi.id, mi.meal_id, mi.ingredient_id, mi.quantity_grams, mi.calories, mi.protein_g, mi.fat_g, mi.carbs_g, mi.created_at, i.name AS ingredient_name
FROM meal_ingredients mi
JOIN ingredients i ON i.id = mi.ingredient_id
WHERE mi.meal_id = $1
ORDER BY mi.created_at
`

type ListMealIngredientsRow struct {
	ID             uuid.UUID
	MealID         uuid.UUID
	IngredientID   uuid.UUID
	QuantityGrams  float64
	Calories       float64
	ProteinG       float64
	FatG           float64
	CarbsG         float64
	CreatedAt      time.Time
	IngredientName string
}

// ingredient_name is denormalized for display without a second round trip.
func (q *Queries) ListMealIngredients(ctx context.Context, mealID uuid.UUID) ([]ListMealIngredientsRow, error) {
	rows, err := q.db.Query(ctx, listMealIngredients, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMealIngredientsRow{}
	for rows.Next() {
		var i ListMealIngredientsRow
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.IngredientID,
			&i.QuantityGrams,
			&i.Calories,
			&i.ProteinG,
			&i.FatG,
			&i.CarbsG,
			&i.CreatedAt,
			&i.IngredientName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlanDays = `-- name: ListMealPlanDays :many
SELECT id, meal_plan_id, weekday, carb_type, carb_g, protein_g, fat_g, created_at FROM meal_plan_days WHERE meal_plan_id = $1 ORDER BY (weekday + 6) % 7
`

// Monday first.
func (q *Queries) ListMealPlanDays(ctx context.Context, mealPlanID uuid.UUID) ([]MealPlanDay, error) {
	rows, err := q.db.Query(ctx, listMealPlanDays, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealPlanDay{}
	for rows.Next() {
		var i MealPlanDay
		if err := rows.Scan(
			&i.ID,
			&i.MealPlanID,
			&i.Weekday,
			&i.CarbType,
			&i.CarbG,
			&i.ProteinG,
			&i.FatG,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlanDaysByUser = `-- name: ListMealPlanDaysByUser :many
SELECT d.id, d.meal_plan_id, d.weekday, d.carb_type, d.carb_g, d.protein_g, d.fat_g, d.created_at FROM meal_plan_days d
JOIN meal_plans mp ON mp.id = d.meal_plan_id
WHERE mp.user_id = $1
ORDER BY d.meal_plan_id, (d.weekday + 6) % 7
`

func (q *Queries) ListMealPlanDaysByUser(ctx context.Context, userID uuid.UUID) ([]MealPlanDay, error) {
	rows, err := q.db.Query(ctx, listMealPlanDaysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealPlanDay{}
	for rows.Next() {
		var i MealPlanDay
		if err := rows.Scan(
			&i.ID,
			&i.MealPlanID,
			&i.Weekday,
			&i.CarbType,
			&i.CarbG,
			&i.ProteinG,
			&i.FatG,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealPlans = `-- name: ListMealPlans :many
SELECT id, user_id, name, description, objective, activity_level, gender, total_macros, created_at, updated_at, plan_type, custom_carb_pct, mode FROM meal_plans WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListMealPlans(ctx context.Context, userID uuid.UUID) ([]MealPlan, error) {
	rows, err := q.db.Query(ctx, listMealPlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealPlan{}
	for rows.Next() {
		var i MealPlan
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Objective,
			&i.ActivityLevel,
			&i.Gender,
			&i.TotalMacros,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PlanType,
			&i.CustomCarbPct,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealReminders = `-- name: ListMealReminders :many
SELECT id, user_id, label, time_of_day, days_of_week, enabled, last_fired_local_date, created_at, updated_at FROM meal_reminders WHERE user_id = $1 ORDER BY time_of_day
`

func (q *Queries) ListMealReminders(ctx context.Context, userID uuid.UUID) ([]MealReminder, error) {
	rows, err := q.db.Query(ctx, listMealReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealReminder{}
	for rows.Next() {
		var i MealReminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.TimeOfDay,
			&i.DaysOfWeek,
			&i.Enabled,
			&i.LastFiredLocalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMealsByPlan = `-- name: ListMealsByPlan :many
SELECT id, meal_plan_id, meal_number, name, total_macros, created_at, day_id FROM meals WHERE meal_plan_id = $1 ORDER BY day_id, meal_number
`

func (q *Queries) ListMealsByPlan(ctx context.Context, mealPlanID uuid.UUID) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMealsByPlan, mealPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meal{}
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.MealPlanID,
			&i.MealNumber,
			&i.Name,
			&i.TotalMacros,
			&i.CreatedAt,
			&i.DayID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotYetFiredMealReminders = `-- name: ListNotYetFiredMealReminders :many
SELECT id, user_id, label, time_of_day, days_of_week, enabled, last_fired_local_date, created_at, updated_at FROM meal_reminders
WHERE user_id = $1 AND enabled AND (last_fired_local_date IS DISTINCT FROM $2::date)
`

type ListNotYetFiredMealRemindersParams struct {
	UserID   uuid.UUID
	AsOfDate pgtype.Date
}

// Candidates for today: enabled, and not already marked fired for this local
// date. Day-of-week and time-of-day matching happens in Go via Reminder.DueOn,
// which keeps that logic in one place instead of splitting it across SQL and
// Go.
func (q *Queries) ListNotYetFiredMealReminders(ctx context.Context, arg ListNotYetFiredMealRemindersParams) ([]MealReminder, error) {
	rows, err := q.db.Query(ctx, listNotYetFiredMealReminders, arg.UserID, arg.AsOfDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MealReminder{}
	for rows.Next() {
		var i MealReminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.TimeOfDay,
			&i.DaysOfWeek,
			&i.Enabled,
			&i.LastFiredLocalDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMealPlan = `-- name: LockMealPlan :one
SELECT id, user_id, name, description, objective, activity_level, gender, total_macros, created_at, updated_at, plan_type, custom_carb_pct, mode FROM meal_plans WHERE id = $1 AND user_id = $2 FOR UPDATE
`

type LockMealPlanParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Taken at the start of every checked change, so two changes to one plan
// cannot each pass the overage check and together go over.
func (q *Queries) LockMealPlan(ctx context.Context, arg LockMealPlanParams) (MealPlan, error) {
	row := q.db.QueryRow(ctx, lockMealPlan, arg.ID, arg.UserID)
	var i MealPlan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Objective,
		&i.ActivityLevel,
		&i.Gender,
		&i.TotalMacros,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PlanType,
		&i.CustomCarbPct,
		&i.Mode,
	)
	return i, err
}

const markMealReminderFired = `-- name: MarkMealReminderFired :exec
UPDATE meal_reminders SET last_fired_local_date = $2, updated_at = now() WHERE id = $1
`

type MarkMealReminderFiredParams struct {
	ID                 uuid.UUID
	LastFiredLocalDate pgtype.Date
}

func (q *Queries) MarkMealReminderFired(ctx context.Context, arg MarkMealReminderFiredParams) error {
	_, err := q.db.Exec(ctx, markMealReminderFired, arg.ID, arg.LastFiredLocalDate)
	return err
}

const removeUserDiet = `-- name: RemoveUserDiet :exec
DELETE FROM user_diet_preferences WHERE user_id = $1 AND diet_id = $2
`

type RemoveUserDietParams struct {
	UserID uuid.UUID
	DietID uuid.UUID
}

func (q *Queries) RemoveUserDiet(ctx context.Context, arg RemoveUserDietParams) error {
	_, err := q.db.Exec(ctx, removeUserDiet, arg.UserID, arg.DietID)
	return err
}

const searchIngredients = `-- name: SearchIngredients :many
SELECT id, user_id, name, brand, category, serving_size_grams, calories_per_100g, protein_g_per_100g, fat_g_per_100g, carbs_g_per_100g, fiber_g_per_100g, sugar_g_per_100g, sodium_mg_per_100g, potassium_mg_per_100g, cholesterol_mg_per_100g, created_at, updated_at, saturated_fat_g_per_100g FROM ingredients
WHERE (user_id IS NULL OR user_id = $1)
  AND lower(name) LIKE ALL ($2::text[])
ORDER BY name
LIMIT $3
`

type SearchIngredientsParams struct {
	UserID   *uuid.UUID
	Patterns []string
	MaxRows  int32
}

// Visible ingredients are the shared/global set plus the user's own.
//
// patterns holds one LIKE pattern per word, already lowercased and escaped, and
// a name must contain every one of them. Word by word rather than one
// substring so "chicken breast" finds "Breast, chicken" — a spoken or typed
// name rarely arrives in the catalog's word order.
func (q *Queries) SearchIngredients(ctx context.Context, arg SearchIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, searchIngredients, arg.UserID, arg.Patterns, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ingredient{}
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Brand,
			&i.Category,
			&i.ServingSizeGrams,
			&i.CaloriesPer100g,
			&i.ProteinGPer100g,
			&i.FatGPer100g,
			&i.CarbsGPer100g,
			&i.FiberGPer100g,
			&i.SugarGPer100g,
			&i.SodiumMgPer100g,
			&i.PotassiumMgPer100g,
			&i.CholesterolMgPer100g,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SaturatedFatGPer100g,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMealReminderEnabled = `-- name: SetMealReminderEnabled :one
UPDATE meal_reminders SET enabled = $3, updated_at = now() WHERE id = $1 AND user_id = $2
RETURNING id, user_id, label, time_of_day, days_of_week, enabled, last_fired_local_date, created_at, updated_at
`

type SetMealReminderEnabledParams struct {
	ID      uuid.UUID
	UserID  uuid.UUID
	Enabled bool
}

func (q *Queries) SetMealReminderEnabled(ctx context.Context, arg SetMealReminderEnabledParams) (MealReminder, error) {
	row := q.db.QueryRow(ctx, setMealReminderEnabled, arg.ID, arg.UserID, arg.Enabled)
	var i MealReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.TimeOfDay,
		&i.DaysOfWeek,
		&i.Enabled,
		&i.LastFiredLocalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sumMealIngredientMacros = `-- name: SumMealIngredientMacros :one
SELECT
    COALESCE(SUM(calories), 0)::double precision  AS calories,
    COALESCE(SUM(protein_g), 0)::double precision AS protein_g,
    COALESCE(SUM(fat_g), 0)::double precision     AS fat_g,
    COALESCE(SUM(carbs_g), 0)::double precision   AS carbs_g
FROM meal_ingredients
WHERE meal_id = $1
`

type SumMealIngredientMacrosRow struct {
	Calories float64
	ProteinG float64
	FatG     float64
	CarbsG   float64
}

func (q *Queries) SumMealIngredientMacros(ctx context.Context, mealID uuid.UUID) (SumMealIngredientMacrosRow, error) {
	row := q.db.QueryRow(ctx, sumMealIngredientMacros, mealID)
	var i SumMealIngredientMacrosRow
	err := row.Scan(
		&i.Calories,
		&i.ProteinG,
		&i.FatG,
		&i.CarbsG,
	)
	return i, err
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients
SET name = $3, brand = $4, category = $5, serving_size_grams = $6,
    calories_per_100g = $7, protein_g_per_100g = $8, fat_g_per_100g = $9, saturated_fat_g_per_100g = $10,
    carbs_g_per_100g = $11, fiber_g_per_100g = $12, sugar_g_per_100g = $13, sodium_mg_per_100g = $14,
    potassium_mg_per_100g = $15, cholesterol_mg_per_100g = $16, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, brand, category, serving_size_grams, calories_per_100g, protein_g_per_100g, fat_g_per_100g, carbs_g_per_100g, fiber_g_per_100g, sugar_g_per_100g, sodium_mg_per_100g, potassium_mg_per_100g, cholesterol_mg_per_100g, created_at, updated_at, saturated_fat_g_per_100g
`

type UpdateIngredientParams struct {
	ID                   uuid.UUID
	UserID               *uuid.UUID
	Name                 string
	Brand                string
	Category             string
	ServingSizeGrams     float64
	CaloriesPer100g      float64
	ProteinGPer100g      float64
	FatGPer100g          float64
	SaturatedFatGPer100g float64
	CarbsGPer100g        float64
	FiberGPer100g        float64
	SugarGPer100g        float64
	SodiumMgPer100g      float64
	PotassiumMgPer100g   float64
	CholesterolMgPer100g float64
}

// Only a user's own ingredients can be edited; shared ones are read-only to
// everyone, which this WHERE clause enforces by requiring ownership.
func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Brand,
		arg.Category,
		arg.ServingSizeGrams,
		arg.CaloriesPer100g,
		arg.ProteinGPer100g,
		arg.FatGPer100g,
		arg.SaturatedFatGPer100g,
		arg.CarbsGPer100g,
		arg.FiberGPer100g,
		arg.SugarGPer100g,
		arg.SodiumMgPer100g,
		arg.PotassiumMgPer100g,
		arg.CholesterolMgPer100g,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Brand,
		&i.Category,
		&i.ServingSizeGrams,
		&i.CaloriesPer100g,
		&i.ProteinGPer100g,
		&i.FatGPer100g,
		&i.CarbsGPer100g,
		&i.FiberGPer100g,
		&i.SugarGPer100g,
		&i.SodiumMgPer100g,
		&i.PotassiumMgPer100g,
		&i.CholesterolMgPer100g,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SaturatedFatGPer100g,
	)
	return i, err
}

const updateMealPlanDay = `-- name: UpdateMealPlanDay :exec
UPDATE meal_plan_days SET carb_type = $2, carb_g = $3, protein_g = $4, fat_g = $5 WHERE id = $1
`

type UpdateMealPlanDayParams struct {
	ID       uuid.UUID
	CarbType *string
	CarbG    *float64
	ProteinG *float64
	FatG     *float64
}

func (q *Queries) UpdateMealPlanDay(ctx context.Context, arg UpdateMealPlanDayParams) error {
	_, err := q.db.Exec(ctx, updateMealPlanDay,
		arg.ID,
		arg.CarbType,
		arg.CarbG,
		arg.ProteinG,
		arg.FatG,
	)
	return err
}

const updateMealPlanSettings = `-- name: UpdateMealPlanSettings :exec
UPDATE meal_plans
SET name = $2, description = $3, plan_type = $4, custom_carb_pct = $5, mode = $6, updated_at = now()
WHERE id = $1
`

type UpdateMealPlanSettingsParams struct {
	ID            uuid.UUID
	Name          string
	Description   string
	PlanType      string
	CustomCarbPct *float64
	Mode          string
}

func (q *Queries) UpdateMealPlanSettings(ctx context.Context, arg UpdateMealPlanSettingsParams) error {
	_, err := q.db.Exec(ctx, updateMealPlanSettings,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PlanType,
		arg.CustomCarbPct,
		arg.Mode,
	)
	return err
}

const updateMealPlanTotalMacros = `-- name: UpdateMealPlanTotalMacros :exec
UPDATE meal_plans SET total_macros = $2, updated_at = now() WHERE id = $1
`

type UpdateMealPlanTotalMacrosParams struct {
	ID          uuid.UUID
	TotalMacros []byte
}

func (q *Queries) UpdateMealPlanTotalMacros(ctx context.Context, arg UpdateMealPlanTotalMacrosParams) error {
	_, err := q.db.Exec(ctx, updateMealPlanTotalMacros, arg.ID, arg.TotalMacros)
	return err
}

const updateMealReminder = `-- name: UpdateMealReminder :one
UPDATE meal_reminders
SET label = $3, time_of_day = $4, days_of_week = $5, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, label, time_of_day, days_of_week, enabled, last_fired_local_date, created_at, updated_at
`

type UpdateMealReminderParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Label      string
	TimeOfDay  string
	DaysOfWeek []int16
}

func (q *Queries) UpdateMealReminder(ctx context.Context, arg UpdateMealReminderParams) (MealReminder, error) {
	row := q.db.QueryRow(ctx, updateMealReminder,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.TimeOfDay,
		arg.DaysOfWeek,
	)
	var i MealReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.TimeOfDay,
		&i.DaysOfWeek,
		&i.Enabled,
		&i.LastFiredLocalDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMealTotalMacros = `-- name: UpdateMealTotalMacros :exec
UPDATE meals SET total_macros = $2 WHERE id = $1
`

type UpdateMealTotalMacrosParams struct {
	ID          uuid.UUID
	TotalMacros []byte
}

func (q *Queries) UpdateMealTotalMacros(ctx context.Context, arg UpdateMealTotalMacrosParams) error {
	_, err := q.db.Exec(ctx, updateMealTotalMacros, arg.ID, arg.TotalMacros)
	return err
}

const userDiets = `-- name: UserDiets :many
SELECT d.id, d.code, d.name, d.description FROM diets d
JOIN user_diet_preferences udp ON udp.diet_id = d.id
WHERE udp.user_id = $1
ORDER BY d.name
`

func (q *Queries) UserDiets(ctx context.Context, userID uuid.UUID) ([]Diet, error) {
	rows, err := q.db.Query(ctx, userDiets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Diet{}
	for rows.Next() {
		var i Diet
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
