// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package mcpauthdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeAuthorizationCode = `-- name: ConsumeAuthorizationCode :execrows
UPDATE mcp_authorization_codes
SET consumed_at = now(), connection_id = $2
WHERE code_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

type ConsumeAuthorizationCodeParams struct {
	CodeHash     []byte
	ConnectionID *uuid.UUID
}

func (q *Queries) ConsumeAuthorizationCode(ctx context.Context, arg ConsumeAuthorizationCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeAuthorizationCode, arg.CodeHash, arg.ConnectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeAuthorizationRequest = `-- name: ConsumeAuthorizationRequest :execrows
UPDATE mcp_authorization_requests
SET consumed_at = now()
WHERE id = $1
  AND verifier_hash = $2
  AND consumed_at IS NULL
  AND expires_at > now()
`

type ConsumeAuthorizationRequestParams struct {
	ID           uuid.UUID
	VerifierHash []byte
}

// ConsumeAuthorizationRequest closes a request so Approve cannot be replayed.
//
// execrows rather than exec: the caller needs to know it won the race, because
// two Approve posts from a double-clicked button must not mint two codes.
func (q *Queries) ConsumeAuthorizationRequest(ctx context.Context, arg ConsumeAuthorizationRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeAuthorizationRequest, arg.ID, arg.VerifierHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :execrows
UPDATE mcp_refresh_tokens
SET consumed_at = now(), replaced_by = $2
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
`

type ConsumeRefreshTokenParams struct {
	TokenHash  []byte
	ReplacedBy *uuid.UUID
}

func (q *Queries) ConsumeRefreshToken(ctx context.Context, arg ConsumeRefreshTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRefreshToken, arg.TokenHash, arg.ReplacedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeRefreshTokensForConnection = `-- name: ConsumeRefreshTokensForConnection :execrows
UPDATE mcp_refresh_tokens
SET consumed_at = now()
WHERE connection_id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeRefreshTokensForConnection(ctx context.Context, connectionID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRefreshTokensForConnection, connectionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOAuthClients = `-- name: CountOAuthClients :one
SELECT count(*) FROM mcp_oauth_clients
`

func (q *Queries) CountOAuthClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOAuthClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredAuthorizationCodes = `-- name: DeleteExpiredAuthorizationCodes :execrows
DELETE FROM mcp_authorization_codes
WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredAuthorizationCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthorizationCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAuthorizationRequests = `-- name: DeleteExpiredAuthorizationRequests :execrows
DELETE FROM mcp_authorization_requests
WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredAuthorizationRequests(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAuthorizationRequests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM mcp_refresh_tokens
WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUnusedOAuthClients = `-- name: DeleteUnusedOAuthClients :execrows
DELETE FROM mcp_oauth_clients c
WHERE c.created_at < now() - interval '30 days'
  AND NOT EXISTS (
      SELECT 1 FROM agent_connections a
      WHERE a.oauth_client_id = c.id
  )
`

// DeleteUnusedOAuthClients removes registrations that never produced a grant.
//
// Open registration means anyone can create a row, and a native client
// registers a new one on every launch because its callback port changes. This
// is what keeps that bounded without a human deciding anything.
func (q *Queries) DeleteUnusedOAuthClients(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedOAuthClients)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAuthorizationCode = `-- name: GetAuthorizationCode :one
SELECT code_hash, client_id, user_id, redirect_uri, code_challenge, code_challenge_method, scope, resource, created_at, expires_at, consumed_at, connection_id FROM mcp_authorization_codes
WHERE code_hash = $1
`

// GetAuthorizationCode reads a code whether or not it has been used.
//
// Deliberately unfiltered on consumed_at: presenting an already-consumed code
// must revoke the whole grant (RFC 6749 section 10.5), and a query that hid
// the row could not tell that case apart from a code that never existed.
func (q *Queries) GetAuthorizationCode(ctx context.Context, codeHash []byte) (McpAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCode, codeHash)
	var i McpAuthorizationCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scope,
		&i.Resource,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConnectionID,
	)
	return i, err
}

const getAuthorizationRequest = `-- name: GetAuthorizationRequest :one
SELECT id, client_id, redirect_uri, state, code_challenge, code_challenge_method, scope, resource, verifier_hash, account_created, created_at, expires_at, consumed_at FROM mcp_authorization_requests
WHERE id = $1
  AND verifier_hash = $2
  AND consumed_at IS NULL
  AND expires_at > now()
`

type GetAuthorizationRequestParams struct {
	ID           uuid.UUID
	VerifierHash []byte
}

// GetAuthorizationRequest reads a parked request that is still usable.
//
// The verifier hash is a predicate rather than a value compared afterwards, so
// a guessed request id finds nothing at all: without it, anyone who could
// guess an id could have a victim approve a request they started.
func (q *Queries) GetAuthorizationRequest(ctx context.Context, arg GetAuthorizationRequestParams) (McpAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, getAuthorizationRequest, arg.ID, arg.VerifierHash)
	var i McpAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scope,
		&i.Resource,
		&i.VerifierHash,
		&i.AccountCreated,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, client_name, redirect_uris, grant_types, software_id, dedupe_key, created_at, last_used_at FROM mcp_oauth_clients
WHERE id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.SoftwareID,
		&i.DedupeKey,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getOAuthClientByDedupeKey = `-- name: GetOAuthClientByDedupeKey :one
SELECT id, client_name, redirect_uris, grant_types, software_id, dedupe_key, created_at, last_used_at FROM mcp_oauth_clients
WHERE dedupe_key = $1
`

// GetOAuthClientByDedupeKey returns an identical earlier registration.
//
// A client that registers twice with the same metadata gets its existing row
// back instead of a new one. This dedupes a web client with a stable callback;
// it deliberately does not dedupe a native client whose callback port changes
// every launch, which is what the sweep is for.
func (q *Queries) GetOAuthClientByDedupeKey(ctx context.Context, dedupeKey []byte) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByDedupeKey, dedupeKey)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.SoftwareID,
		&i.DedupeKey,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, connection_id, token_hash, created_at, expires_at, consumed_at, replaced_by FROM mcp_refresh_tokens
WHERE token_hash = $1
`

// Unfiltered on consumed_at for the same reason as the authorization code:
// reuse of a consumed refresh token revokes the grant, so the row has to be
// findable after it has been spent.
func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (McpRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i McpRefreshToken
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const insertAuthorizationCode = `-- name: InsertAuthorizationCode :one
INSERT INTO mcp_authorization_codes (
    code_hash, client_id, user_id, redirect_uri, code_challenge,
    code_challenge_method, scope, resource, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING code_hash, client_id, user_id, redirect_uri, code_challenge, code_challenge_method, scope, resource, created_at, expires_at, consumed_at, connection_id
`

type InsertAuthorizationCodeParams struct {
	CodeHash            []byte
	ClientID            string
	UserID              uuid.UUID
	RedirectUri         string
	CodeChallenge       string
	CodeChallengeMethod string
	Scope               string
	Resource            string
	ExpiresAt           time.Time
}

func (q *Queries) InsertAuthorizationCode(ctx context.Context, arg InsertAuthorizationCodeParams) (McpAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, insertAuthorizationCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Scope,
		arg.Resource,
		arg.ExpiresAt,
	)
	var i McpAuthorizationCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scope,
		&i.Resource,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ConnectionID,
	)
	return i, err
}

const insertAuthorizationRequest = `-- name: InsertAuthorizationRequest :one
INSERT INTO mcp_authorization_requests (
    client_id, redirect_uri, state, code_challenge, code_challenge_method,
    scope, resource, verifier_hash, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, client_id, redirect_uri, state, code_challenge, code_challenge_method, scope, resource, verifier_hash, account_created, created_at, expires_at, consumed_at
`

type InsertAuthorizationRequestParams struct {
	ClientID            string
	RedirectUri         string
	State               string
	CodeChallenge       string
	CodeChallengeMethod string
	Scope               string
	Resource            string
	VerifierHash        []byte
	ExpiresAt           time.Time
}

func (q *Queries) InsertAuthorizationRequest(ctx context.Context, arg InsertAuthorizationRequestParams) (McpAuthorizationRequest, error) {
	row := q.db.QueryRow(ctx, insertAuthorizationRequest,
		arg.ClientID,
		arg.RedirectUri,
		arg.State,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Scope,
		arg.Resource,
		arg.VerifierHash,
		arg.ExpiresAt,
	)
	var i McpAuthorizationRequest
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.RedirectUri,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Scope,
		&i.Resource,
		&i.VerifierHash,
		&i.AccountCreated,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const insertOAuthClient = `-- name: InsertOAuthClient :one
INSERT INTO mcp_oauth_clients (id, client_name, redirect_uris, grant_types, software_id, dedupe_key)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, client_name, redirect_uris, grant_types, software_id, dedupe_key, created_at, last_used_at
`

type InsertOAuthClientParams struct {
	ID           string
	ClientName   string
	RedirectUris []string
	GrantTypes   []string
	SoftwareID   string
	DedupeKey    []byte
}

func (q *Queries) InsertOAuthClient(ctx context.Context, arg InsertOAuthClientParams) (McpOauthClient, error) {
	row := q.db.QueryRow(ctx, insertOAuthClient,
		arg.ID,
		arg.ClientName,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.SoftwareID,
		arg.DedupeKey,
	)
	var i McpOauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientName,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.SoftwareID,
		&i.DedupeKey,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO mcp_refresh_tokens (connection_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, connection_id, token_hash, created_at, expires_at, consumed_at, replaced_by
`

type InsertRefreshTokenParams struct {
	ConnectionID uuid.UUID
	TokenHash    []byte
	ExpiresAt    time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (McpRefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.ConnectionID, arg.TokenHash, arg.ExpiresAt)
	var i McpRefreshToken
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const linkReplacedRefreshToken = `-- name: LinkReplacedRefreshToken :exec
UPDATE mcp_refresh_tokens
SET replaced_by = $2
WHERE token_hash = $1
`

type LinkReplacedRefreshTokenParams struct {
	TokenHash  []byte
	ReplacedBy *uuid.UUID
}

// LinkReplacedRefreshToken records which token superseded a spent one.
//
// A separate statement because the replacement cannot exist before the row it
// replaces has been claimed: consuming first is what stops a race from leaving
// two live refresh tokens, so the chain is recorded a moment later.
func (q *Queries) LinkReplacedRefreshToken(ctx context.Context, arg LinkReplacedRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, linkReplacedRefreshToken, arg.TokenHash, arg.ReplacedBy)
	return err
}

const markAuthorizationRequestAccountCreated = `-- name: MarkAuthorizationRequestAccountCreated :exec
UPDATE mcp_authorization_requests
SET account_created = true
WHERE id = $1 AND verifier_hash = $2
`

type MarkAuthorizationRequestAccountCreatedParams struct {
	ID           uuid.UUID
	VerifierHash []byte
}

func (q *Queries) MarkAuthorizationRequestAccountCreated(ctx context.Context, arg MarkAuthorizationRequestAccountCreatedParams) error {
	_, err := q.db.Exec(ctx, markAuthorizationRequestAccountCreated, arg.ID, arg.VerifierHash)
	return err
}

const touchOAuthClient = `-- name: TouchOAuthClient :exec
UPDATE mcp_oauth_clients
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchOAuthClient(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchOAuthClient, id)
	return err
}
