// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package integrationsdb

import (
	"time"

	"github.com/google/uuid"
)

type IntegrationConnection struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Provider      string
	Endpoint      string
	TokenSealed   []byte
	Status        string
	LastError     string
	LastCheckedAt *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
