// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package integrationsdb

import (
	"context"

	"github.com/google/uuid"
)

const deleteIntegrationConnection = `-- name: DeleteIntegrationConnection :exec
DELETE FROM integration_connections
WHERE user_id = $1 AND provider = $2
`

type DeleteIntegrationConnectionParams struct {
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) DeleteIntegrationConnection(ctx context.Context, arg DeleteIntegrationConnectionParams) error {
	_, err := q.db.Exec(ctx, deleteIntegrationConnection, arg.UserID, arg.Provider)
	return err
}

const getIntegrationConnection = `-- name: GetIntegrationConnection :one
SELECT id, user_id, provider, endpoint, token_sealed, status, last_error, last_checked_at, created_at, updated_at FROM integration_connections
WHERE user_id = $1 AND provider = $2
`

type GetIntegrationConnectionParams struct {
	UserID   uuid.UUID
	Provider string
}

func (q *Queries) GetIntegrationConnection(ctx context.Context, arg GetIntegrationConnectionParams) (IntegrationConnection, error) {
	row := q.db.QueryRow(ctx, getIntegrationConnection, arg.UserID, arg.Provider)
	var i IntegrationConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Endpoint,
		&i.TokenSealed,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markIntegrationChecked = `-- name: MarkIntegrationChecked :exec
UPDATE integration_connections
SET status          = $3,
    last_error      = $4,
    last_checked_at = now(),
    updated_at      = now()
WHERE user_id = $1 AND provider = $2
`

type MarkIntegrationCheckedParams struct {
	UserID    uuid.UUID
	Provider  string
	Status    string
	LastError string
}

// Records the outcome of the last attempt to reach the server, so the settings
// page can say "not reachable" instead of leaving somebody to guess.
func (q *Queries) MarkIntegrationChecked(ctx context.Context, arg MarkIntegrationCheckedParams) error {
	_, err := q.db.Exec(ctx, markIntegrationChecked,
		arg.UserID,
		arg.Provider,
		arg.Status,
		arg.LastError,
	)
	return err
}

const upsertIntegrationConnection = `-- name: UpsertIntegrationConnection :one
INSERT INTO integration_connections (user_id, provider, endpoint, token_sealed, status, last_error)
VALUES ($1, $2, $3, $4, 'ok', '')
ON CONFLICT (user_id, provider) DO UPDATE
SET endpoint     = EXCLUDED.endpoint,
    token_sealed = EXCLUDED.token_sealed,
    status       = 'ok',
    last_error   = '',
    updated_at   = now()
RETURNING id, user_id, provider, endpoint, token_sealed, status, last_error, last_checked_at, created_at, updated_at
`

type UpsertIntegrationConnectionParams struct {
	UserID      uuid.UUID
	Provider    string
	Endpoint    string
	TokenSealed []byte
}

// Connecting again replaces the endpoint and token rather than adding a second
// row: "connect my calendar" is a statement about one calendar.
func (q *Queries) UpsertIntegrationConnection(ctx context.Context, arg UpsertIntegrationConnectionParams) (IntegrationConnection, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationConnection,
		arg.UserID,
		arg.Provider,
		arg.Endpoint,
		arg.TokenSealed,
	)
	var i IntegrationConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.Endpoint,
		&i.TokenSealed,
		&i.Status,
		&i.LastError,
		&i.LastCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
