// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package milestonesdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MilestoneTracker struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Name           string
	LastDoneOn     pgtype.Date
	IntervalMonths *int16
	CreatedAt      time.Time
}
