// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package milestonesdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestone_trackers (user_id, name, last_done_on, interval_months)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, last_done_on, interval_months, created_at
`

type CreateMilestoneParams struct {
	UserID         uuid.UUID
	Name           string
	LastDoneOn     pgtype.Date
	IntervalMonths *int16
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (MilestoneTracker, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.UserID,
		arg.Name,
		arg.LastDoneOn,
		arg.IntervalMonths,
	)
	var i MilestoneTracker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LastDoneOn,
		&i.IntervalMonths,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :execrows
DELETE FROM milestone_trackers WHERE id = $1 AND user_id = $2
`

type DeleteMilestoneParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMilestone(ctx context.Context, arg DeleteMilestoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMilestone, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listMilestones = `-- name: ListMilestones :many
SELECT id, user_id, name, last_done_on, interval_months, created_at FROM milestone_trackers WHERE user_id = $1 ORDER BY created_at, name
`

func (q *Queries) ListMilestones(ctx context.Context, userID uuid.UUID) ([]MilestoneTracker, error) {
	rows, err := q.db.Query(ctx, listMilestones, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MilestoneTracker{}
	for rows.Next() {
		var i MilestoneTracker
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.LastDoneOn,
			&i.IntervalMonths,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMilestoneDone = `-- name: MarkMilestoneDone :one
UPDATE milestone_trackers SET last_done_on = $3
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, last_done_on, interval_months, created_at
`

type MarkMilestoneDoneParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	LastDoneOn pgtype.Date
}

func (q *Queries) MarkMilestoneDone(ctx context.Context, arg MarkMilestoneDoneParams) (MilestoneTracker, error) {
	row := q.db.QueryRow(ctx, markMilestoneDone, arg.ID, arg.UserID, arg.LastDoneOn)
	var i MilestoneTracker
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LastDoneOn,
		&i.IntervalMonths,
		&i.CreatedAt,
	)
	return i, err
}
