// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package lighterdaydb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getChoice = `-- name: GetChoice :one
SELECT choice FROM lighter_days WHERE user_id = $1 AND day = $2
`

type GetChoiceParams struct {
	UserID uuid.UUID
	Day    pgtype.Date
}

func (q *Queries) GetChoice(ctx context.Context, arg GetChoiceParams) (string, error) {
	row := q.db.QueryRow(ctx, getChoice, arg.UserID, arg.Day)
	var choice string
	err := row.Scan(&choice)
	return choice, err
}

const setChoice = `-- name: SetChoice :exec
INSERT INTO lighter_days (user_id, day, choice) VALUES ($1, $2, $3)
ON CONFLICT (user_id, day) DO UPDATE SET choice = EXCLUDED.choice, decided_at = now()
`

type SetChoiceParams struct {
	UserID uuid.UUID
	Day    pgtype.Date
	Choice string
}

func (q *Queries) SetChoice(ctx context.Context, arg SetChoiceParams) error {
	_, err := q.db.Exec(ctx, setChoice, arg.UserID, arg.Day, arg.Choice)
	return err
}
