// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sorenessdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SorenessLog struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	LogDate  pgtype.Date
	Region   string
	Severity int16
	Note     string
	LoggedAt time.Time
}
