// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package preferencesdb

import (
	"time"

	"github.com/google/uuid"
)

type UserPreference struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	UnitsSystem       string
	DefaultGoal       string
	DefaultMacroSplit string
	UpdatedAt         time.Time
}
