// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package preferencesdb

import (
	"context"

	"github.com/google/uuid"
)

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT id, user_id, units_system, default_goal, default_macro_split, updated_at FROM user_preferences WHERE user_id = $1
`

func (q *Queries) GetUserPreferences(ctx context.Context, userID uuid.UUID) (UserPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreferences, userID)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UnitsSystem,
		&i.DefaultGoal,
		&i.DefaultMacroSplit,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :one
INSERT INTO user_preferences (user_id, units_system, default_goal, default_macro_split)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET units_system = $2, default_goal = $3, default_macro_split = $4, updated_at = now()
RETURNING id, user_id, units_system, default_goal, default_macro_split, updated_at
`

type UpsertUserPreferencesParams struct {
	UserID            uuid.UUID
	UnitsSystem       string
	DefaultGoal       string
	DefaultMacroSplit string
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) (UserPreference, error) {
	row := q.db.QueryRow(ctx, upsertUserPreferences,
		arg.UserID,
		arg.UnitsSystem,
		arg.DefaultGoal,
		arg.DefaultMacroSplit,
	)
	var i UserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UnitsSystem,
		&i.DefaultGoal,
		&i.DefaultMacroSplit,
		&i.UpdatedAt,
	)
	return i, err
}
