// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package caffeinedb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCaffeineEntry = `-- name: CreateCaffeineEntry :one
INSERT INTO caffeine_logs (user_id, log_date, mg, label, logged_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, log_date, mg, label, logged_at
`

type CreateCaffeineEntryParams struct {
	UserID   uuid.UUID
	LogDate  pgtype.Date
	Mg       int32
	Label    string
	LoggedAt time.Time
}

func (q *Queries) CreateCaffeineEntry(ctx context.Context, arg CreateCaffeineEntryParams) (CaffeineLog, error) {
	row := q.db.QueryRow(ctx, createCaffeineEntry,
		arg.UserID,
		arg.LogDate,
		arg.Mg,
		arg.Label,
		arg.LoggedAt,
	)
	var i CaffeineLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LogDate,
		&i.Mg,
		&i.Label,
		&i.LoggedAt,
	)
	return i, err
}

const deleteCaffeineEntry = `-- name: DeleteCaffeineEntry :execrows
DELETE FROM caffeine_logs WHERE id = $1 AND user_id = $2
`

type DeleteCaffeineEntryParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteCaffeineEntry(ctx context.Context, arg DeleteCaffeineEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCaffeineEntry, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCaffeineBetween = `-- name: ListCaffeineBetween :many
SELECT id, user_id, log_date, mg, label, logged_at FROM caffeine_logs
WHERE user_id = $1 AND logged_at >= $2 AND logged_at < $3
ORDER BY logged_at DESC
`

type ListCaffeineBetweenParams struct {
	UserID     uuid.UUID
	LoggedAt   time.Time
	LoggedAt_2 time.Time
}

// Half-open [since, until) on when it was drunk, newest first.
func (q *Queries) ListCaffeineBetween(ctx context.Context, arg ListCaffeineBetweenParams) ([]CaffeineLog, error) {
	rows, err := q.db.Query(ctx, listCaffeineBetween, arg.UserID, arg.LoggedAt, arg.LoggedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaffeineLog{}
	for rows.Next() {
		var i CaffeineLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LogDate,
			&i.Mg,
			&i.Label,
			&i.LoggedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
