// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package supplementsdb

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type SupplementLog struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	LogDate   pgtype.Date
	Name      string
	Count     int16
	Nutrients []string
	LoggedAt  time.Time
}
