// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package spenddb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnpricedGenerations = `-- name: CountUnpricedGenerations :one
SELECT count(*) FROM ai_generations
WHERE created_at >= $1
  AND created_at < $2
  AND byok = false
  AND cost_micros = 0
  AND (input_tokens > 0 OR output_tokens > 0)
`

type CountUnpricedGenerationsParams struct {
	FromTime time.Time
	ToTime   time.Time
}

// Calls recorded with no price. A non-zero answer means the pricing table is
// missing a model and every total below is an understatement.
func (q *Queries) CountUnpricedGenerations(ctx context.Context, arg CountUnpricedGenerationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpricedGenerations, arg.FromTime, arg.ToTime)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recordGeneration = `-- name: RecordGeneration :exec
INSERT INTO ai_generations (
    user_id, surface, provider, model,
    input_tokens, output_tokens, cost_micros, byok
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8
)
`

type RecordGenerationParams struct {
	UserID       *uuid.UUID
	Surface      string
	Provider     string
	Model        *string
	InputTokens  int32
	OutputTokens int32
	CostMicros   int64
	Byok         bool
}

// Appends one model call to the ledger. Fire-and-forget: the caller has already
// served the user by the time this runs, and a failed insert must never turn a
// successful reply into an error.
func (q *Queries) RecordGeneration(ctx context.Context, arg RecordGenerationParams) error {
	_, err := q.db.Exec(ctx, recordGeneration,
		arg.UserID,
		arg.Surface,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CostMicros,
		arg.Byok,
	)
	return err
}

const spendByModel = `-- name: SpendByModel :many
SELECT
    provider,
    model,
    count(*)                    AS generations,
    sum(input_tokens)::bigint   AS input_tokens,
    sum(output_tokens)::bigint  AS output_tokens,
    sum(cost_micros)::bigint    AS cost_micros
FROM ai_generations
WHERE created_at >= $1
  AND created_at < $2
  AND (NOT $3::boolean OR byok = false)
GROUP BY provider, model
ORDER BY sum(cost_micros) DESC
`

type SpendByModelParams struct {
	FromTime     time.Time
	ToTime       time.Time
	BillableOnly bool
}

type SpendByModelRow struct {
	Provider     string
	Model        *string
	Generations  int64
	InputTokens  int64
	OutputTokens int64
	CostMicros   int64
}

// What the money went on. Answers whether a price is wrong before it answers
// anything about a customer.
func (q *Queries) SpendByModel(ctx context.Context, arg SpendByModelParams) ([]SpendByModelRow, error) {
	rows, err := q.db.Query(ctx, spendByModel, arg.FromTime, arg.ToTime, arg.BillableOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByModelRow{}
	for rows.Next() {
		var i SpendByModelRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.Generations,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendBySurface = `-- name: SpendBySurface :many
SELECT
    surface,
    count(*)                    AS generations,
    sum(input_tokens)::bigint   AS input_tokens,
    sum(output_tokens)::bigint  AS output_tokens,
    sum(cost_micros)::bigint    AS cost_micros
FROM ai_generations
WHERE created_at >= $1
  AND created_at < $2
  AND (NOT $3::boolean OR byok = false)
GROUP BY surface
ORDER BY sum(cost_micros) DESC
`

type SpendBySurfaceParams struct {
	FromTime     time.Time
	ToTime       time.Time
	BillableOnly bool
}

type SpendBySurfaceRow struct {
	Surface      string
	Generations  int64
	InputTokens  int64
	OutputTokens int64
	CostMicros   int64
}

// Which part of the product spends. This is the split that says whether the
// answer is chat or the scheduled sweeps.
func (q *Queries) SpendBySurface(ctx context.Context, arg SpendBySurfaceParams) ([]SpendBySurfaceRow, error) {
	rows, err := q.db.Query(ctx, spendBySurface, arg.FromTime, arg.ToTime, arg.BillableOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendBySurfaceRow{}
	for rows.Next() {
		var i SpendBySurfaceRow
		if err := rows.Scan(
			&i.Surface,
			&i.Generations,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendByUser = `-- name: SpendByUser :many
SELECT
    user_id,
    count(*)                    AS generations,
    sum(input_tokens)::bigint   AS input_tokens,
    sum(output_tokens)::bigint  AS output_tokens,
    sum(cost_micros)::bigint    AS cost_micros
FROM ai_generations
WHERE created_at >= $1
  AND created_at < $2
  AND (NOT $3::boolean OR byok = false)
GROUP BY user_id
ORDER BY sum(cost_micros) DESC
`

type SpendByUserParams struct {
	FromTime     time.Time
	ToTime       time.Time
	BillableOnly bool
}

type SpendByUserRow struct {
	UserID       *uuid.UUID
	Generations  int64
	InputTokens  int64
	OutputTokens int64
	CostMicros   int64
}

// Total spend per account over a window, most expensive first. NULL user_id
// rows group together as the unattributed bucket.
func (q *Queries) SpendByUser(ctx context.Context, arg SpendByUserParams) ([]SpendByUserRow, error) {
	rows, err := q.db.Query(ctx, spendByUser, arg.FromTime, arg.ToTime, arg.BillableOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpendByUserRow{}
	for rows.Next() {
		var i SpendByUserRow
		if err := rows.Scan(
			&i.UserID,
			&i.Generations,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CostMicros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
