// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	TokenHash  []byte
	UserID     uuid.UUID
	ExpiresAt  time.Time
	CreatedAt  time.Time
	LastSeenAt time.Time
	UserAgent  *string
	Ip         *netip.Addr
}

type User struct {
	ID            uuid.UUID
	Email         string
	PasswordHash  string
	DisplayName   string
	Timezone      string
	CoachingStyle *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
