// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package habitsdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeHabit = `-- name: CompleteHabit :exec
INSERT INTO habit_completions (habit_id, user_id, local_date)
VALUES ($1, $2, $3)
ON CONFLICT (habit_id, local_date) DO NOTHING
`

type CompleteHabitParams struct {
	HabitID   uuid.UUID
	UserID    uuid.UUID
	LocalDate pgtype.Date
}

func (q *Queries) CompleteHabit(ctx context.Context, arg CompleteHabitParams) error {
	_, err := q.db.Exec(ctx, completeHabit, arg.HabitID, arg.UserID, arg.LocalDate)
	return err
}

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (user_id, name, domain, days_of_week)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, domain, days_of_week, active, created_at, updated_at
`

type CreateHabitParams struct {
	UserID     uuid.UUID
	Name       string
	Domain     string
	DaysOfWeek []int16
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, createHabit,
		arg.UserID,
		arg.Name,
		arg.Domain,
		arg.DaysOfWeek,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.DaysOfWeek,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits WHERE id = $1 AND user_id = $2
`

type DeleteHabitParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteHabit(ctx context.Context, arg DeleteHabitParams) error {
	_, err := q.db.Exec(ctx, deleteHabit, arg.ID, arg.UserID)
	return err
}

const getHabit = `-- name: GetHabit :one
SELECT id, user_id, name, domain, days_of_week, active, created_at, updated_at FROM habits WHERE id = $1 AND user_id = $2
`

type GetHabitParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetHabit(ctx context.Context, arg GetHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, getHabit, arg.ID, arg.UserID)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.DaysOfWeek,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompletionDatesSince = `-- name: ListCompletionDatesSince :many
SELECT habit_id, local_date
FROM habit_completions
WHERE user_id = $1 AND local_date >= $2
ORDER BY local_date DESC
`

type ListCompletionDatesSinceParams struct {
	UserID    uuid.UUID
	LocalDate pgtype.Date
}

type ListCompletionDatesSinceRow struct {
	HabitID   uuid.UUID
	LocalDate pgtype.Date
}

func (q *Queries) ListCompletionDatesSince(ctx context.Context, arg ListCompletionDatesSinceParams) ([]ListCompletionDatesSinceRow, error) {
	rows, err := q.db.Query(ctx, listCompletionDatesSince, arg.UserID, arg.LocalDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletionDatesSinceRow{}
	for rows.Next() {
		var i ListCompletionDatesSinceRow
		if err := rows.Scan(&i.HabitID, &i.LocalDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHabits = `-- name: ListHabits :many
SELECT id, user_id, name, domain, days_of_week, active, created_at, updated_at FROM habits
WHERE user_id = $1 AND (active OR NOT $2::boolean)
ORDER BY created_at
`

type ListHabitsParams struct {
	UserID     uuid.UUID
	ActiveOnly bool
}

func (q *Queries) ListHabits(ctx context.Context, arg ListHabitsParams) ([]Habit, error) {
	rows, err := q.db.Query(ctx, listHabits, arg.UserID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Habit{}
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Domain,
			&i.DaysOfWeek,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncompleteHabit = `-- name: UncompleteHabit :exec
DELETE FROM habit_completions
WHERE habit_id = $1 AND user_id = $2 AND local_date = $3
`

type UncompleteHabitParams struct {
	HabitID   uuid.UUID
	UserID    uuid.UUID
	LocalDate pgtype.Date
}

func (q *Queries) UncompleteHabit(ctx context.Context, arg UncompleteHabitParams) error {
	_, err := q.db.Exec(ctx, uncompleteHabit, arg.HabitID, arg.UserID, arg.LocalDate)
	return err
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET name = $3, domain = $4, days_of_week = $5, active = $6, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, domain, days_of_week, active, created_at, updated_at
`

type UpdateHabitParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Domain     string
	DaysOfWeek []int16
	Active     bool
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRow(ctx, updateHabit,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Domain,
		arg.DaysOfWeek,
		arg.Active,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Domain,
		&i.DaysOfWeek,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
