// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package exercisesdb

import (
	"time"

	"github.com/google/uuid"
)

type Exercise struct {
	ID               uuid.UUID
	Slug             string
	Name             string
	Category         string
	Equipment        string
	Difficulty       string
	Instructions     string
	VideoUrl         string
	PrimaryMuscles   []string
	SecondaryMuscles []string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	IllustrationSlug string
}
