// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package xpdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const earned = `-- name: Earned :many
WITH people AS (
    -- An unknown zone name falls back to UTC, as users.User.Location does,
    -- rather than failing the whole board.
    SELECT id, COALESCE((SELECT z.name FROM pg_catalog.pg_timezone_names z WHERE z.name = users.timezone LIMIT 1), 'UTC') AS timezone
    FROM users WHERE id = ANY($1::uuid[])
),
habits_kept AS (
    SELECT hc.user_id, count(*)::int AS n
    FROM habit_completions hc
    JOIN habits h ON h.id = hc.habit_id
    WHERE hc.user_id IN (SELECT id FROM people)
      AND hc.local_date >= ($2::text)::date
      AND hc.local_date <  ($3::text)::date
      AND EXTRACT(DOW FROM hc.local_date)::smallint = ANY(h.days_of_week)
    GROUP BY hc.user_id
),
runs AS (
    SELECT user_id, local_date,
           local_date - (ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY local_date))::int AS run
    FROM check_ins
    WHERE user_id IN (SELECT id FROM people)
      AND local_date < ($3::text)::date
),
streak_days AS (
    SELECT user_id, count(*)::int AS n
    FROM (
        SELECT user_id, local_date,
               ROW_NUMBER() OVER (PARTITION BY user_id, run ORDER BY local_date) AS day_in_run
        FROM runs
    ) d
    WHERE day_in_run >= $4::int
      AND local_date >= ($2::text)::date
    GROUP BY user_id
),
workouts AS (
    SELECT user_id, count(*)::int AS n
    FROM (
        SELECT s.user_id,
               ROW_NUMBER() OVER (
                   PARTITION BY s.user_id, (s.ended_at AT TIME ZONE p.timezone)::date
                   ORDER BY s.ended_at
               ) AS nth
        FROM activity_sessions s
        JOIN people p ON p.id = s.user_id
        WHERE s.status = 'completed'
          AND s.ended_at >= $5::timestamptz
          AND s.ended_at <  $6::timestamptz
          AND EXTRACT(EPOCH FROM (s.ended_at - s.started_at)) - s.total_paused_seconds
              >= $7::int
    ) w
    WHERE nth <= $8::int
    GROUP BY user_id
),
milestones AS (
    SELECT user_id, count(*)::int AS n
    FROM goal_milestones
    WHERE user_id IN (SELECT id FROM people)
      AND status = 'completed'
      AND completed_at >= $5::timestamptz AND completed_at < $6::timestamptz
    GROUP BY user_id
),
goals_achieved AS (
    SELECT user_id, count(*)::int AS n
    FROM goals
    WHERE user_id IN (SELECT id FROM people)
      AND status = 'achieved'
      AND closed_at >= $5::timestamptz AND closed_at < $6::timestamptz
    GROUP BY user_id
)
SELECT user_id, 'habit_kept'::text AS kind, n FROM habits_kept
UNION ALL SELECT user_id, 'streak_day', n FROM streak_days
UNION ALL SELECT user_id, 'workout', n FROM workouts
UNION ALL SELECT user_id, 'milestone', n FROM milestones
UNION ALL SELECT user_id, 'goal', n FROM goals_achieved
`

type EarnedParams struct {
	UserIds           []uuid.UUID
	FromDay           string
	ToDay             string
	StreakFrom        int32
	FromAt            time.Time
	ToAt              time.Time
	WorkoutMinSeconds int32
	WorkoutsPerDay    int32
}

type EarnedRow struct {
	UserID uuid.UUID
	Kind   string
	N      int32
}

// What each person earned in a window, by kind. Nothing here is stored: every
// row is counted from the slice that owns it, under the rules in internal/xp.
// Dates are local days (first inclusive, last exclusive); times bound the
// kinds that carry a timestamp. A streak day needs the check-ins before the
// window too, so that scan is open at the start.
func (q *Queries) Earned(ctx context.Context, arg EarnedParams) ([]EarnedRow, error) {
	rows, err := q.db.Query(ctx, earned,
		arg.UserIds,
		arg.FromDay,
		arg.ToDay,
		arg.StreakFrom,
		arg.FromAt,
		arg.ToAt,
		arg.WorkoutMinSeconds,
		arg.WorkoutsPerDay,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EarnedRow{}
	for rows.Next() {
		var i EarnedRow
		if err := rows.Scan(&i.UserID, &i.Kind, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const participants = `-- name: Participants :many
SELECT u.id, u.display_name, u.handle, u.timezone
FROM users u
WHERE u.id = $1
   OR (
     EXISTS (SELECT 1 FROM follows f
             WHERE f.follower_id = $1 AND f.followee_id = u.id AND f.status = 'accepted')
     AND EXISTS (SELECT 1 FROM achievement_sharing s
                 WHERE s.user_id = u.id AND s.category = $2 AND s.shared)
     AND NOT EXISTS (SELECT 1 FROM blocks b
                     WHERE (b.blocker_id = $1 AND b.blocked_id = u.id)
                        OR (b.blocker_id = u.id AND b.blocked_id = $1))
   )
`

type ParticipantsParams struct {
	Viewer   uuid.UUID
	Category string
}

type ParticipantsRow struct {
	ID          uuid.UUID
	DisplayName string
	Handle      *string
	Timezone    string
}

// Who appears on the viewer's board for one sharing category: the viewer, and
// everyone they follow (accepted) who shares that category, minus anybody
// blocked either way. The same rule as the friends feed.
func (q *Queries) Participants(ctx context.Context, arg ParticipantsParams) ([]ParticipantsRow, error) {
	rows, err := q.db.Query(ctx, participants, arg.Viewer, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ParticipantsRow{}
	for rows.Next() {
		var i ParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Handle,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shares = `-- name: Shares :one
SELECT EXISTS (
    SELECT 1 FROM achievement_sharing
    WHERE user_id = $1 AND category = $2 AND shared
)
`

type SharesParams struct {
	UserID   uuid.UUID
	Category string
}

// Whether a person shares one category with followers.
func (q *Queries) Shares(ctx context.Context, arg SharesParams) (bool, error) {
	row := q.db.QueryRow(ctx, shares, arg.UserID, arg.Category)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const workoutsFinished = `-- name: WorkoutsFinished :many
SELECT user_id, count(*)::int AS n
FROM activity_sessions
WHERE user_id = ANY($1::uuid[])
  AND status = 'completed'
  AND ended_at >= $2::timestamptz AND ended_at < $3::timestamptz
GROUP BY user_id
`

type WorkoutsFinishedParams struct {
	UserIds []uuid.UUID
	FromAt  time.Time
	ToAt    time.Time
}

type WorkoutsFinishedRow struct {
	UserID uuid.UUID
	N      int32
}

// Finished sessions per person in a window, uncapped: the workouts board
// counts what was done, like a crew's board does.
func (q *Queries) WorkoutsFinished(ctx context.Context, arg WorkoutsFinishedParams) ([]WorkoutsFinishedRow, error) {
	rows, err := q.db.Query(ctx, workoutsFinished, arg.UserIds, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkoutsFinishedRow{}
	for rows.Next() {
		var i WorkoutsFinishedRow
		if err := rows.Scan(&i.UserID, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
